export const SUB_RULE_LABELS: Record<string, string> = {
  "a-before-consonant": "a before a consonant sound",
  "a-few-count": "a few + countable",
  "a-little-uncount": "a little + uncountable",
  "a-lot-of": "a lot of",
  "a-with-count": "a/an with countable",
  "adj-before-noun": "my/your before a noun",
  "adj-noun": "adjective before a noun",
  "adj-prep": "adjective + preposition",
  "adv-verb": "adverb after a verb",
  "affect-verb": "affect is the verb",
  "after-be": "adverb after am/is/are",
  "already-positive": "already in positives",
  "although-concede": "although = concession",
  "an-before-vowel-sound": "an before a vowel sound",
  "another-one": "another + singular",
  "any-negative-question": "any in questions/negatives",
  "apostrophe-s": "'s for belonging",
  "as-role": "as = role or + clause",
  "at-clock": "at + clock time / night",
  "at-end-of": "at the end of + noun",
  "at-point": "at a point",
  "attach-clause": "who/which/that to attach a clause",
  backshift: "tense usually moves back",
  "base-after": "base verb after the helper",
  "base-after-modal": "base verb after can/could",
  "base-form": "I/you/we/they + base",
  "be-going-to": "am/is/are going to + verb",
  "be-plus-ing": "am/is/are + -ing",
  "be-pp-present": "am/is/are + past participle",
  "be-question": "invert am/is/are",
  "be-used-to-now": "be used to + -ing = accustomed",
  "because-reason": "because = reason",
  "been-back": "been = went and came back",
  "before-verb": "adverb before the main verb",
  "borrow-from": "borrow from someone",
  "bring-here": "bring towards here",
  "by-deadline": "by = not later than",
  "by-future-point": "by + a future point",
  "can-ability": "can for ability/permission",
  "can-count": "countable nouns",
  "could-past": "could as past of can",
  "could-polite": "could for polite requests",
  "decide-to": "decide/hope/refuse + to",
  "despite-noun": "despite / in spite of + noun or -ing",
  "did-base": "did + base",
  "did-plus-base": "did + base verb",
  "did-use-to": "did you use to",
  "do-base": "do + base",
  "do-plus-base": "do + base",
  "do-task": "do for tasks",
  "does-base": "does + base",
  "does-have": "does he have (not has)",
  "does-plus-base": "does + base",
  "doesnt-base": "doesn't + base",
  "dont-base": "don't + base",
  "dont-have-to": "don't have to = not necessary",
  "during-noun": "during + noun",
  "each-one-by-one": "each = one by one",
  "ed-feeling": "-ed how you feel",
  "effect-noun": "effect is the noun",
  "enough-after": "enough after an adjective",
  "enough-noun": "enough + noun",
  "every-group": "every = the group",
  "everyone-singular": "everyone/each/nobody + singular",
  "experience-present-perfect": "life experience → present perfect",
  "facts-simple": "facts use present simple",
  "far-plural": "those = far + plural",
  "far-singular": "that = far + one",
  "fewer-count": "fewer + countable",
  "finished-time-past-simple": "finished time → past simple",
  "first-real": "first conditional = real future",
  "first-then-the": "a first, then the",
  "for-period": "for + length of time",
  "general-no-article": "no article for things in general",
  "get-done": "get something done",
  "going-to-evidence": "going to from evidence",
  "going-to-plan": "going to for a plan",
  "gone-still-there": "gone = still there",
  "good-noun": "good + noun",
  "habit-vs-now": "habit vs now",
  "had-better-warn": "had better = warning",
  "had-pp": "had + past participle",
  "has-he-she-it": "he/she/it has",
  "have-been-ing": "have/has been + -ing",
  "have-done": "have something done",
  "have-has-pp": "have/has + past participle",
  "have-plural-subject": "I/you/we/they have",
  "have-to-rule": "have to from a rule",
  "he-she-it-is": "he/she/it is",
  "he-she-it-s": "he/she/it + -s",
  "hear-sound": "hear = sound reaches you",
  "however-contrast": "however starts a contrast",
  "i-am": "I am",
  "i-he-was": "I/he/she/it was",
  "if-had-would-have": "if + had, would have",
  "if-past-would": "if + past, would",
  "if-present-present": "if + present, present",
  "if-present-will": "if + present, will",
  "if-whether": "reported yes/no: if/whether",
  "in-month-year": "in + month/year/part of day",
  "in-order-to": "in order to + base",
  "in-space": "in a space",
  "in-the-end-finally": "in the end = finally",
  "in-time-spare": "in time = not too late",
  "ing-cause": "-ing what causes it",
  institution: "go to school (no article)",
  interrupt: "background vs interruption",
  "into-space": "into a space",
  irregular: "irregular past forms",
  "irregular-plural": "children's",
  "its-contraction": "it's = it is / it has",
  "its-possessive": "its = belonging",
  "keep-ing": "keep + -ing",
  "lay-object": "lay = put (needs an object)",
  "lend-to": "lend to someone",
  "less-uncount": "less + uncountable",
  "lie-recline": "lie = recline (no object)",
  "like-similar": "like + noun = similar to",
  "listen-to": "listen to = pay attention",
  "look-at": "look at = direct your eyes",
  "make-create": "make for creating",
  "many-count": "many + countable",
  "mind-ing": "mind/suggest/consider + -ing",
  "more-long": "long adjectives: more",
  "much-uncount": "much + uncountable",
  "must-speaker": "must from the speaker",
  "mustnt-forbidden": "mustn't = not allowed",
  "near-plural": "these = near + plural",
  "near-singular": "this = near + one",
  "negative-ing": "isn't/aren't + -ing",
  "negative-past-ing": "wasn't/weren't + -ing",
  "neither-agree": "neither + auxiliary + subject",
  "news-singular": "news/furniture + singular",
  "no-a-uncount": "no a/an with uncountable",
  "no-a-with-uncountable": "no a/an with uncountable nouns",
  "no-extra-object": "no second object in a relative clause",
  "no-plural": "advice/information: no plural",
  "no-to-after-must": "no to after must",
  "no-will-if": "no will in the if-clause",
  "no-would-have-if": "no would have in the if-clause",
  "no-would-if": "no would in the if-clause",
  "not-as": "as … as, not as -er as",
  "not-clause": "no full clause after despite",
  "not-instead-of-me": "do not use a reflexive instead of me",
  "object-after-preposition": "object after a preposition",
  "object-after-verb": "object after the verb",
  "off-out": "off / out of when you leave",
  "on-day": "on + day/date",
  "on-surface": "on a surface",
  "on-time-schedule": "on time = as scheduled",
  "onto-surface": "onto a surface",
  "opposite-tag": "positive statement, negative tag",
  "other-plus-noun": "other + noun",
  "others-alone": "others stands alone",
  "particle-meaning": "verb + particle changes the meaning",
  "past-if-present-result": "past if-clause, present result",
  "piece-of": "a piece of + uncountable",
  "plural-apostrophe": "plural s'",
  "plural-are": "there are + plural",
  "plural-plural": "plural subject + plural verb",
  possibility: "may/might = possibility",
  "pp-result": "present perfect = result",
  "ppc-activity": "present perfect continuous = activity",
  "present-if-past-result": "present if-clause, past result",
  "pronoun-alone": "mine/yours stand alone",
  "pronoun-shift": "I becomes he/she in a report",
  "rather-prefer": "would rather = preference",
  "regular-ed": "regular past: -ed",
  "remember-ing": "remember + -ing = a memory",
  "remember-to": "remember to = don't forget",
  "result-now": "result that is still true now",
  "same-aux": "tag uses the same auxiliary",
  "same-degree": "as + adjective + as",
  "same-person": "myself when subject and object are the same",
  "say-words": "say something",
  "second-unreal": "second conditional = unreal",
  "see-notice": "see = notice",
  "short-er": "short adjectives: -er",
  "should-advice": "should for advice",
  "should-base": "should + base",
  "since-point": "since + starting point",
  "singular-after": "every/each + singular",
  "singular-is": "there is + singular",
  "so-adj": "so + adjective/adverb",
  "so-agree": "so + auxiliary + subject",
  "so-that-clause": "so that + clause",
  "some-offer": "some in offers",
  "some-positive": "some in positives",
  "statement-order": "reported questions: statement order",
  "stative-verbs": "state verbs stay simple",
  "still-continue": "still = it continues",
  "stop-ing-quit": "stop + -ing = quit",
  "stop-to-purpose": "stop to = pause in order to",
  "subject-form": "subject pronoun",
  "such-noun": "such + (a) + adjective + noun",
  "superlative-the": "the + superlative",
  "take-away": "take away from here",
  "tell-person": "tell someone",
  "temporary-now": "temporary situations around now",
  "than-not-that": "than, not that",
  "that-identifying": "that in identifying clauses",
  "the-for-specific": "the for specific things",
  "the-other": "the other = the remaining one",
  "the-specific": "the when you both know which one",
  "third-person-s": "he/she/it + -s",
  "to-destination": "to a destination",
  "too-before": "too before an adjective",
  "until-continue": "until = up to that time",
  "until-now": "since/for until now",
  "used-to-habit": "used to for a finished habit",
  "used-to-habit-past": "used to + verb = past habit",
  "used-to-state": "used to for a past state, not would",
  "verb-ing": "some verbs take -ing",
  "verb-prep": "verb + locked preposition",
  "verb-to": "some verbs take to",
  "want-to": "want/plan/learn + to",
  "was-were-ing": "was/were + -ing",
  "was-were-pp": "was/were + past participle",
  "watch-period": "watch = look for a period",
  "well-health": "feel well",
  "well-verb": "well + verb",
  "were-question": "were you + -ing",
  "which-things": "which for things",
  "while-background": "while + past continuous",
  "while-clause": "while + clause",
  "who-people": "who for people",
  "who-subject": "who = subject",
  "whom-object": "whom = object",
  "will-base": "will + base",
  "will-be-ing": "will be + -ing",
  "will-have-pp": "will have + past participle",
  "will-now": "will for a decision now",
  "wish-past-perfect": "wish + past perfect for the past",
  "wish-past-present": "wish + past for now",
  wont: "won't = will not",
  "would-action": "would for a repeated past action",
  "yet-question-neg": "yet in questions and negatives",
  "you-they-were": "you/we/they were",
  "you-we-they-are": "you/we/they are",
};
