import type { Level, Question, QuestionType } from "../lib/types";

function q(
  topicId: string,
  n: number,
  level: Level,
  type: QuestionType,
  prompt: string,
  answer: string,
  options: string[],
  hint: string,
  explanation: string,
  subRule: string,
): Question {
  return {
    id: `${topicId}-${String(n).padStart(2, "0")}`,
    topicId,
    level,
    type,
    prompt,
    answer,
    options,
    hint,
    explanation,
    subRule,
  };
}

export const PHASE3_QUESTIONS: Question[] = [
  q("already-yet-still", 1, "A2", "gap", "She has ___ finished the report.", "already", ["already", "yet", "still"], "Positive, sooner than expected.", "Already in positives: has already finished.", "already-positive"),
  q("already-yet-still", 2, "A2", "gap", "Have they arrived ___?", "yet", ["already", "yet", "still"], "A question about until now.", "Yet in questions: have they arrived yet?", "yet-question-neg"),
  q("already-yet-still", 3, "A2", "fix", "I haven't already called her.", "I haven't called her yet.", ["I haven't already called her.", "I haven't called her yet.", "I haven't still called her."], "Negative until now.", "Yet in negatives, not already.", "yet-question-neg"),
  q("already-yet-still", 4, "A2", "mcq", "She is ___ at her desk at 7 p.m.", "still", ["yet", "still", "already"], "It continues.", "Still = continuing.", "still-continue"),
  q("already-yet-still", 5, "A2", "gap", "He ___ hasn't replied.", "still", ["yet", "still", "already"], "Surprising that it continues not to happen.", "Still hasn't = continuing negative.", "still-continue"),
  q("already-yet-still", 6, "A2", "mcq", "Which is correct?", "Has the shop opened yet?", ["Has the shop opened yet?", "Has the shop opened still?", "Has the shop yet opened already?"], "Until now, in a question.", "Opened yet.", "yet-question-neg"),
  q("already-yet-still", 7, "A2", "fix", "We already not booked the tickets.", "We haven't booked the tickets yet.", ["We already not booked the tickets.", "We haven't booked the tickets yet.", "We still booked not the tickets."], "Negative + yet.", "Haven't … yet.", "yet-question-neg"),
  q("already-yet-still", 8, "A2", "gap", "It's only 9, but the meeting has ___ started.", "already", ["already", "yet", "still"], "Sooner than you thought.", "Already started.", "already-positive"),

  q("reflexive-pronouns", 1, "A2", "gap", "I made ___ a sandwich.", "myself", ["me", "myself", "mine"], "I did it to me.", "Myself when subject and object are I.", "same-person"),
  q("reflexive-pronouns", 2, "A2", "gap", "She taught ___ to code.", "herself", ["her", "herself", "she"], "Same person.", "Taught herself, not her, for the learner.", "same-person"),
  q("reflexive-pronouns", 3, "A2", "fix", "Please send the file to myself.", "Please send the file to me.", ["Please send the file to myself.", "Please send the file to me.", "Please send the file to I."], "The subject is you, not I.", "To me. Reflexive only if you send it to yourself.", "not-instead-of-me"),
  q("reflexive-pronouns", 4, "A2", "mcq", "Which is correct?", "They enjoyed themselves.", ["They enjoyed themselves.", "They enjoyed them.", "They enjoyed theirselves."], "They + themselves.", "Enjoyed themselves.", "same-person"),
  q("reflexive-pronouns", 5, "A2", "gap", "We can do it ___.", "ourselves", ["us", "ourselves", "ourself"], "We = same group.", "Ourselves, not ourself.", "same-person"),
  q("reflexive-pronouns", 6, "A2", "mcq", "He looked at ___ in the mirror.", "himself", ["him", "himself", "he"], "He looking at he.", "Looked at himself.", "same-person"),
  q("reflexive-pronouns", 7, "A2", "fix", "The manager asked myself to wait.", "The manager asked me to wait.", ["The manager asked myself to wait.", "The manager asked me to wait.", "The manager asked I to wait."], "Different people.", "Asked me.", "not-instead-of-me"),
  q("reflexive-pronouns", 8, "A2", "gap", "Did you hurt ___?", "yourself", ["you", "yourself", "yourselves"], "One person, you.", "Hurt yourself.", "same-person"),

  q("relative-pronouns", 1, "A2", "fix", "The man called is my uncle.", "The man who called is my uncle.", ["The man called is my uncle.", "The man who called is my uncle.", "The man who call is my uncle."], "You need a word to attach the extra clause.", "Who called attaches the clause to the man.", "attach-clause"),
  q("relative-pronouns", 2, "A2", "fix", "This is the laptop I bought it.", "This is the laptop that I bought.", ["This is the laptop I bought it.", "This is the laptop that I bought.", "This is the laptop that I bought it."], "Do not keep it after the relative clause.", "That I bought — no second it.", "no-extra-object"),
  q("relative-pronouns", 3, "A2", "gap", "The woman ___ called is my manager.", "who", ["who", "what", "how"], "Attach the clause about the woman.", "Who called. What and how are not relative pronouns here.", "attach-clause"),
  q("relative-pronouns", 4, "A2", "mcq", "Which sentence attaches the clause correctly?", "The keys that are on the desk are mine.", ["The keys are on the desk are mine.", "The keys that are on the desk are mine.", "The keys that they are on the desk are mine."], "You need that or which, and no extra they.", "That are on the desk.", "attach-clause"),
  q("relative-pronouns", 5, "A2", "fix", "This is the café opened last week.", "This is the café which opened last week.", ["This is the café opened last week.", "This is the café which opened last week.", "This is the café which open last week."], "Attach which or that before opened.", "Which opened last week.", "attach-clause"),
  q("relative-pronouns", 6, "A2", "mcq", "Choose the sentence with no extra object.", "The file that I sent is in your inbox.", ["The file that I sent it is in your inbox.", "The file that I sent is in your inbox.", "The file that I sent them is in your inbox."], "After that I sent, do not add it.", "No second object.", "no-extra-object"),
  q("relative-pronouns", 7, "A2", "fix", "People work here start at 9.", "People who work here start at 9.", ["People work here start at 9.", "People who work here start at 9.", "People who works here start at 9."], "Two verbs need a relative to join them.", "Who work here.", "attach-clause"),
  q("relative-pronouns", 8, "A2", "gap", "She's the colleague ___ helped us.", "who", ["who", "what", "how"], "Attach the clause about the colleague.", "Who helped us.", "attach-clause"),

  q("prepositions-of-movement", 1, "A2", "gap", "We drove ___ the airport.", "to", ["in", "to", "at"], "Destination.", "To the airport = direction.", "to-destination"),
  q("prepositions-of-movement", 2, "A2", "gap", "Please come ___ the kitchen.", "into", ["in", "into", "on"], "Entering a space.", "Into the kitchen.", "into-space"),
  q("prepositions-of-movement", 3, "A2", "fix", "She put the mug in the table.", "She put the mug onto the table.", ["She put the mug in the table.", "She put the mug onto the table.", "She put the mug at the table."], "Onto a surface.", "Onto the table.", "onto-surface"),
  q("prepositions-of-movement", 4, "A2", "mcq", "He took the book ___ the shelf.", "off", ["out", "off", "into"], "Leaving a surface.", "Off the shelf.", "off-out"),
  q("prepositions-of-movement", 5, "A2", "gap", "Get ___ the car. We're late.", "into", ["in", "into", "on"], "Entering.", "Get into the car.", "into-space"),
  q("prepositions-of-movement", 6, "A2", "mcq", "Which shows direction?", "She ran to the gate.", ["She ran at the gate.", "She ran to the gate.", "She ran on the gate."], "To = towards.", "Ran to the gate.", "to-destination"),
  q("prepositions-of-movement", 7, "A2", "fix", "Take the milk out the fridge.", "Take the milk out of the fridge.", ["Take the milk out the fridge.", "Take the milk out of the fridge.", "Take the milk off of fridge."], "Out of a container.", "Out of the fridge.", "off-out"),
  q("prepositions-of-movement", 8, "A2", "gap", "The cat jumped ___ the sofa.", "onto", ["into", "onto", "at"], "Onto a surface.", "Jumped onto the sofa.", "onto-surface"),

  q("dependent-prepositions", 1, "B1", "gap", "I'm interested ___ photography.", "in", ["on", "in", "at"], "Interested + in.", "Interested in.", "adj-prep"),
  q("dependent-prepositions", 2, "B1", "gap", "She's good ___ numbers.", "at", ["in", "at", "on"], "Good + at.", "Good at.", "adj-prep"),
  q("dependent-prepositions", 3, "B1", "fix", "It depends of the weather.", "It depends on the weather.", ["It depends of the weather.", "It depends on the weather.", "It depends at the weather."], "Depend + on.", "Depends on.", "verb-prep"),
  q("dependent-prepositions", 4, "B1", "mcq", "Which is correct?", "Please listen to the announcement.", ["Please listen the announcement.", "Please listen to the announcement.", "Please listen at the announcement."], "Listen + to.", "Listen to.", "verb-prep"),
  q("dependent-prepositions", 5, "B1", "gap", "He's afraid ___ flying.", "of", ["from", "of", "at"], "Afraid + of.", "Afraid of.", "adj-prep"),
  q("dependent-prepositions", 6, "B1", "mcq", "Choose the locked pair.", "proud of", ["proud on", "proud of", "proud at"], "Proud + of.", "Proud of.", "adj-prep"),
  q("dependent-prepositions", 7, "B1", "fix", "We arrived to the hotel at 6.", "We arrived at the hotel at 6.", ["We arrived to the hotel at 6.", "We arrived at the hotel at 6.", "We arrived on the hotel at 6."], "Arrive + at a building.", "Arrive at the hotel.", "verb-prep"),
  q("dependent-prepositions", 8, "B1", "gap", "Don't worry ___ the delay.", "about", ["for", "about", "on"], "Worry + about.", "Worry about.", "verb-prep"),

  q("may-might", 1, "A2", "gap", "Take a coat. It ___ snow.", "might", ["can", "might", "might to"], "Possibility, not ability.", "Might snow.", "possibility"),
  q("may-might", 2, "A2", "gap", "I ___ be late. The train is slow.", "may", ["may", "may to", "can to"], "Possible future.", "May be late.", "possibility"),
  q("may-might", 3, "A2", "fix", "She might to join us later.", "She might join us later.", ["She might to join us later.", "She might join us later.", "She might joining us later."], "Base after might.", "Might join.", "base-after"),
  q("may-might", 4, "A2", "mcq", "Which shows possibility, not ability?", "He might be in a meeting.", ["He can swim 2 km.", "He might be in a meeting.", "He can the meeting."], "Might = perhaps.", "Might be.", "possibility"),
  q("may-might", 5, "A2", "gap", "We ___ not finish today.", "may", ["may", "may not to", "might to"], "Possible negative.", "May not finish.", "possibility"),
  q("may-might", 6, "A2", "mcq", "Choose the correct form.", "It may rain.", ["It may raining.", "It may rain.", "It may to rain."], "Base verb.", "May rain.", "base-after"),
  q("may-might", 7, "A2", "fix", "Can it rain tomorrow?", "It might rain tomorrow.", ["Can it rain tomorrow?", "It might rain tomorrow.", "It can raining tomorrow."], "Can is ability; you mean chance.", "Might rain.", "possibility"),
  q("may-might", 8, "A2", "gap", "I'm not sure. They ___ already know.", "might", ["can", "might", "might to"], "Uncertain.", "Might already know.", "possibility"),

  q("too-enough", 1, "A2", "gap", "This suitcase is ___ heavy to lift.", "too", ["too", "enough", "so"], "More than is OK.", "Too + adjective.", "too-before"),
  q("too-enough", 2, "A2", "gap", "She's old ___ to drive.", "enough", ["too", "enough", "too much"], "As much as needed.", "Adjective + enough.", "enough-after"),
  q("too-enough", 3, "A2", "fix", "The coffee is enough hot.", "The coffee is hot enough.", ["The coffee is enough hot.", "The coffee is hot enough.", "The coffee is too enough hot."], "Enough after the adjective.", "Hot enough.", "enough-after"),
  q("too-enough", 4, "A2", "mcq", "Which is correct?", "It's too noisy here.", ["It's enough noisy here.", "It's too noisy here.", "It's noisy too here."], "Too before adjective.", "Too noisy.", "too-before"),
  q("too-enough", 5, "A2", "gap", "We haven't got ___ chairs.", "enough", ["too", "enough", "too many of"], "Not as many as we need.", "Enough + noun: enough chairs.", "enough-noun"),
  q("too-enough", 6, "A2", "mcq", "There's ___ sugar in this.", "too much", ["enough much", "too much", "too many"], "Sugar is uncountable.", "Too much sugar.", "too-before"),
  q("too-enough", 7, "A2", "fix", "He isn't enough tall for the team.", "He isn't tall enough for the team.", ["He isn't enough tall for the team.", "He isn't tall enough for the team.", "He is too enough tall for the team."], "Tall + enough.", "Tall enough.", "enough-after"),
  q("too-enough", 8, "A2", "gap", "I'm ___ tired to cook.", "too", ["too", "enough", "too enough"], "More tired than is OK.", "Too tired to cook.", "too-before"),

  q("as-as", 1, "A2", "gap", "This room is ___ big ___ that one.", "as / as", ["as / as", "as / than", "more / as"], "Same size.", "As big as.", "same-degree"),
  q("as-as", 2, "A2", "fix", "She is as taller as her sister.", "She is as tall as her sister.", ["She is as taller as her sister.", "She is as tall as her sister.", "She is as more tall as her sister."], "No -er inside as … as.", "As tall as.", "same-degree"),
  q("as-as", 3, "A2", "mcq", "Which is correct?", "Today is not as cold as yesterday.", ["Today is not as colder as yesterday.", "Today is not as cold as yesterday.", "Today is not as cold than yesterday."], "Not as … as.", "Not as cold as.", "not-as"),
  q("as-as", 4, "A2", "gap", "Please reply ___ soon ___ you can.", "as / as", ["as / as", "so / as", "as / than"], "Fixed phrase.", "As soon as.", "same-degree"),
  q("as-as", 5, "A2", "mcq", "Choose the same-degree form.", "as expensive as", ["expensiver as", "as expensive as", "more expensive as"], "Not a comparative with more here.", "As expensive as.", "same-degree"),
  q("as-as", 6, "A2", "fix", "My bag isn't as heavier as yours.", "My bag isn't as heavy as yours.", ["My bag isn't as heavier as yours.", "My bag isn't as heavy as yours.", "My bag isn't as heavy than yours."], "Base adjective.", "As heavy as.", "not-as"),
  q("as-as", 7, "A2", "gap", "He's ___ old ___ I am.", "as / as", ["as / as", "so / than", "as / that"], "Same age.", "As old as I am.", "same-degree"),
  q("as-as", 8, "A2", "mcq", "Which uses as … as?", "This line is as long as that one.", ["This line is longer as that one.", "This line is as long as that one.", "This line is as longer than that one."], "Equal length.", "As long as.", "same-degree"),

  q("adverbs-of-frequency", 1, "A1", "gap", "She ___ arrives before 9.", "always", ["always", "always is", "is always arrives"], "Before the main verb.", "Always arrives.", "before-verb"),
  q("adverbs-of-frequency", 2, "A1", "gap", "He is ___ tired after work.", "usually", ["usually", "usually is", "is usuallys"], "After am/is/are.", "Is usually tired.", "after-be"),
  q("adverbs-of-frequency", 3, "A1", "fix", "They take sometimes the bus.", "They sometimes take the bus.", ["They take sometimes the bus.", "They sometimes take the bus.", "They are sometimes take the bus."], "Before take.", "Sometimes take.", "before-verb"),
  q("adverbs-of-frequency", 4, "A1", "mcq", "Which is correct?", "I am never late.", ["I never am late.", "I am never late.", "I am late never."], "After am.", "Am never late.", "after-be"),
  q("adverbs-of-frequency", 5, "A1", "gap", "We ___ eat out — maybe twice a year.", "rarely", ["rarely", "are rarely eat", "rarely are eat"], "Before eat.", "Rarely eat.", "before-verb"),
  q("adverbs-of-frequency", 6, "A1", "mcq", "Choose the right place.", "She often works from home.", ["She is often works from home.", "She often works from home.", "She often is works from home."], "Before works.", "Often works.", "before-verb"),
  q("adverbs-of-frequency", 7, "A1", "fix", "You always are kind.", "You are always kind.", ["You always are kind.", "You are always kind.", "You always are being kind."], "After are.", "Are always kind.", "after-be"),
  q("adverbs-of-frequency", 8, "A1", "gap", "I ___ drink coffee. I hate the taste.", "never", ["never", "am never drink", "never am drink"], "Before drink.", "Never drink.", "before-verb"),

  q("gerunds-vs-infinitives", 1, "B1", "gap", "I enjoy ___ (read) on the train.", "reading", ["to read", "reading", "read"], "Enjoy + -ing.", "Enjoy reading.", "verb-ing"),
  q("gerunds-vs-infinitives", 2, "B1", "gap", "She wants ___ (leave) early.", "to leave", ["leaving", "to leave", "leave"], "Want + to.", "Wants to leave.", "verb-to"),
  q("gerunds-vs-infinitives", 3, "B1", "fix", "He finished to write the email.", "He finished writing the email.", ["He finished to write the email.", "He finished writing the email.", "He finished write the email."], "Finish + -ing.", "Finished writing.", "verb-ing"),
  q("gerunds-vs-infinitives", 4, "B1", "mcq", "Which is correct?", "We decided to wait.", ["We decided waiting.", "We decided to wait.", "We decided wait."], "Decide + to.", "Decided to wait.", "verb-to"),
  q("gerunds-vs-infinitives", 5, "B1", "gap", "Avoid ___ (use) that door.", "using", ["to use", "using", "use"], "Avoid + -ing.", "Avoid using.", "verb-ing"),
  q("gerunds-vs-infinitives", 6, "B1", "mcq", "Choose the to-infinitive verb.", "hope to see", ["hope seeing", "hope to see", "hope see"], "Hope + to.", "Hope to see.", "verb-to"),
  q("gerunds-vs-infinitives", 7, "B1", "fix", "I enjoy to walk by the river.", "I enjoy walking by the river.", ["I enjoy to walk by the river.", "I enjoy walking by the river.", "I enjoy walk by the river."], "Enjoy + -ing.", "Enjoy walking.", "verb-ing"),
  q("gerunds-vs-infinitives", 8, "B1", "gap", "They hope ___ (win).", "to win", ["winning", "to win", "win"], "Hope + to.", "Hope to win.", "verb-to"),

  q("zero-conditional", 1, "A2", "gap", "If you ___ water to 100°, it ___.", "heat / boils", ["heat / boils", "will heat / boils", "heat / will boils"], "Fact, both present.", "If you heat, it boils.", "if-present-present"),
  q("zero-conditional", 2, "A2", "mcq", "Which is a zero conditional?", "If I am late, my manager gets annoyed.", ["If I will be late, my manager gets annoyed.", "If I am late, my manager gets annoyed.", "If I am late, my manager will got annoyed."], "Routine/fact.", "Present + present.", "if-present-present"),
  q("zero-conditional", 3, "A2", "fix", "If you mix red and blue, it will makes purple.", "If you mix red and blue, it makes purple.", ["If you mix red and blue, it will makes purple.", "If you mix red and blue, it makes purple.", "If you will mix red and blue, it makes purple."], "No will in a fact.", "It makes purple.", "if-present-present"),
  q("zero-conditional", 4, "A2", "gap", "Plants die if they ___ water.", "don't get", ["won't get", "don't get", "didn't get"], "General truth.", "If they don't get water.", "if-present-present"),
  q("zero-conditional", 5, "A2", "mcq", "Choose the fact pattern.", "If you press this, the light comes on.", ["If you will press this, the light comes on.", "If you press this, the light comes on.", "If you press this, the light will coming on."], "Always true.", "Press / comes.", "if-present-present"),
  q("zero-conditional", 6, "A2", "gap", "If the shop ___ empty, it ___ at 6.", "is / closes", ["is / closes", "will be / closes", "is / will closing"], "Routine.", "Is empty, it closes.", "if-present-present"),
  q("zero-conditional", 7, "A2", "fix", "If ice will melt, it becomes water.", "If ice melts, it becomes water.", ["If ice will melt, it becomes water.", "If ice melts, it becomes water.", "If ice melts, it will becomes water."], "No will in the if-clause for facts.", "If ice melts.", "if-present-present"),
  q("zero-conditional", 8, "A2", "mcq", "Which belongs on this page, not first conditional?", "If you don't water plants, they die.", ["If it rains tomorrow, we will cancel.", "If you don't water plants, they die.", "If I were you, I would water them."], "Always true.", "They die — present.", "if-present-present"),

  q("first-conditional", 1, "A2", "gap", "If it ___, we ___ at home.", "rains / will stay", ["rains / will stay", "will rain / stay", "rains / stay"], "Real future.", "If + present, will + base.", "if-present-will"),
  q("first-conditional", 2, "A2", "fix", "If she will call, I will answer.", "If she calls, I will answer.", ["If she will call, I will answer.", "If she calls, I will answer.", "If she will calling, I will answer."], "No will in the if-clause.", "If she calls.", "no-will-if"),
  q("first-conditional", 3, "A2", "mcq", "Which is first conditional?", "If you hurry, you will catch the bus.", ["If you hurry, you catch the bus every day.", "If you hurry, you will catch the bus.", "If you hurried, you would catch the bus."], "Possible future.", "Will catch.", "if-present-will"),
  q("first-conditional", 4, "A2", "gap", "We ___ the meeting if he ___ late.", "will start / is", ["start / will be", "will start / is", "will start / will be"], "Will in the result only.", "Will start if he is late.", "if-present-will"),
  q("first-conditional", 5, "A2", "mcq", "Choose the correct if-clause.", "If I see her, I'll tell her.", ["If I will see her, I'll tell her.", "If I see her, I'll tell her.", "If I saw her, I'll tell her."], "Present after if.", "If I see.", "no-will-if"),
  q("first-conditional", 6, "A2", "gap", "If they ___ the offer, they ___ us.", "accept / will email", ["will accept / email", "accept / will email", "accepted / will email"], "Real possibility.", "Accept / will email.", "if-present-will"),
  q("first-conditional", 7, "A2", "fix", "If you don't leave now, you miss the train tomorrow.", "If you don't leave now, you will miss the train.", ["If you don't leave now, you miss the train tomorrow.", "If you don't leave now, you will miss the train.", "If you won't leave now, you will miss the train."], "Future result needs will.", "You will miss.", "if-present-will"),
  q("first-conditional", 8, "A2", "mcq", "Which is wrong?", "If it will be sunny, we will walk.", ["If it is sunny, we will walk.", "If it will be sunny, we will walk.", "If it's sunny, we'll walk."], "Will does not go in the if-clause.", "If it is sunny.", "no-will-if"),

  q("second-conditional", 1, "B1", "gap", "If I ___ time, I ___ you.", "had / would help", ["have / will help", "had / would help", "had / will help"], "Unreal now.", "If I had, I would help.", "if-past-would"),
  q("second-conditional", 2, "B1", "fix", "If I would have a car, I would drive.", "If I had a car, I would drive.", ["If I would have a car, I would drive.", "If I had a car, I would drive.", "If I have a car, I would drive."], "No would in the if-clause.", "If I had.", "no-would-if"),
  q("second-conditional", 3, "B1", "mcq", "Which is second conditional?", "If I were you, I would wait.", ["If I am you, I will wait.", "If I were you, I would wait.", "If I had been you, I would have waited."], "Unreal advice.", "If I were you.", "if-past-would"),
  q("second-conditional", 4, "B1", "gap", "They ___ move if the rent ___ cheaper.", "would / were", ["will / was", "would / were", "would / is"], "Unreal present.", "Would move if it were cheaper.", "if-past-would"),
  q("second-conditional", 5, "B1", "mcq", "Choose the unreal present.", "If she lived closer, we would meet more.", ["If she lives closer, we will meet more.", "If she lived closer, we would meet more.", "If she had lived closer, we would have met more."], "Not true now.", "Lived / would meet.", "if-past-would"),
  q("second-conditional", 6, "B1", "gap", "If we ___ the budget, we ___ hire two people.", "had / would", ["have / will", "had / would", "had / will"], "Imaginary now.", "If we had, we would hire.", "if-past-would"),
  q("second-conditional", 7, "B1", "fix", "If he would work nights, he would earn more.", "If he worked nights, he would earn more.", ["If he would work nights, he would earn more.", "If he worked nights, he would earn more.", "If he works nights, he would earn more."], "Past form in the if-clause.", "If he worked.", "no-would-if"),
  q("second-conditional", 8, "B1", "mcq", "Which uses were for advice?", "If I were you, I'd say no.", ["If I was you, I will say no.", "If I were you, I'd say no.", "If I were you, I said no."], "If I were you.", "Were + would.", "if-past-would"),

  q("passive-present", 1, "B1", "gap", "English ___ (speak) here.", "is spoken", ["speaks", "is spoken", "is speak"], "Thing receiving the action.", "Is spoken.", "be-pp-present"),
  q("passive-present", 2, "B1", "fix", "The reports are write every Friday.", "The reports are written every Friday.", ["The reports are write every Friday.", "The reports are written every Friday.", "The reports written every Friday."], "Are + participle.", "Are written.", "be-pp-present"),
  q("passive-present", 3, "B1", "mcq", "Which is present passive?", "The office is cleaned at 6.", ["The office cleans at 6.", "The office is cleaned at 6.", "The office is clean at 6."], "Is + cleaned.", "Is cleaned.", "be-pp-present"),
  q("passive-present", 4, "B1", "gap", "These phones ___ (make) in Vietnam.", "are made", ["make", "are made", "are make"], "Plural subject.", "Are made.", "be-pp-present"),
  q("passive-present", 5, "B1", "mcq", "Choose the correct form.", "The data is stored on the server.", ["The data is store on the server.", "The data is stored on the server.", "The data are storing on the server."], "Is + stored.", "Is stored.", "be-pp-present"),
  q("passive-present", 6, "B1", "gap", "Visitors ___ (not / allow) after 8.", "aren't allowed", ["don't allow", "aren't allowed", "aren't allow"], "Negative passive.", "Aren't allowed.", "be-pp-present"),
  q("passive-present", 7, "B1", "fix", "Lunch is serving at 12.", "Lunch is served at 12.", ["Lunch is serving at 12.", "Lunch is served at 12.", "Lunch served at 12."], "Is + served.", "Is served.", "be-pp-present"),
  q("passive-present", 8, "B1", "gap", "The results ___ (publish) on Monday.", "are published", ["publish", "are published", "are publishing"], "Present routine.", "Are published.", "be-pp-present"),

  q("passive-past", 1, "B1", "gap", "The window ___ (break) last night.", "was broken", ["broke", "was broken", "was broke"], "Past + thing receiving action.", "Was broken.", "was-were-pp"),
  q("passive-past", 2, "B1", "fix", "The emails was sent at 5.", "The emails were sent at 5.", ["The emails was sent at 5.", "The emails were sent at 5.", "The emails were send at 5."], "Emails is plural.", "Were sent.", "was-were-pp"),
  q("passive-past", 3, "B1", "mcq", "Which is past passive?", "The contract was signed in May.", ["The contract signed in May.", "The contract was signed in May.", "The contract was sign in May."], "Was + signed.", "Was signed.", "was-were-pp"),
  q("passive-past", 4, "B1", "gap", "Two seats ___ (book) yesterday.", "were booked", ["booked", "were booked", "was booked"], "Plural.", "Were booked.", "was-were-pp"),
  q("passive-past", 5, "B1", "mcq", "Choose the correct sentence.", "My phone was stolen.", ["My phone was stole.", "My phone was stolen.", "My phone stolen."], "Was + stolen.", "Was stolen.", "was-were-pp"),
  q("passive-past", 6, "B1", "gap", "The meeting ___ (not / cancel).", "wasn't cancelled", ["didn't cancel", "wasn't cancelled", "wasn't cancel"], "Negative past passive.", "Wasn't cancelled.", "was-were-pp"),
  q("passive-past", 7, "B1", "fix", "The cake were eaten.", "The cake was eaten.", ["The cake were eaten.", "The cake was eaten.", "The cake was eat."], "Cake is singular.", "Was eaten.", "was-were-pp"),
  q("passive-past", 8, "B1", "gap", "These photos ___ (take) in 2019.", "were taken", ["took", "were taken", "were took"], "Plural + past.", "Were taken.", "was-were-pp"),

  q("future-simple", 1, "A2", "gap", "I ___ (call) you after lunch.", "will call", ["call", "will call", "will calling"], "Will + base.", "Will call.", "will-base"),
  q("future-simple", 2, "A2", "fix", "She will waits outside.", "She will wait outside.", ["She will waits outside.", "She will wait outside.", "She will waiting outside."], "No -s after will.", "Will wait.", "will-base"),
  q("future-simple", 3, "A2", "mcq", "Which is correct?", "They won't be late.", ["They won't to be late.", "They won't be late.", "They willn't be late."], "Won't + base.", "Won't be.", "wont"),
  q("future-simple", 4, "A2", "gap", "___ you ___ (save) me a seat?", "Will / save", ["Do / save", "Will / save", "Will / saving"], "Will question.", "Will you save…?", "will-base"),
  q("future-simple", 5, "A2", "mcq", "Choose the form on this page.", "I will send the file.", ["I am going send the file.", "I will send the file.", "I will sending the file."], "Will + send.", "Will send.", "will-base"),
  q("future-simple", 6, "A2", "gap", "He ___ (not / forget).", "won't forget", ["doesn't forget", "won't forget", "won't forgetting"], "Will not.", "Won't forget.", "wont"),
  q("future-simple", 7, "A2", "fix", "We will to meet at 6.", "We will meet at 6.", ["We will to meet at 6.", "We will meet at 6.", "We will meeting at 6."], "No to after will.", "Will meet.", "will-base"),
  q("future-simple", 8, "A2", "gap", "The shop ___ (open) at 10 tomorrow.", "will open", ["opens will", "will open", "will opens"], "Will + base.", "Will open.", "will-base"),

  q("future-continuous", 1, "B1", "gap", "This time tomorrow I ___ (sit) on a train.", "will be sitting", ["will sit", "will be sitting", "will sitting"], "In progress at a future time.", "Will be sitting.", "will-be-ing"),
  q("future-continuous", 2, "B1", "fix", "At 9 she will working.", "At 9 she will be working.", ["At 9 she will working.", "At 9 she will be working.", "At 9 she will works."], "Will be + -ing.", "Will be working.", "will-be-ing"),
  q("future-continuous", 3, "B1", "mcq", "Which is future continuous?", "Don't call at 8. I'll be having dinner.", ["Don't call at 8. I'll have dinner.", "Don't call at 8. I'll be having dinner.", "Don't call at 8. I having dinner."], "Action in progress then.", "Will be having.", "will-be-ing"),
  q("future-continuous", 4, "B1", "gap", "They ___ (not / use) the room at noon.", "won't be using", ["won't use", "won't be using", "won't be use"], "Negative.", "Won't be using.", "will-be-ing"),
  q("future-continuous", 5, "B1", "mcq", "Choose the correct form.", "We'll be waiting at the gate.", ["We'll waiting at the gate.", "We'll be waiting at the gate.", "We'll be wait at the gate."], "Will be + waiting.", "Will be waiting.", "will-be-ing"),
  q("future-continuous", 6, "B1", "gap", "___ you ___ (work) at 6?", "Will / be working", ["Will / work", "Will / be working", "Do / be working"], "Question.", "Will you be working…?", "will-be-ing"),
  q("future-continuous", 7, "B1", "fix", "I will be travel all morning.", "I will be travelling all morning.", ["I will be travel all morning.", "I will be travelling all morning.", "I will travelling all morning."], "Be + -ing.", "Will be travelling.", "will-be-ing"),
  q("future-continuous", 8, "B1", "gap", "At midnight the servers ___ (run) a backup.", "will be running", ["will run just", "will be running", "will running"], "In progress at that time.", "Will be running.", "will-be-ing"),

  q("past-perfect", 1, "B1", "gap", "The film ___ (start) when we arrived.", "had started", ["already started", "had started", "has started"], "Earlier past.", "Had started (before we arrived).", "had-pp"),
  q("past-perfect", 2, "B1", "fix", "She has left before I got there.", "She had left before I got there.", ["She has left before I got there.", "She had left before I got there.", "She left had before I got there."], "Two past times; earlier needs had.", "Had left.", "had-pp"),
  q("past-perfect", 3, "B1", "mcq", "Which is past perfect?", "I had locked the door before I left.", ["I locked the door before I had leave.", "I had locked the door before I left.", "I have locked the door before I left."], "Earlier action: had locked.", "Had locked.", "had-pp"),
  q("past-perfect", 4, "B1", "gap", "They ___ (not / meet) until that day.", "hadn't met", ["didn't met", "hadn't met", "haven't met"], "Until a past point.", "Hadn't met.", "had-pp"),
  q("past-perfect", 5, "B1", "mcq", "Choose the earlier event.", "After she had eaten, she opened her laptop.", ["After she ate, she had opened her laptop.", "After she had eaten, she opened her laptop.", "After she has eaten, she opened her laptop."], "Had eaten first.", "Had eaten, then opened.", "had-pp"),
  q("past-perfect", 6, "B1", "gap", "We ___ (already / book) when they called.", "had already booked", ["have already booked", "had already booked", "already booked had"], "Earlier than they called.", "Had already booked.", "had-pp"),
  q("past-perfect", 7, "B1", "fix", "He didn't had seen the email.", "He hadn't seen the email.", ["He didn't had seen the email.", "He hadn't seen the email.", "He hadn't saw the email."], "Hadn't + participle.", "Hadn't seen.", "had-pp"),
  q("past-perfect", 8, "B1", "gap", "By the time the taxi came, I ___ (give up).", "had given up", ["already gave up", "had given up", "have given up"], "Earlier past.", "Had given up.", "had-pp"),

  q("present-perfect-continuous", 1, "B1", "gap", "I ___ (wait) for an hour.", "have been waiting", ["have waited", "have been waiting", "am waiting since an hour"], "Activity up to now.", "Have been waiting.", "have-been-ing"),
  q("present-perfect-continuous", 2, "B1", "fix", "She has been write all morning.", "She has been writing all morning.", ["She has been write all morning.", "She has been writing all morning.", "She have been writing all morning."], "Has been + -ing.", "Has been writing.", "have-been-ing"),
  q("present-perfect-continuous", 3, "B1", "mcq", "Which is present perfect continuous?", "They have been living here since 2020.", ["They live here since 2020.", "They have been living here since 2020.", "They have living here since 2020."], "Have been + -ing.", "Have been living.", "have-been-ing"),
  q("present-perfect-continuous", 4, "B1", "gap", "It ___ (rain) all day.", "has been raining", ["rains all day", "has been raining", "has raining"], "Activity continuing.", "Has been raining.", "have-been-ing"),
  q("present-perfect-continuous", 5, "B1", "mcq", "Choose the correct form.", "We haven't been sleeping well.", ["We haven't sleeping well.", "We haven't been sleeping well.", "We hasn't been sleeping well."], "Haven't been + -ing.", "Haven't been sleeping.", "have-been-ing"),
  q("present-perfect-continuous", 6, "B1", "gap", "How long ___ you ___ (learn) Arabic?", "have / been learning", ["do / learn", "have / been learning", "have / learning"], "How long + activity.", "Have you been learning…?", "have-been-ing"),
  q("present-perfect-continuous", 7, "B1", "fix", "I have waiting since 8.", "I have been waiting since 8.", ["I have waiting since 8.", "I have been waiting since 8.", "I am been waiting since 8."], "Need been.", "Have been waiting.", "have-been-ing"),
  q("present-perfect-continuous", 8, "B1", "gap", "He ___ (not / feel) well lately.", "hasn't been feeling", ["doesn't been feel", "hasn't been feeling", "hasn't feeling"], "Lately + activity.", "Hasn't been feeling.", "have-been-ing"),

  q("reported-statements", 1, "B1", "gap", "“I work here.” → She said she ___ there.", "worked", ["works", "worked", "work"], "Tense moves back.", "Worked.", "backshift"),
  q("reported-statements", 2, "B1", "fix", "He said he is tired yesterday.", "He said he was tired.", ["He said he is tired yesterday.", "He said he was tired.", "He said he tired."], "Past report of a past feeling.", "Was tired.", "backshift"),
  q("reported-statements", 3, "B1", "mcq", "“I will call you.” → She said she ___ me.", "would call", ["will call", "would call", "calls"], "Will → would.", "Would call.", "backshift"),
  q("reported-statements", 4, "B1", "gap", "“We have finished.” → They said they ___ .", "had finished", ["have finished", "had finished", "finished have"], "Have → had.", "Had finished.", "backshift"),
  q("reported-statements", 5, "B1", "mcq", "Pronouns change: “I’ll send my notes.” → He said he would send ___ notes.", "his", ["my", "his", "him"], "My → his.", "His notes.", "pronoun-shift"),
  q("reported-statements", 6, "B1", "gap", "“I can help.” → She said she ___ help.", "could", ["can", "could", "can to"], "Can → could.", "Could help.", "backshift"),
  q("reported-statements", 7, "B1", "fix", "Tom said I was on holiday.", "Tom said he was on holiday.", ["Tom said I was on holiday.", "Tom said he was on holiday.", "Tom said him was on holiday."], "I in the quote becomes he.", "He was.", "pronoun-shift"),
  q("reported-statements", 8, "B1", "mcq", "Which is a reported statement?", "She said the shop closed at 6.", ["She said the shop close at 6.", "She said the shop closed at 6.", "She told the shop closed at 6 without a person."], "Said + past.", "Closed.", "backshift"),

  q("third-conditional", 1, "B1", "gap", "If I ___ earlier, I ___ the train.", "had left / would have caught", ["left / would catch", "had left / would have caught", "had left / would catch"], "Unreal past.", "Had left / would have caught.", "if-had-would-have"),
  q("third-conditional", 2, "B1", "fix", "If I would have studied, I would have passed.", "If I had studied, I would have passed.", ["If I would have studied, I would have passed.", "If I had studied, I would have passed.", "If I studied, I would have passed."], "If + had, not would have.", "If I had studied.", "no-would-have-if"),
  q("third-conditional", 3, "B1", "mcq", "Which is third conditional?", "If we had booked sooner, we would have paid less.", ["If we booked sooner, we would pay less.", "If we had booked sooner, we would have paid less.", "If we had booked sooner, we would pay less now."], "Both halves about the past.", "Would have paid.", "if-had-would-have"),
  q("third-conditional", 4, "B1", "gap", "She ___ the job if she ___ the form.", "would have got / had sent", ["would get / sent", "would have got / had sent", "would have got / sent"], "Unreal past.", "Would have got if she had sent.", "if-had-would-have"),
  q("third-conditional", 5, "B1", "mcq", "Choose the correct if-clause.", "If they had left at 6, they would have arrived.", ["If they would have left at 6, they would have arrived.", "If they had left at 6, they would have arrived.", "If they left at 6, they would have arrived."], "Had + participle.", "If they had left.", "no-would-have-if"),
  q("third-conditional", 6, "B1", "gap", "We ___ if you ___ us.", "would have waited / had called", ["would wait / called", "would have waited / had called", "would have waited / called"], "Past imaginary.", "Would have waited / had called.", "if-had-would-have"),
  q("third-conditional", 7, "B1", "fix", "If he had drove, we would have been on time.", "If he had driven, we would have been on time.", ["If he had drove, we would have been on time.", "If he had driven, we would have been on time.", "If he drove, we would have been on time."], "Had + driven.", "Had driven.", "if-had-would-have"),
  q("third-conditional", 8, "B1", "mcq", "Which result belongs to third conditional?", "I would have called you.", ["I would call you now.", "I would have called you.", "I will have called you."], "Would have + participle.", "Would have called.", "if-had-would-have"),

  q("mixed-conditionals", 1, "B2", "mcq", "Choose the sentence: the job was then, Berlin is now.", "If I had taken that job, I would be in Berlin now.", ["If I had taken that job, I would have been in Berlin now.", "If I had taken that job, I would be in Berlin now.", "If I took that job, I would have been in Berlin now."], "Now = would + base.", "Would be now.", "past-if-present-result"),
  q("mixed-conditionals", 2, "B2", "gap", "If she ___ medicine, she ___ a doctor today.", "had studied / would be", ["studied / would have been", "had studied / would be", "had studied / would have been"], "Past study, present job.", "Had studied / would be.", "past-if-present-result"),
  q("mixed-conditionals", 3, "B2", "fix", "If I had slept more, I would have been awake now.", "If I had slept more, I would be awake now.", ["If I had slept more, I would have been awake now.", "If I had slept more, I would be awake now.", "If I slept more, I would have been awake now."], "Result is now.", "Would be awake now.", "past-if-present-result"),
  q("mixed-conditionals", 4, "B2", "mcq", "Which is mixed, not pure third?", "If you had listened, you wouldn't be stuck now.", ["If you had listened, you wouldn't have been stuck yesterday.", "If you had listened, you wouldn't be stuck now.", "If you listened, you wouldn't have been stuck now."], "Now in the result.", "Wouldn't be stuck now.", "past-if-present-result"),
  q("mixed-conditionals", 5, "B2", "gap", "If we ___ the earlier train, we ___ at the hotel now.", "had caught / would be", ["caught / would have been", "had caught / would be", "had caught / would have been"], "Past miss, present location.", "Had caught / would be.", "past-if-present-result"),
  q("mixed-conditionals", 6, "B2", "mcq", "Choose the present result.", "would own a flat now", ["would have owned a flat now", "would own a flat now", "will own a flat now"], "Would + base + now.", "Would own now.", "past-if-present-result"),
  q("mixed-conditionals", 7, "B2", "fix", "If he would have saved, he would be free of debt now.", "If he had saved, he would be free of debt now.", ["If he would have saved, he would be free of debt now.", "If he had saved, he would be free of debt now.", "If he had saved, he would have been free of debt now."], "If + had; result now.", "Had saved / would be.", "past-if-present-result"),
  q("mixed-conditionals", 8, "B2", "gap", "If I ___ your number, I ___ you yesterday.", "knew / would have called", ["had known / would call", "knew / would have called", "know / would have called"], "Unreal present knowledge, past missed call.", "If I knew (now), I would have called (then).", "present-if-past-result"),

  q("was-were", 1, "A1", "gap", "I ___ tired last night.", "was", ["was", "were", "am"], "I takes was.", "I was.", "i-he-was"),
  q("was-were", 2, "A1", "gap", "They ___ in Lisbon in May.", "were", ["was", "were", "are"], "They takes were.", "They were.", "you-they-were"),
  q("was-were", 3, "A1", "fix", "She were at the office.", "She was at the office.", ["She were at the office.", "She was at the office.", "She was be at the office."], "She takes was.", "She was.", "i-he-was"),
  q("was-were", 4, "A1", "mcq", "Which is correct?", "We were late.", ["We was late.", "We were late.", "We were be late."], "We takes were.", "We were.", "you-they-were"),
  q("was-were", 5, "A1", "gap", "___ you at home?", "Were", ["Was", "Were", "Are"], "You takes were.", "Were you…?", "you-they-were"),
  q("was-were", 6, "A1", "mcq", "Choose the pair.", "It was cold.", ["It were cold.", "It was cold.", "It was be cold."], "It takes was.", "It was.", "i-he-was"),
  q("was-were", 7, "A1", "fix", "You was very kind.", "You were very kind.", ["You was very kind.", "You were very kind.", "You were be very kind."], "You takes were.", "You were.", "you-they-were"),
  q("was-were", 8, "A1", "gap", "The shops ___ closed on Sunday.", "were", ["was", "were", "is"], "Shops is plural.", "Were closed.", "you-they-were"),

  q("have-has", 1, "A1", "gap", "I ___ two brothers.", "have", ["have", "has", "having"], "I takes have.", "I have.", "have-plural-subject"),
  q("have-has", 2, "A1", "gap", "She ___ a new laptop.", "has", ["have", "has", "haves"], "She takes has.", "She has.", "has-he-she-it"),
  q("have-has", 3, "A1", "fix", "He have a meeting at 3.", "He has a meeting at 3.", ["He have a meeting at 3.", "He has a meeting at 3.", "He haves a meeting at 3."], "He takes has.", "He has.", "has-he-she-it"),
  q("have-has", 4, "A1", "mcq", "Which is correct?", "They have a garden.", ["They has a garden.", "They have a garden.", "They haves a garden."], "They takes have.", "They have.", "have-plural-subject"),
  q("have-has", 5, "A1", "gap", "___ she ___ a spare key?", "Does / have", ["Does / have", "Does / has", "Do / has"], "Questions: does she have.", "Does she have…? Not has in the question with does.", "does-have"),
  q("have-has", 6, "A1", "mcq", "Choose the negative.", "We don't have time.", ["We doesn't have time.", "We don't have time.", "We don't has time."], "We + don't have.", "Don't have.", "have-plural-subject"),
  q("have-has", 7, "A1", "fix", "The office have a lift.", "The office has a lift.", ["The office have a lift.", "The office has a lift.", "The office haves a lift."], "Office is it.", "Has a lift.", "has-he-she-it"),
  q("have-has", 8, "A1", "gap", "You ___ my number.", "have", ["have", "has", "having"], "You takes have.", "You have.", "have-plural-subject"),

  q("question-tags", 1, "A2", "gap", "You're tired, ___ you?", "aren't", ["are", "aren't", "don't"], "Positive statement → negative tag.", "Aren't you?", "opposite-tag"),
  q("question-tags", 2, "A2", "gap", "She doesn't drive, ___ she?", "does", ["does", "doesn't", "is"], "Negative statement → positive tag.", "Does she?", "opposite-tag"),
  q("question-tags", 3, "A2", "fix", "They were late, were they?", "They were late, weren't they?", ["They were late, were they?", "They were late, weren't they?", "They were late, didn't they?"], "Positive → negative tag.", "Weren't they?", "opposite-tag"),
  q("question-tags", 4, "A2", "mcq", "Which is correct?", "It's cold, isn't it?", ["It's cold, is it?", "It's cold, isn't it?", "It's cold, doesn't it?"], "Is → isn't it.", "Isn't it?", "same-aux"),
  q("question-tags", 5, "A2", "gap", "You haven't eaten, ___ you?", "have", ["have", "haven't", "did"], "Haven't → have you?", "Have you?", "opposite-tag"),
  q("question-tags", 6, "A2", "mcq", "Choose the matching auxiliary.", "She can swim, can't she?", ["She can swim, doesn't she?", "She can swim, can't she?", "She can swim, isn't she?"], "Can → can't she.", "Can't she?", "same-aux"),
  q("question-tags", 7, "A2", "fix", "We should leave, we shouldn't?", "We should leave, shouldn't we?", ["We should leave, we shouldn't?", "We should leave, shouldn't we?", "We should leave, don't we?"], "Tag repeats should.", "Shouldn't we?", "same-aux"),
  q("question-tags", 8, "A2", "gap", "He won't mind, ___ he?", "will", ["will", "won't", "does"], "Won't → will he?", "Will he?", "opposite-tag"),

  q("indirect-questions", 1, "B1", "mcq", "Which is an indirect question?", "Could you tell me where the station is?", ["Could you tell me where is the station?", "Could you tell me where the station is?", "Could you tell me where does the station is?"], "Statement order after where.", "Where the station is.", "statement-order"),
  q("indirect-questions", 2, "B1", "fix", "I wonder where does she live.", "I wonder where she lives.", ["I wonder where does she live.", "I wonder where she lives.", "I wonder where she does live."], "No does after where here.", "Where she lives.", "statement-order"),
  q("indirect-questions", 3, "B1", "gap", "Do you know what time it ___ ?", "starts", ["does start", "starts", "start it"], "Statement order.", "What time it starts.", "statement-order"),
  q("indirect-questions", 4, "B1", "mcq", "Choose the correct clause.", "I don't know if he is coming.", ["I don't know if is he coming.", "I don't know if he is coming.", "I don't know if does he coming."], "If + statement order.", "If he is coming.", "statement-order"),
  q("indirect-questions", 5, "B1", "gap", "Could you tell me how much this ___ ?", "costs", ["does cost", "costs", "cost it"], "No do.", "How much this costs.", "statement-order"),
  q("indirect-questions", 6, "B1", "fix", "She asked me where was the file.", "She asked me where the file was.", ["She asked me where was the file.", "She asked me where the file was.", "She asked me where did the file was."], "Was goes after the subject.", "Where the file was.", "statement-order"),
  q("indirect-questions", 7, "B1", "mcq", "Which is wrong?", "Do you know where does she work?", ["Do you know where she works?", "Do you know where does she work?", "Could you tell me where she works?"], "Does is extra.", "Where she works.", "statement-order"),
  q("indirect-questions", 8, "B1", "gap", "I can't remember why they ___ late.", "were", ["were", "did be", "was"], "Statement order.", "Why they were late.", "statement-order"),

  q("used-to-vs-would", 1, "B1", "mcq", "Choose the sentence about a motorbike I owned years ago.", "I used to have a motorbike.", ["I would have a motorbike.", "I used to have a motorbike.", "I would had a motorbike."], "Would does not work for states.", "Used to have.", "used-to-state"),
  q("used-to-vs-would", 2, "B1", "gap", "Every summer we ___ camp by the lake.", "would", ["used", "would", "would to"], "Repeated past action: would is OK.", "Would camp.", "would-action"),
  q("used-to-vs-would", 3, "B1", "fix", "I would be shy as a child.", "I used to be shy as a child.", ["I would be shy as a child.", "I used to be shy as a child.", "I would to be shy as a child."], "Be shy is a state.", "Used to be.", "used-to-state"),
  q("used-to-vs-would", 4, "B1", "mcq", "Which can talk about owning a bike years ago?", "used to", ["would", "used to", "would to"], "Used to covers both.", "Used to.", "used-to-state"),
  q("used-to-vs-would", 5, "B1", "gap", "On Sundays he ___ walk to the bakery.", "would", ["would", "would to", "used"], "Repeated action.", "Would walk.", "would-action"),
  q("used-to-vs-would", 6, "B1", "mcq", "Choose the state sentence.", "She used to live in Osaka.", ["She would live in Osaka every year.", "She used to live in Osaka.", "She would living in Osaka."], "Live = state here.", "Used to live.", "used-to-state"),
  q("used-to-vs-would", 7, "B1", "fix", "They would own a shop on the corner.", "They used to own a shop on the corner.", ["They would own a shop on the corner.", "They used to own a shop on the corner.", "They would owned a shop on the corner."], "Own is a state.", "Used to own.", "used-to-state"),
  q("used-to-vs-would", 8, "B1", "gap", "When we were kids we ___ play until dark.", "would", ["used to to", "would", "would playing"], "Repeated action.", "Would play. Used to play is also fine.", "would-action"),

  q("used-to-vs-be-used-to", 1, "B1", "mcq", "Choose the sentence about a habit that ended.", "I used to smoke.", ["I am used to smoke.", "I used to smoke.", "I am used to smoking years ago."], "Used to + verb.", "Used to smoke.", "used-to-habit-past"),
  q("used-to-vs-be-used-to", 2, "B1", "gap", "I ___ the noise now. I sleep fine.", "am used to", ["used to", "am used to", "used to to"], "Accustomed now.", "Am used to the noise.", "be-used-to-now"),
  q("used-to-vs-be-used-to", 3, "B1", "fix", "She is used to work nights.", "She is used to working nights.", ["She is used to work nights.", "She is used to working nights.", "She used to working nights."], "Be used to + -ing.", "Used to working.", "be-used-to-now"),
  q("used-to-vs-be-used-to", 4, "B1", "mcq", "Which means accustomed?", "He is used to early starts.", ["He used to early starts.", "He is used to early starts.", "He used to be early starts."], "Be used to + noun.", "Is used to.", "be-used-to-now"),
  q("used-to-vs-be-used-to", 5, "B1", "gap", "We ___ live by the sea, but we moved.", "used to", ["are used to", "used to", "are used to living then"], "Past, not true now.", "Used to live.", "used-to-habit-past"),
  q("used-to-vs-be-used-to", 6, "B1", "mcq", "Choose the -ing pattern.", "I'm used to getting up at 5.", ["I used to getting up at 5.", "I'm used to getting up at 5.", "I'm used to get up at 5."], "Be used to + -ing.", "Used to getting.", "be-used-to-now"),
  q("used-to-vs-be-used-to", 7, "B1", "fix", "I used to the cold weather now.", "I am used to the cold weather now.", ["I used to the cold weather now.", "I am used to the cold weather now.", "I am used the cold weather now."], "Need am used to.", "Am used to.", "be-used-to-now"),
  q("used-to-vs-be-used-to", 8, "B1", "gap", "Did you ___ wear glasses?", "use to", ["used to", "use to", "be used to"], "Did + use to.", "Did you use to wear…?", "used-to-habit-past"),

  q("adjective-vs-adverb", 1, "A2", "gap", "She is a ___ worker.", "careful", ["careful", "carefully", "carefuly"], "Before a noun.", "A careful worker.", "adj-noun"),
  q("adjective-vs-adverb", 2, "A2", "gap", "She works ___.", "carefully", ["careful", "carefully", "carefuly"], "How she works.", "Works carefully.", "adv-verb"),
  q("adjective-vs-adverb", 3, "A2", "fix", "Please speak slow.", "Please speak slowly.", ["Please speak slow.", "Please speak slowly.", "Please speak slowerly."], "Speak is a verb.", "Speak slowly.", "adv-verb"),
  q("adjective-vs-adverb", 4, "A2", "mcq", "Which is correct?", "It was a quiet night.", ["It was a quietly night.", "It was a quiet night.", "It was quiet nightly."], "Night is a noun.", "A quiet night.", "adj-noun"),
  q("adjective-vs-adverb", 5, "A2", "gap", "The train arrived ___.", "late", ["lately", "late", "latelly"], "Late can be an adverb of time.", "Arrived late.", "adv-verb"),
  q("adjective-vs-adverb", 6, "A2", "mcq", "Choose the adjective after be.", "The instructions are clear.", ["The instructions are clearly.", "The instructions are clear.", "The instructions are clearlier."], "Be + adjective.", "Are clear.", "adj-noun"),
  q("adjective-vs-adverb", 7, "A2", "fix", "He opened the box careful.", "He opened the box carefully.", ["He opened the box careful.", "He opened the box carefully.", "He opened the box carefuly."], "Opened = verb.", "Opened carefully.", "adv-verb"),
  q("adjective-vs-adverb", 8, "A2", "gap", "That's a ___ idea.", "simple", ["simple", "simply", "simplely"], "Idea is a noun.", "A simple idea.", "adj-noun"),

  q("a-few-vs-a-little", 1, "A2", "gap", "I have ___ emails to send.", "a few", ["a little", "a few", "a few email"], "Emails are countable.", "A few emails.", "a-few-count"),
  q("a-few-vs-a-little", 2, "A2", "gap", "We have ___ milk left.", "a little", ["a few", "a little", "a few milks"], "Milk is uncountable.", "A little milk.", "a-little-uncount"),
  q("a-few-vs-a-little", 3, "A2", "fix", "Give me a few water.", "Give me a little water.", ["Give me a few water.", "Give me a little water.", "Give me few waters."], "Water is uncountable.", "A little water.", "a-little-uncount"),
  q("a-few-vs-a-little", 4, "A2", "mcq", "Which is correct?", "A few people stayed.", ["A little people stayed.", "A few people stayed.", "A few person stayed."], "People is countable.", "A few people.", "a-few-count"),
  q("a-few-vs-a-little", 5, "A2", "gap", "There's ___ hope, but not much.", "a little", ["a few", "a little", "few hopes"], "Hope is uncountable here.", "A little hope.", "a-little-uncount"),
  q("a-few-vs-a-little", 6, "A2", "mcq", "Choose countable.", "a few chairs", ["a little chairs", "a few chairs", "a little chair"], "Chairs are countable.", "A few chairs.", "a-few-count"),
  q("a-few-vs-a-little", 7, "A2", "fix", "I need a few time.", "I need a little time.", ["I need a few time.", "I need a little time.", "I need few times."], "Time as duration is uncountable.", "A little time.", "a-little-uncount"),
  q("a-few-vs-a-little", 8, "A2", "gap", "___ questions came up in the meeting.", "A few", ["A little", "A few", "Little questions"], "Questions are countable.", "A few questions.", "a-few-count"),
];
