import type { Level, Question, QuestionType } from "../lib/types";

function q(
  topicId: string,
  n: number,
  level: Level,
  type: QuestionType,
  prompt: string,
  answer: string,
  options: string[],
  hint: string,
  explanation: string,
  subRule: string,
): Question {
  return {
    id: `${topicId}-${String(n).padStart(2, "0")}`,
    topicId,
    level,
    type,
    prompt,
    answer,
    options,
    hint,
    explanation,
    subRule,
  };
}

export const PHASE2_QUESTIONS: Question[] = [
  q("present-simple", 1, "A1", "gap", "He ___ in Porto.", "lives", ["live", "lives", "living"], "He is one person.", "He/she/it adds -s: he lives.", "third-person-s"),
  q("present-simple", 2, "A1", "gap", "They ___ English at work.", "speak", ["speak", "speaks", "speaking"], "They is plural.", "I/you/we/they use the base: they speak.", "base-form"),
  q("present-simple", 3, "A1", "fix", "She don't like tea.", "She doesn't like tea.", ["She don't like tea.", "She doesn't like tea.", "She doesn't likes tea."], "She needs doesn't.", "He/she/it: doesn't + base. Not don't, and not doesn't likes.", "doesnt-base"),
  q("present-simple", 4, "A1", "mcq", "Which question is correct?", "Does he play football?", ["Does he plays football?", "Does he play football?", "Do he play football?"], "After does, keep the base verb.", "Does + he + base: Does he play…?", "does-plus-base"),
  q("present-simple", 5, "A1", "gap", "I ___ (not / eat) meat.", "don't eat", ["don't eat", "doesn't eat", "not eat"], "The subject is I.", "I/you/we/they: don't + base.", "dont-base"),
  q("present-simple", 6, "A1", "gap", "___ you ___ (work) here?", "Do / work", ["Do / work", "Does / work", "Do / works"], "You takes do.", "Do you work…? Not does you, not do you works.", "do-plus-base"),
  q("present-simple", 7, "A1", "fix", "My brother go to school by bus.", "My brother goes to school by bus.", ["My brother go to school by bus.", "My brother goes to school by bus.", "My brother going to school by bus."], "Brother is he.", "He/she/it: goes, not go.", "third-person-s"),
  q("present-simple", 8, "A1", "mcq", "Choose the correct negative.", "It doesn't rain much here.", ["It don't rain much here.", "It doesn't rain much here.", "It doesn't rains much here."], "It is like he/she.", "It doesn't rain. Doesn't + base, not don't and not doesn't rains.", "doesnt-base"),

  q("present-continuous", 1, "A1", "gap", "I ___ (wait) for a taxi.", "am waiting", ["am waiting", "wait", "am wait"], "Need am + -ing.", "I am waiting. Do not drop am.", "be-plus-ing"),
  q("present-continuous", 2, "A1", "gap", "She ___ (not / sleep).", "isn't sleeping", ["isn't sleeping", "doesn't sleeping", "isn't sleep"], "Not + continuous.", "Isn't + -ing: isn't sleeping. Not doesn't sleeping.", "negative-ing"),
  q("present-continuous", 3, "A1", "fix", "They watching a film.", "They are watching a film.", ["They watching a film.", "They are watching a film.", "They watches a film."], "You still need are.", "They are watching. The -ing form needs am/is/are.", "be-plus-ing"),
  q("present-continuous", 4, "A1", "mcq", "Which question is correct?", "Are you coming with us?", ["Do you coming with us?", "Are you coming with us?", "Are you come with us?"], "Questions invert am/is/are.", "Are you coming…? Not do you coming.", "be-question"),
  q("present-continuous", 5, "A1", "gap", "We ___ (have) lunch at the moment.", "are having", ["have", "are having", "having"], "At the moment + be + -ing.", "Are having — keep are.", "be-plus-ing"),
  q("present-continuous", 6, "A1", "gap", "___ he ___ (work) today?", "Is / working", ["Is / working", "Does / working", "Is / work"], "He takes is.", "Is he working…?", "be-question"),
  q("present-continuous", 7, "A1", "fix", "The baby is cry.", "The baby is crying.", ["The baby is cry.", "The baby is crying.", "The baby crying."], "Add -ing to the verb.", "Is crying, not is cry.", "be-plus-ing"),
  q("present-continuous", 8, "A1", "mcq", "Choose the correct sentence.", "I'm not using the printer.", ["I not using the printer.", "I'm not using the printer.", "I don't using the printer."], "I + am not + -ing.", "I'm not using. Don't using is wrong.", "negative-ing"),

  q("past-continuous", 1, "A2", "gap", "At 8 p.m. I ___ (drive) home.", "was driving", ["drove", "was driving", "driven"], "A past moment already in progress.", "Was driving = in progress at that time.", "was-were-ing"),
  q("past-continuous", 2, "A2", "gap", "They ___ (not / listen).", "weren't listening", ["didn't listening", "weren't listening", "weren't listen"], "Past continuous negative.", "Weren't + -ing. Not didn't listening.", "negative-past-ing"),
  q("past-continuous", 3, "A2", "fix", "She were waiting at the gate.", "She was waiting at the gate.", ["She were waiting at the gate.", "She was waiting at the gate.", "She waited at the gate still."], "She takes was.", "I/he/she/it was; you/we/they were.", "was-were-ing"),
  q("past-continuous", 4, "A2", "mcq", "Which sentence shows an action in progress yesterday at noon?", "He was sitting in a meeting.", ["He sat in a meeting at noon and finished.", "He was sitting in a meeting.", "He sits in a meeting."], "Need was/were + -ing.", "Was sitting = already happening then.", "was-were-ing"),
  q("past-continuous", 5, "A2", "gap", "___ you ___ (work) at 6?", "Were / working", ["Were / working", "Did / working", "Was / working"], "You takes were.", "Were you working…?", "were-question"),
  q("past-continuous", 6, "A2", "gap", "The children ___ (play) in the garden all afternoon.", "were playing", ["played", "were playing", "was playing"], "Children is plural.", "Were playing, not was playing.", "was-were-ing"),
  q("past-continuous", 7, "A2", "fix", "I was cook dinner at 7.", "I was cooking dinner at 7.", ["I was cook dinner at 7.", "I was cooking dinner at 7.", "I cooking dinner at 7."], "Need -ing.", "Was cooking, not was cook.", "was-were-ing"),
  q("past-continuous", 8, "A2", "mcq", "Choose the correct negative.", "We weren't sleeping.", ["We didn't sleeping.", "We weren't sleeping.", "We wasn't sleeping."], "We takes weren't.", "Weren't sleeping.", "negative-past-ing"),

  q("past-simple-vs-past-continuous", 1, "A2", "gap", "I ___ (cook) when the phone ___ (ring).", "was cooking / rang", ["cooked / was ringing", "was cooking / rang", "was cooking / was ringing"], "Long action vs short interruption.", "Background: was cooking. Interruption: rang.", "interrupt"),
  q("past-simple-vs-past-continuous", 2, "A2", "mcq", "Which sentence is correct?", "She was walking home when it started to rain.", ["She walked home when it was starting to rain.", "She was walking home when it started to rain.", "She was walking home when it was start to rain."], "Rain starting is the short event.", "Was walking (background) + started (interruption).", "interrupt"),
  q("past-simple-vs-past-continuous", 3, "A2", "fix", "I watched TV when he was coming in.", "I was watching TV when he came in.", ["I watched TV when he was coming in.", "I was watching TV when he came in.", "I was watching TV when he was came in."], "Coming in is the short event.", "Was watching + came in.", "interrupt"),
  q("past-simple-vs-past-continuous", 4, "A2", "gap", "They ___ (talk) when the manager ___ (arrive).", "were talking / arrived", ["talked / was arriving", "were talking / arrived", "were talking / was arrived"], "Talking was already happening.", "Were talking + arrived.", "interrupt"),
  q("past-simple-vs-past-continuous", 5, "A2", "mcq", "While I ___, the toast ___.", "was showering / burned", ["showered / was burning", "was showering / burned", "was showering / was burn"], "While + longer action.", "While I was showering, the toast burned.", "while-background"),
  q("past-simple-vs-past-continuous", 6, "A2", "gap", "We ___ (wait) for a taxi when it ___ (start) to snow.", "were waiting / started", ["waited / was starting", "were waiting / started", "were wait / started"], "Waiting is the background.", "Were waiting + started.", "interrupt"),
  q("past-simple-vs-past-continuous", 7, "A2", "fix", "He was breaking the glass while he dropped it.", "He broke the glass while he was washing up.", ["He was breaking the glass while he dropped it.", "He broke the glass while he was washing up.", "He broken the glass while he was washing up."], "The accident is short; washing is long.", "Broke (short) while was washing (long).", "while-background"),
  q("past-simple-vs-past-continuous", 8, "A2", "mcq", "Choose the pair that fits: When I ___ the kitchen, they ___ coffee.", "entered / were making", ["was entering / made", "entered / were making", "enter / were making"], "Entering is a short arrival.", "Entered + were making.", "interrupt"),

  q("present-perfect", 1, "A2", "gap", "She ___ (already / finish) the report.", "has already finished", ["has already finished", "have already finished", "already finished"], "She takes has + participle.", "Has finished. Already often sits with this form.", "have-has-pp"),
  q("present-perfect", 2, "A2", "gap", "I ___ (never / try) sushi.", "have never tried", ["have never tried", "has never tried", "never tried"], "I takes have.", "Have never tried — life up to now, no date.", "have-has-pp"),
  q("present-perfect", 3, "A2", "fix", "They has left the office.", "They have left the office.", ["They has left the office.", "They have left the office.", "They have leave the office."], "They takes have.", "Have + left (participle).", "have-has-pp"),
  q("present-perfect", 4, "A2", "mcq", "Which sentence is correct?", "He hasn't called yet.", ["He hasn't called yet.", "He haven't called yet.", "He hasn't call yet."], "Yet + has/have + participle.", "Hasn't called yet. Call is not the participle.", "have-has-pp"),
  q("present-perfect", 5, "A2", "gap", "___ you ___ (see) this email?", "Have / seen", ["Have / seen", "Has / seen", "Have / saw"], "You takes have + seen.", "Have you seen…? Saw is past simple.", "have-has-pp"),
  q("present-perfect", 6, "A2", "gap", "We ___ (just / arrive).", "have just arrived", ["have just arrived", "has just arrived", "just arrive"], "Just + present perfect.", "Have just arrived.", "have-has-pp"),
  q("present-perfect", 7, "A2", "fix", "My sister have lost her card.", "My sister has lost her card.", ["My sister have lost her card.", "My sister has lost her card.", "My sister has lose her card."], "Sister is she.", "Has lost.", "have-has-pp"),
  q("present-perfect", 8, "A2", "mcq", "Choose the correct participle pair.", "They have written two drafts.", ["They have wrote two drafts.", "They have written two drafts.", "They has written two drafts."], "Write → written.", "Have written, not have wrote.", "have-has-pp"),

  q("will-vs-going-to", 1, "A2", "mcq", "The doorbell rings. You say:", "I'll get it.", ["I'm going to get it later this week.", "I'll get it.", "I getting it."], "A decision right now.", "Will for a decision at the moment of speaking.", "will-now"),
  q("will-vs-going-to", 2, "A2", "gap", "Look at those clouds. It ___ rain.", "is going to", ["will", "is going to", "is"], "You can see the evidence.", "Going to for a future you can see coming.", "going-to-evidence"),
  q("will-vs-going-to", 3, "A2", "fix", "I will visiting my aunt on Sunday. We booked it last month.", "I am going to visit my aunt on Sunday.", ["I will visiting my aunt on Sunday.", "I am going to visit my aunt on Sunday.", "I going visit my aunt on Sunday."], "A plan already made.", "Going to for a plan already decided. Will visiting is the wrong form.", "going-to-plan"),
  q("will-vs-going-to", 4, "A2", "mcq", "I think she ___ the job.", "will get", ["is going to getting", "will get", "will gets"], "A prediction, no evidence in front of you.", "Will get for a prediction.", "will-now"),
  q("will-vs-going-to", 5, "A2", "gap", "We ___ move in July. We signed the contract.", "are going to", ["will", "are going to", "going"], "The plan is already fixed.", "Are going to move — plan already made.", "going-to-plan"),
  q("will-vs-going-to", 6, "A2", "mcq", "Wait, the bag is heavy. I ___ it.", "I'll carry", ["I'm going to carry", "I'll carry", "I carry"], "Offer made now.", "I'll carry it — decision/offer now.", "will-now"),
  q("will-vs-going-to", 7, "A2", "fix", "Be careful! You will drop it — the glass is already sliding.", "You are going to drop it.", ["You will drop it.", "You are going to drop it.", "You dropping it."], "Evidence right now.", "Going to when you can see it about to happen.", "going-to-evidence"),
  q("will-vs-going-to", 8, "A2", "gap", "I'm tired. I think I ___ to bed.", "will go", ["am going to going", "will go", "go"], "Decision as you speak.", "Will go — deciding now.", "will-now"),

  q("going-to", 1, "A1", "gap", "I ___ (start) a new course.", "am going to start", ["am going to start", "going to start", "am going start"], "Need am + going to + base.", "I am going to start.", "be-going-to"),
  q("going-to", 2, "A1", "gap", "She ___ (not / sell) the car.", "isn't going to sell", ["isn't going to sell", "isn't going sell", "doesn't going to sell"], "Negative: isn't going to.", "Isn't going to sell.", "be-going-to"),
  q("going-to", 3, "A1", "fix", "They going to fly tomorrow.", "They are going to fly tomorrow.", ["They going to fly tomorrow.", "They are going to fly tomorrow.", "They are going fly tomorrow."], "Need are.", "Are going to fly.", "be-going-to"),
  q("going-to", 4, "A1", "mcq", "Which question is correct?", "Are you going to apply?", ["Do you going to apply?", "Are you going to apply?", "Are you going apply?"], "Invert are.", "Are you going to apply?", "be-going-to"),
  q("going-to", 5, "A1", "gap", "We ___ (meet) at 6.", "are going to meet", ["are going to meet", "going to meet", "are going meet"], "We + are.", "Are going to meet.", "be-going-to"),
  q("going-to", 6, "A1", "gap", "___ he ___ (join) us?", "Is / going to join", ["Is / going to join", "Does / going to join", "Is / going join"], "He takes is.", "Is he going to join…?", "be-going-to"),
  q("going-to", 7, "A1", "fix", "I'm going to to call later.", "I'm going to call later.", ["I'm going to to call later.", "I'm going to call later.", "I going to call later."], "Only one to.", "Going to + base: going to call.", "be-going-to"),
  q("going-to", 8, "A1", "mcq", "Choose the correct sentence.", "It is going to be busy.", ["It going to be busy.", "It is going to be busy.", "It is going be busy."], "It + is + going to + be.", "Is going to be.", "be-going-to"),

  q("zero-article", 1, "A2", "mcq", "Which sentence means coffee in general?", "I don't drink coffee.", ["I don't drink the coffee.", "I don't drink coffee.", "I don't drink coffees."], "No article for the drink as a type.", "Uncountable + general: coffee, not the coffee.", "general-no-article"),
  q("zero-article", 2, "A2", "gap", "___ need sleep.", "Dogs", ["The dogs", "Dogs", "A dogs"], "Plural + general = no article.", "Dogs need sleep. The dogs would be specific dogs.", "general-no-article"),
  q("zero-article", 3, "A2", "fix", "She loves the music.", "She loves music.", ["She loves the music.", "She loves music.", "She loves a music."], "Music in general takes no article.", "I like music / she loves music.", "general-no-article"),
  q("zero-article", 4, "A2", "mcq", "Which is correct for school as an institution?", "They go to school at 8.", ["They go to school at 8.", "They go school at 8.", "They go to a school at 8."], "Go to school = the activity.", "No article: go to school.", "institution"),
  q("zero-article", 5, "A2", "gap", "I need ___ information, not a brochure.", "information", ["an information", "information", "the informations"], "Information is uncountable and general here.", "Information, not an information.", "general-no-article"),
  q("zero-article", 6, "A2", "fix", "The life is short.", "Life is short.", ["The life is short.", "Life is short.", "A life is short."], "Abstract nouns in general.", "Life is short — no the.", "general-no-article"),
  q("zero-article", 7, "A2", "mcq", "Choose the sentence about specific files you both can see.", "Please send the files.", ["Please send files.", "Please send the files.", "Please send a files."], "You both know which files.", "The files = specific. Bare files would be general.", "the-for-specific"),
  q("zero-article", 8, "A2", "gap", "He works in ___ finance.", "finance", ["the finance", "finance", "a finance"], "Fields of work often take no article.", "In finance, in education — no article.", "general-no-article"),

  q("some-any", 1, "A1", "gap", "I bought ___ apples.", "some", ["some", "any", "an"], "Positive sentence.", "Some in positives: I bought some apples.", "some-positive"),
  q("some-any", 2, "A1", "gap", "We haven't got ___ milk.", "any", ["some", "any", "a"], "Negative sentence.", "Any in negatives: haven't got any milk.", "any-negative-question"),
  q("some-any", 3, "A1", "mcq", "Which question is typical?", "Do you have any questions?", ["Do you have some questions?", "Do you have any questions?", "Do you have a questions?"], "Questions usually take any.", "Any in most questions.", "any-negative-question"),
  q("some-any", 4, "A1", "fix", "There isn't some bread left.", "There isn't any bread left.", ["There isn't some bread left.", "There isn't any bread left.", "There isn't a bread left."], "Negative + uncountable.", "Isn't any, not isn't some.", "any-negative-question"),
  q("some-any", 5, "A1", "gap", "Would you like ___ tea?", "some", ["some", "any", "the"], "Offers often use some.", "Offers/requests can use some: Would you like some tea?", "some-offer"),
  q("some-any", 6, "A1", "gap", "I don't know ___ of these people.", "any", ["some", "any", "a"], "Negative idea.", "Don't know any of them.", "any-negative-question"),
  q("some-any", 7, "A1", "mcq", "Choose the correct sentence.", "She has some news.", ["She has any news.", "She has some news.", "She has a news."], "Positive + uncountable.", "Some news (uncountable). Not a news.", "some-positive"),
  q("some-any", 8, "A1", "fix", "Have you got some stamps? I need one.", "Have you got any stamps?", ["Have you got some stamps?", "Have you got any stamps?", "Have you got a stamps?"], "A normal question prefers any.", "Have you got any…? Some is more like expecting yes.", "any-negative-question"),

  q("much-many-a-lot-of", 1, "A1", "gap", "How ___ emails did you get?", "many", ["much", "many", "a lot"], "Emails are countable.", "How many + plural count noun.", "many-count"),
  q("much-many-a-lot-of", 2, "A1", "gap", "How ___ time do we have?", "much", ["much", "many", "a lot"], "Time is uncountable here.", "How much + uncountable.", "much-uncount"),
  q("much-many-a-lot-of", 3, "A1", "mcq", "Which is natural in a positive sentence?", "We have a lot of work.", ["We have much work.", "We have a lot of work.", "We have many work."], "Much is awkward in positives.", "A lot of work. Many work is wrong.", "a-lot-of"),
  q("much-many-a-lot-of", 4, "A1", "fix", "There aren't much chairs.", "There aren't many chairs.", ["There aren't much chairs.", "There aren't many chairs.", "There aren't a lot chair."], "Chairs are countable.", "Many chairs, not much chairs.", "many-count"),
  q("much-many-a-lot-of", 5, "A1", "gap", "I don't have ___ money.", "much", ["much", "many", "a"], "Money is uncountable.", "Don't have much money.", "much-uncount"),
  q("much-many-a-lot-of", 6, "A1", "gap", "She reads ___ books.", "a lot of", ["much", "a lot of", "many of book"], "Positive + countable.", "A lot of books (or many books).", "a-lot-of"),
  q("much-many-a-lot-of", 7, "A1", "mcq", "Choose the correct question.", "Is there much traffic?", ["Are there many traffic?", "Is there much traffic?", "Is there many traffic?"], "Traffic is uncountable.", "Much traffic.", "much-uncount"),
  q("much-many-a-lot-of", 8, "A1", "fix", "He has many informations.", "He has a lot of information.", ["He has many informations.", "He has a lot of information.", "He has much informations."], "Information has no plural here.", "A lot of information.", "a-lot-of"),

  q("this-that-these-those", 1, "A1", "gap", "___ pen in my hand is new.", "This", ["This", "That", "These"], "Near you, one thing.", "This = near + singular.", "near-singular"),
  q("this-that-these-those", 2, "A1", "gap", "___ houses across the street are old.", "Those", ["These", "Those", "That"], "Far + plural.", "Those = far + plural.", "far-plural"),
  q("this-that-these-those", 3, "A1", "fix", "This shoes are wet.", "These shoes are wet.", ["This shoes are wet.", "These shoes are wet.", "That shoes are wet."], "Shoes is plural.", "These shoes, not this shoes.", "near-plural"),
  q("this-that-these-those", 4, "A1", "mcq", "Which sentence points to a building far from you?", "That building is the office.", ["This building is the office.", "That building is the office.", "These building is the office."], "Far + one.", "That building.", "far-singular"),
  q("this-that-these-those", 5, "A1", "gap", "Can you pass me ___ papers next to you?", "those", ["these", "those", "this"], "Next to the other person = farther from you.", "Those papers (not in your hands).", "far-plural"),
  q("this-that-these-those", 6, "A1", "gap", "___ is my colleague, Ana.", "This", ["This", "These", "Those"], "One person, near.", "This is Ana.", "near-singular"),
  q("this-that-these-those", 7, "A1", "mcq", "Choose the correct pair.", "These apples are sweet.", ["This apples are sweet.", "These apples are sweet.", "Those apple are sweet."], "Plural + near.", "These apples.", "near-plural"),
  q("this-that-these-those", 8, "A1", "fix", "I like that photos.", "I like those photos.", ["I like that photos.", "I like those photos.", "I like this photos."], "Photos is plural.", "Those photos, not that photos.", "far-plural"),

  q("possessive-adjectives-pronouns", 1, "A1", "gap", "This is ___ desk. (I)", "my", ["my", "mine", "me"], "Before a noun.", "My desk. Mine cannot sit before a noun.", "adj-before-noun"),
  q("possessive-adjectives-pronouns", 2, "A1", "gap", "This desk is ___. (I)", "mine", ["my", "mine", "me"], "No noun after it.", "The desk is mine.", "pronoun-alone"),
  q("possessive-adjectives-pronouns", 3, "A1", "fix", "The keys are her.", "The keys are hers.", ["The keys are her.", "The keys are hers.", "The keys are she's."], "Stand-alone form.", "Hers, not her, when no noun follows.", "pronoun-alone"),
  q("possessive-adjectives-pronouns", 4, "A1", "mcq", "Which is correct?", "Is this yours?", ["Is this your?", "Is this yours?", "Is this you're?"], "Yours stands alone.", "Yours, not your, without a noun.", "pronoun-alone"),
  q("possessive-adjectives-pronouns", 5, "A1", "gap", "They forgot ___ badges.", "their", ["their", "theirs", "them"], "Before badges.", "Their badges.", "adj-before-noun"),
  q("possessive-adjectives-pronouns", 6, "A1", "gap", "Ours is the blue one. So the blue one is ___.", "ours", ["our", "ours", "us"], "Repeating the stand-alone form.", "Ours stands alone.", "pronoun-alone"),
  q("possessive-adjectives-pronouns", 7, "A1", "fix", "That's mine bag.", "That's my bag.", ["That's mine bag.", "That's my bag.", "That's me bag."], "Bag is a noun after it.", "My bag, not mine bag.", "adj-before-noun"),
  q("possessive-adjectives-pronouns", 8, "A1", "mcq", "Choose the correct sentence.", "Your idea is better than mine.", ["Your idea is better than my.", "Your idea is better than mine.", "Yours idea is better than mine."], "Mine = my idea.", "Than mine, not than my.", "pronoun-alone"),

  q("possessive-s", 1, "A1", "gap", "This is ___ laptop. (Ana)", "Ana's", ["Ana", "Ana's", "Anas"], "One person + 's.", "Ana's laptop.", "apostrophe-s"),
  q("possessive-s", 2, "A1", "mcq", "Choose the phrase for the room of the students.", "the students' room", ["the student's room", "the students' room", "the students room"], "Plural ending in s: apostrophe after s.", "students' = of the students.", "plural-apostrophe"),
  q("possessive-s", 3, "A1", "fix", "My parents car is old.", "My parents' car is old.", ["My parents car is old.", "My parents' car is old.", "My parent's car is old."], "Parents is plural with s.", "Parents' car.", "plural-apostrophe"),
  q("possessive-s", 4, "A1", "gap", "The ___ name is Max. (dog)", "dog's", ["dog", "dog's", "dogs"], "One animal.", "The dog's name.", "apostrophe-s"),
  q("possessive-s", 5, "A1", "mcq", "Which is correct?", "James's office is upstairs.", ["James office is upstairs.", "James's office is upstairs.", "Jame's office is upstairs."], "Names ending in s still often take 's.", "James's office.", "apostrophe-s"),
  q("possessive-s", 6, "A1", "fix", "The childrens toys are everywhere.", "The children's toys are everywhere.", ["The childrens toys are everywhere.", "The children's toys are everywhere.", "The childrens' toys are everywhere."], "Children is irregular plural.", "Children's — add 's, not only '.", "irregular-plural"),
  q("possessive-s", 7, "A1", "gap", "I borrowed ___ charger. (my brother)", "my brother's", ["my brother", "my brother's", "my brothers"], "One brother.", "My brother's charger.", "apostrophe-s"),
  q("possessive-s", 8, "A1", "mcq", "Choose the phrase for the results of one team.", "the team's results", ["the teams results", "the team's results", "the teams' results"], "One team.", "Team's = of the team.", "apostrophe-s"),

  q("question-formation", 1, "A1", "mcq", "Which question is correct?", "Do they live nearby?", ["Do they lives nearby?", "Do they live nearby?", "Does they live nearby?"], "They + do + base.", "Do they live…? Not lives.", "do-base"),
  q("question-formation", 2, "A1", "gap", "___ she ___ (drive) to work?", "Does / drive", ["Does / drive", "Does / drives", "Do / drive"], "She takes does + base.", "Does she drive…?", "does-base"),
  q("question-formation", 3, "A1", "fix", "Did you saw the email?", "Did you see the email?", ["Did you saw the email?", "Did you see the email?", "Did you seen the email?"], "Did + base.", "Did you see, not saw.", "did-base"),
  q("question-formation", 4, "A1", "mcq", "Choose the correct question.", "Does it work?", ["Does it works?", "Does it work?", "Do it work?"], "It + does + base.", "Does it work?", "does-base"),
  q("question-formation", 5, "A1", "gap", "___ you ___ (finish) the form yesterday?", "Did / finish", ["Did / finish", "Did / finished", "Do / finish"], "Yesterday → did + base.", "Did you finish…?", "did-base"),
  q("question-formation", 6, "A1", "fix", "Do he know the code?", "Does he know the code?", ["Do he know the code?", "Does he know the code?", "Does he knows the code?"], "He takes does.", "Does he know, not do he, not knows.", "does-base"),
  q("question-formation", 7, "A1", "gap", "Where ___ they ___ (keep) the files?", "do / keep", ["do / keep", "does / keep", "do / keeps"], "They + do.", "Where do they keep…?", "do-base"),
  q("question-formation", 8, "A1", "mcq", "Which is correct?", "Did she call you?", ["Did she called you?", "Did she call you?", "Does she called you?"], "Did + base.", "Did she call…?", "did-base"),

  q("countable-uncountable", 1, "A1", "mcq", "Which noun is countable here?", "ticket", ["advice", "ticket", "furniture"], "You can say two tickets.", "Ticket is countable. Advice and furniture are not.", "can-count"),
  q("countable-uncountable", 2, "A1", "gap", "I need ___ chair.", "a", ["a", "some", "two"], "One countable thing.", "A chair. Uncountable nouns do not take a.", "a-with-count"),
  q("countable-uncountable", 3, "A1", "fix", "She gave me an advice.", "She gave me some advice.", ["She gave me an advice.", "She gave me some advice.", "She gave me two advices."], "Advice is uncountable.", "Some advice, not an advice.", "no-a-uncount"),
  q("countable-uncountable", 4, "A1", "mcq", "Which sentence is correct?", "How many bags do you have?", ["How much bags do you have?", "How many bags do you have?", "How many bag do you have?"], "Bags are countable.", "How many + plural countable.", "can-count"),
  q("countable-uncountable", 5, "A1", "gap", "There is ___ water in the bottle.", "some", ["a", "some", "two"], "Water is uncountable.", "Some water, not a water.", "no-a-uncount"),
  q("countable-uncountable", 6, "A1", "fix", "I bought two breads.", "I bought two loaves of bread.", ["I bought two breads.", "I bought two loaves of bread.", "I bought a breads."], "Bread is uncountable.", "Loaves of bread, not two breads.", "no-a-uncount"),
  q("countable-uncountable", 7, "A1", "mcq", "Choose the uncountable noun.", "information", ["email", "information", "meeting"], "You cannot say two informations.", "Information is uncountable.", "no-a-uncount"),
  q("countable-uncountable", 8, "A1", "gap", "We had three ___ yesterday.", "meetings", ["meeting", "meetings", "meeting's"], "You can count meetings.", "Three meetings — countable plural.", "can-count"),

  q("can-could", 1, "A1", "gap", "I ___ swim, but not very far.", "can", ["can", "can to", "cans"], "Ability now.", "Can + base: can swim.", "can-ability"),
  q("can-could", 2, "A1", "gap", "___ you help me with this box?", "Could", ["Could", "Could to", "Can to"], "Polite request.", "Could you help…? Base verb after could.", "could-polite"),
  q("can-could", 3, "A1", "fix", "She can plays the piano.", "She can play the piano.", ["She can plays the piano.", "She can play the piano.", "She can playing the piano."], "Base after can.", "Can play, not plays.", "base-after-modal"),
  q("can-could", 4, "A1", "mcq", "Choose the sentence about running ten years ago.", "I could run faster ten years ago.", ["I can run faster ten years ago.", "I could run faster ten years ago.", "I could ran faster ten years ago."], "Could = past of can.", "Could run — past ability.", "could-past"),
  q("can-could", 5, "A1", "gap", "There's a green sign. You ___ park here.", "can", ["can", "can to", "could to"], "Permission now.", "You can park here.", "can-ability"),
  q("can-could", 6, "A1", "fix", "Could you opening the door?", "Could you open the door?", ["Could you opening the door?", "Could you open the door?", "Could you to open the door?"], "Base after could.", "Could you open…?", "base-after-modal"),
  q("can-could", 7, "A1", "mcq", "Which is correct?", "He can't come today.", ["He can't to come today.", "He can't come today.", "He doesn't can come today."], "Can't + base.", "Can't come, not doesn't can.", "can-ability"),
  q("can-could", 8, "A1", "gap", "When I was a child I ___ (not / stay) up late.", "couldn't stay", ["couldn't stay", "can't stay", "couldn't stayed"], "Past negative ability.", "Couldn't stay.", "could-past"),

  q("must-have-to", 1, "A2", "mcq", "A company rule: staff ___ wear a badge.", "have to", ["must to", "have to", "should to"], "External rule.", "Have to for a rule from outside.", "have-to-rule"),
  q("must-have-to", 2, "A2", "gap", "This cake is excellent. You ___ try it.", "must", ["must", "have to", "must to"], "Speaker's strong feeling.", "Must from the speaker.", "must-speaker"),
  q("must-have-to", 3, "A2", "fix", "I must to leave at 5.", "I must leave at 5.", ["I must to leave at 5.", "I must leave at 5.", "I must leaving at 5."], "No to after must.", "Must leave — never must to.", "no-to-after-must"),
  q("must-have-to", 4, "A2", "mcq", "It's optional. You ___ come.", "don't have to", ["mustn't", "don't have to", "must not to"], "No obligation.", "Don't have to = not necessary. Mustn't = forbidden.", "dont-have-to"),
  q("must-have-to", 5, "A2", "gap", "It's a no-smoking room. You ___ smoke in here.", "mustn't", ["don't have to", "mustn't", "must not to"], "Not allowed.", "Mustn't = prohibition.", "mustnt-forbidden"),
  q("must-have-to", 6, "A2", "fix", "She have to starts at 9.", "She has to start at 9.", ["She have to starts at 9.", "She has to start at 9.", "She has to starting at 9."], "She + has to + base.", "Has to start.", "have-to-rule"),
  q("must-have-to", 7, "A2", "mcq", "Which means 'it is not necessary'?", "You don't have to pay today.", ["You mustn't pay today.", "You don't have to pay today.", "You must to pay today."], "Don't have to ≠ mustn't.", "Don't have to = optional.", "dont-have-to"),
  q("must-have-to", 8, "A2", "gap", "The form says applicants ___ upload a CV.", "have to", ["must to", "have to", "should to"], "Requirement from the process.", "Have to upload.", "have-to-rule"),

  q("should", 1, "A2", "gap", "You ___ rest if you feel ill.", "should", ["should", "should to", "must to"], "Advice, not a law.", "Should + base: should rest.", "should-advice"),
  q("should", 2, "A2", "fix", "He should to apologise.", "He should apologise.", ["He should to apologise.", "He should apologise.", "He should apologising."], "No to after should.", "Should apologise.", "should-base"),
  q("should", 3, "A2", "mcq", "Which is the weakest obligation?", "You should check the date.", ["You must check the date.", "You have to check the date.", "You should check the date."], "Should is advice.", "Should is weaker than must/have to.", "should-advice"),
  q("should", 4, "A2", "gap", "We ___ (not / be) late.", "shouldn't be", ["shouldn't be", "shouldn't to be", "don't should be"], "Negative advice.", "Shouldn't be.", "should-advice"),
  q("should", 5, "A2", "mcq", "Choose the correct question.", "Should I take a coat?", ["Should I to take a coat?", "Should I take a coat?", "Do I should take a coat?"], "Should + subject + base.", "Should I take…?", "should-base"),
  q("should", 6, "A2", "fix", "You should seeing a dentist.", "You should see a dentist.", ["You should seeing a dentist.", "You should see a dentist.", "You should to see a dentist."], "Base form.", "Should see.", "should-base"),
  q("should", 7, "A2", "gap", "People ___ drink more water.", "should", ["should", "shoulds", "are should"], "General advice.", "Should drink.", "should-advice"),
  q("should", 8, "A2", "mcq", "Which sentence is correct?", "She should call them.", ["She should calls them.", "She should call them.", "She should calling them."], "No -s after should.", "Should call.", "should-base"),

  q("used-to", 1, "A2", "gap", "I ___ smoke, but I stopped.", "used to", ["used to", "use to", "used"], "Past habit, not true now.", "Used to + base: used to smoke.", "used-to-habit"),
  q("used-to", 2, "A2", "mcq", "Which question is correct?", "Did you use to live here?", ["Did you used to live here?", "Did you use to live here?", "Did you use to lived here?"], "Did + use to (not used).", "Did you use to…?", "did-use-to"),
  q("used-to", 3, "A2", "fix", "She didn't used to like coffee.", "She didn't use to like coffee.", ["She didn't used to like coffee.", "She didn't use to like coffee.", "She didn't use to liked coffee."], "After didn't: use, not used.", "Didn't use to like.", "did-use-to"),
  q("used-to", 4, "A2", "gap", "We ___ have a garden.", "used to", ["used to", "were used to", "use to"], "Past state, not true now.", "Used to have.", "used-to-habit"),
  q("used-to", 5, "A2", "mcq", "Choose the correct sentence.", "He used to work nights.", ["He used to working nights.", "He used to work nights.", "He used work nights."], "Used to + base.", "Used to work.", "used-to-habit"),
  q("used-to", 6, "A2", "gap", "___ she ___ (play) tennis every weekend?", "Did / use to play", ["Did / used to play", "Did / use to play", "Does / use to play"], "Question with did.", "Did she use to play…?", "did-use-to"),
  q("used-to", 7, "A2", "fix", "I use to go by bus, but not anymore.", "I used to go by bus, but not anymore.", ["I use to go by bus, but not anymore.", "I used to go by bus, but not anymore.", "I used go by bus, but not anymore."], "Positive: used to.", "Used to go.", "used-to-habit"),
  q("used-to", 8, "A2", "mcq", "Which meaning fits used to?", "a past habit that has stopped", ["a plan for next week", "a past habit that has stopped", "something happening right now"], "Not true now.", "Used to = past, finished habit/state.", "used-to-habit"),

  q("for-since", 1, "A2", "gap", "I have known her ___ 2019.", "since", ["for", "since", "from"], "2019 is a starting point.", "Since + a point in time.", "since-point"),
  q("for-since", 2, "A2", "gap", "They have been here ___ three hours.", "for", ["for", "since", "during"], "Three hours is a length.", "For + a period.", "for-period"),
  q("for-since", 3, "A2", "fix", "She has lived here for January.", "She has lived here since January.", ["She has lived here for January.", "She has lived here since January.", "She has lived here since three months."], "January is a start point.", "Since January. For three months.", "since-point"),
  q("for-since", 4, "A2", "mcq", "Which is correct?", "He has been ill for a week.", ["He has been ill since a week.", "He has been ill for a week.", "He has been ill for last Monday."], "A week is a duration.", "For a week. Since Monday.", "for-period"),
  q("for-since", 5, "A2", "gap", "We've waited ___ noon.", "since", ["for", "since", "at"], "Noon is a point.", "Since noon.", "since-point"),
  q("for-since", 6, "A2", "gap", "I've had this phone ___ two years.", "for", ["for", "since", "from"], "Two years is a length.", "For two years.", "for-period"),
  q("for-since", 7, "A2", "mcq", "Choose the correct pair.", "since Monday / for three days", ["for Monday / since three days", "since Monday / for three days", "since three days / for Monday"], "Point vs period.", "Since + point; for + period.", "since-point"),
  q("for-since", 8, "A2", "fix", "I have worked here since five years.", "I have worked here for five years.", ["I have worked here since five years.", "I have worked here for five years.", "I have worked here since five years ago."], "Five years is a length.", "For five years.", "for-period"),

  q("its-vs-its", 1, "A2", "gap", "___ raining.", "It's", ["Its", "It's", "Its'"], "It is raining.", "It's = it is.", "its-contraction"),
  q("its-vs-its", 2, "A2", "gap", "The cat licked ___ paws.", "its", ["it's", "its", "its'"], "Belonging, no apostrophe.", "Its paws = of the cat.", "its-possessive"),
  q("its-vs-its", 3, "A2", "fix", "The company changed it's logo.", "The company changed its logo.", ["The company changed it's logo.", "The company changed its logo.", "The company changed its' logo."], "Logo belongs to the company.", "Its logo, not it's.", "its-possessive"),
  q("its-vs-its", 4, "A2", "mcq", "Which is correct?", "It's been a long day.", ["Its been a long day.", "It's been a long day.", "Its' been a long day."], "It has been.", "It's = it has here.", "its-contraction"),
  q("its-vs-its", 5, "A2", "gap", "Every tool has ___ place.", "its", ["it's", "its", "it"], "Belonging.", "Its place.", "its-possessive"),
  q("its-vs-its", 6, "A2", "mcq", "Choose the contraction of it is.", "It's cold.", ["Its cold.", "It's cold.", "Its' cold."], "It is cold.", "It's cold.", "its-contraction"),
  q("its-vs-its", 7, "A2", "fix", "Its time to go.", "It's time to go.", ["Its time to go.", "It's time to go.", "Its' time to go."], "It is time.", "It's time.", "its-contraction"),
  q("its-vs-its", 8, "A2", "gap", "The printer has lost ___ wireless signal.", "its", ["it's", "its", "its'"], "The signal belongs to the printer.", "Its signal.", "its-possessive"),

  q("affect-vs-effect", 1, "B1", "gap", "The delay will ___ our plans.", "affect", ["affect", "effect", "effects"], "Need a verb.", "Affect = verb.", "affect-verb"),
  q("affect-vs-effect", 2, "B1", "gap", "What was the ___ of the change?", "effect", ["affect", "effect", "affects"], "Need a noun after the.", "The effect = noun.", "effect-noun"),
  q("affect-vs-effect", 3, "B1", "fix", "The weather effected the match.", "The weather affected the match.", ["The weather effected the match.", "The weather affected the match.", "The weather had an affect on the match."], "Verb needed.", "Affected the match.", "affect-verb"),
  q("affect-vs-effect", 4, "B1", "mcq", "Which sentence is correct?", "The new hours had a good effect.", ["The new hours had a good affect.", "The new hours had a good effect.", "The new hours effected a good affect."], "A/an/the + effect.", "A good effect.", "effect-noun"),
  q("affect-vs-effect", 5, "B1", "gap", "Stress can ___ your sleep.", "affect", ["affect", "effect", "an effect"], "Verb after can.", "Can affect.", "affect-verb"),
  q("affect-vs-effect", 6, "B1", "mcq", "Choose the noun.", "side effect", ["side affect", "side effect", "side affected"], "Effect as noun.", "Side effect.", "effect-noun"),
  q("affect-vs-effect", 7, "B1", "fix", "How did the news effect you?", "How did the news affect you?", ["How did the news effect you?", "How did the news affect you?", "How did the news have affect you?"], "Did + verb.", "Affect you.", "affect-verb"),
  q("affect-vs-effect", 8, "B1", "gap", "The ___ on sales was small.", "effect", ["affect", "effect", "affected"], "The + noun.", "The effect on sales.", "effect-noun"),

  q("fewer-vs-less", 1, "B1", "gap", "We need ___ meetings.", "fewer", ["fewer", "less", "least"], "Meetings are countable.", "Fewer meetings.", "fewer-count"),
  q("fewer-vs-less", 2, "B1", "gap", "Please use ___ sugar.", "less", ["fewer", "less", "fewer of"], "Sugar is uncountable.", "Less sugar.", "less-uncount"),
  q("fewer-vs-less", 3, "B1", "fix", "There are less people in the office today.", "There are fewer people in the office today.", ["There are less people in the office today.", "There are fewer people in the office today.", "There is fewer people in the office today."], "People is countable plural.", "Fewer people.", "fewer-count"),
  q("fewer-vs-less", 4, "B1", "mcq", "Which is correct?", "I have less time this week.", ["I have fewer time this week.", "I have less time this week.", "I have fewer times this week."], "Time as duration is uncountable.", "Less time.", "less-uncount"),
  q("fewer-vs-less", 5, "B1", "gap", "___ cars on the road would help.", "Fewer", ["Fewer", "Less", "Least"], "Cars are countable.", "Fewer cars.", "fewer-count"),
  q("fewer-vs-less", 6, "B1", "mcq", "Choose the uncountable pair.", "less traffic", ["fewer traffic", "less traffic", "fewer traffics"], "Traffic is uncountable.", "Less traffic.", "less-uncount"),
  q("fewer-vs-less", 7, "B1", "fix", "Buy less apples.", "Buy fewer apples.", ["Buy less apples.", "Buy fewer apples.", "Buy fewer apple."], "Apples are countable.", "Fewer apples.", "fewer-count"),
  q("fewer-vs-less", 8, "B1", "gap", "There's ___ noise after 8.", "less", ["fewer", "less", "fewer of"], "Noise is uncountable.", "Less noise.", "less-uncount"),

  q("make-vs-do", 1, "A2", "gap", "I need to ___ a phone call.", "make", ["make", "do", "make do"], "Creating the call.", "Make a call / make a decision.", "make-create"),
  q("make-vs-do", 2, "A2", "gap", "Have you ___ the dishes?", "done", ["made", "done", "do"], "A household task.", "Do the dishes.", "do-task"),
  q("make-vs-do", 3, "A2", "fix", "She did a mistake.", "She made a mistake.", ["She did a mistake.", "She made a mistake.", "She made mistake."], "Mistake collocation.", "Make a mistake.", "make-create"),
  q("make-vs-do", 4, "A2", "mcq", "Which is correct?", "He does his homework after dinner.", ["He makes his homework after dinner.", "He does his homework after dinner.", "He does a homework after dinner."], "Homework is a task.", "Do homework.", "do-task"),
  q("make-vs-do", 5, "A2", "gap", "Can you ___ a reservation?", "make", ["make", "do", "doing"], "Creating a booking.", "Make a reservation.", "make-create"),
  q("make-vs-do", 6, "A2", "mcq", "Choose the task verb.", "do the shopping", ["make the shopping", "do the shopping", "make shopping"], "Shopping as a chore.", "Do the shopping.", "do-task"),
  q("make-vs-do", 7, "A2", "fix", "We need to do a plan.", "We need to make a plan.", ["We need to do a plan.", "We need to make a plan.", "We need to make plan."], "Plan is produced.", "Make a plan.", "make-create"),
  q("make-vs-do", 8, "A2", "gap", "I'll ___ my best.", "do", ["make", "do", "did"], "Fixed phrase.", "Do my best.", "do-task"),

  q("say-vs-tell", 1, "A2", "gap", "She ___ me the news.", "told", ["said", "told", "say"], "Tell + person.", "Told me.", "tell-person"),
  q("say-vs-tell", 2, "A2", "gap", "He ___ he was tired.", "said", ["told", "said", "told to"], "No person object needed.", "Said (that) he was tired.", "say-words"),
  q("say-vs-tell", 3, "A2", "fix", "Please say me the truth.", "Please tell me the truth.", ["Please say me the truth.", "Please tell me the truth.", "Please tell the truth me."], "Person after tell.", "Tell me, not say me.", "tell-person"),
  q("say-vs-tell", 4, "A2", "mcq", "Which is correct?", "What did she say?", ["What did she tell?", "What did she say?", "What did she said?"], "Say without a person.", "What did she say?", "say-words"),
  q("say-vs-tell", 5, "A2", "gap", "Don't ___ anyone yet.", "tell", ["say", "tell", "say to"], "Tell + person.", "Don't tell anyone.", "tell-person"),
  q("say-vs-tell", 6, "A2", "mcq", "Choose the correct sentence.", "She said to me that it was late.", ["She said me that it was late.", "She said to me that it was late.", "She told to me that it was late."], "Say to someone.", "Said to me. Told me (no to).", "say-words"),
  q("say-vs-tell", 7, "A2", "fix", "He told that he was leaving.", "He said that he was leaving.", ["He told that he was leaving.", "He said that he was leaving.", "He told that leaving."], "Told needs a person if you keep told.", "Said that… (or told me that…).", "say-words"),
  q("say-vs-tell", 8, "A2", "gap", "Can you ___ her I'll be late?", "tell", ["say", "tell", "saying"], "Tell + her.", "Tell her.", "tell-person"),

  q("good-vs-well", 1, "A2", "gap", "She is a ___ driver.", "good", ["good", "well", "best"], "Driver is a noun.", "Good + noun.", "good-noun"),
  q("good-vs-well", 2, "A2", "gap", "She drives ___.", "well", ["good", "well", "goodly"], "Drives is a verb.", "Well describes the action.", "well-verb"),
  q("good-vs-well", 3, "A2", "fix", "You speak English very good.", "You speak English very well.", ["You speak English very good.", "You speak English very well.", "You speak English very weller."], "Speak is a verb.", "Speak well.", "well-verb"),
  q("good-vs-well", 4, "A2", "mcq", "Which is correct?", "That was a good meeting.", ["That was a well meeting.", "That was a good meeting.", "That was a goodly meeting."], "Meeting is a noun.", "A good meeting.", "good-noun"),
  q("good-vs-well", 5, "A2", "gap", "I don't feel ___.", "well", ["good", "well", "best"], "Health.", "Feel well = healthy.", "well-health"),
  q("good-vs-well", 6, "A2", "mcq", "Choose the manner adverb.", "The team played well.", ["The team played good.", "The team played well.", "The team played weller."], "Played is a verb.", "Played well.", "well-verb"),
  q("good-vs-well", 7, "A2", "fix", "He did a well job.", "He did a good job.", ["He did a well job.", "He did a good job.", "He did well job."], "Job is a noun.", "A good job. He did well. are both possible in other shapes.", "good-noun"),
  q("good-vs-well", 8, "A2", "gap", "The food smells ___.", "good", ["good", "well", "best"], "Smell describing the food itself.", "Smell/taste + good (the thing, not how you smell).", "good-noun"),

  q("every-vs-each", 1, "A2", "gap", "___ student passed the test.", "Every", ["Every", "Each of", "Every of"], "The group as a whole.", "Every student.", "every-group"),
  q("every-vs-each", 2, "A2", "gap", "___ locker has a number.", "Each", ["Every of", "Each", "Each of locker"], "Members separately.", "Each locker / each student.", "each-one-by-one"),
  q("every-vs-each", 3, "A2", "fix", "Each students have a key.", "Each student has a key.", ["Each students have a key.", "Each student has a key.", "Every students has a key."], "Each + singular + singular verb.", "Each student has.", "singular-after"),
  q("every-vs-each", 4, "A2", "mcq", "Which is correct?", "Every room is clean.", ["Every rooms are clean.", "Every room is clean.", "Each rooms is clean."], "Every + singular noun.", "Every room is.", "singular-after"),
  q("every-vs-each", 5, "A2", "gap", "There are four doors. ___ door is locked.", "Each", ["Every of", "Each", "Each doors"], "Looking at them one by one.", "Each door is locked.", "each-one-by-one"),
  q("every-vs-each", 6, "A2", "mcq", "Choose the natural group meaning.", "I go running every morning.", ["I go running each mornings.", "I go running every morning.", "I go running every mornings."], "Habit across the set of mornings.", "Every morning.", "every-group"),
  q("every-vs-each", 7, "A2", "fix", "Every of the files is ready.", "Each of the files is ready.", ["Every of the files is ready.", "Each of the files is ready.", "Every of files is ready."], "Each of + the + plural.", "Each of the files. Not every of.", "each-one-by-one"),
  q("every-vs-each", 8, "A2", "gap", "___ child needs a ticket.", "Every", ["Every", "Every of", "Each of child"], "All children as a set.", "Every child needs…", "every-group"),

  q("other-another-others", 1, "A2", "gap", "Would you like ___ biscuit?", "another", ["other", "another", "others"], "One more of the same.", "Another + singular.", "another-one"),
  q("other-another-others", 2, "A2", "gap", "I spoke to a few people. ___ were busy.", "Others", ["Other", "Others", "Another"], "No noun after it.", "Others stands alone.", "others-alone"),
  q("other-another-others", 3, "A2", "fix", "Do you have other stamp?", "Do you have another stamp?", ["Do you have other stamp?", "Do you have another stamp?", "Do you have others stamp?"], "One stamp.", "Another stamp.", "another-one"),
  q("other-another-others", 4, "A2", "mcq", "Which is correct?", "The other bag is in the car.", ["The another bag is in the car.", "The other bag is in the car.", "The others bag is in the car."], "The remaining one.", "The other + noun.", "the-other"),
  q("other-another-others", 5, "A2", "gap", "Some staff stayed. ___ left at 5.", "Others", ["Other", "Others", "Another"], "Stand-alone plural.", "Others left.", "others-alone"),
  q("other-another-others", 6, "A2", "mcq", "Choose the form before a plural noun.", "other people", ["another people", "other people", "others people"], "Other + noun.", "Other people, not another people.", "other-plus-noun"),
  q("other-another-others", 7, "A2", "fix", "I need others chair.", "I need another chair.", ["I need others chair.", "I need another chair.", "I need other chair."], "One chair.", "Another chair.", "another-one"),
  q("other-another-others", 8, "A2", "gap", "One file is here. Where is ___ file?", "the other", ["another", "the other", "others"], "The last remaining one.", "The other file.", "the-other"),

  q("been-vs-gone", 1, "A2", "mcq", "She isn't in the office. She ___ to the bank.", "has gone", ["has been", "has gone", "have gone"], "She is still there.", "Has gone = not back yet.", "gone-still-there"),
  q("been-vs-gone", 2, "A2", "gap", "I ___ to Lisbon twice. I'm home now.", "have been", ["have gone", "have been", "has been"], "Experience; you returned.", "Have been = went and came back.", "been-back"),
  q("been-vs-gone", 3, "A2", "fix", "Where is Tom? He has been to the shops.", "He has gone to the shops.", ["He has been to the shops.", "He has gone to the shops.", "He have gone to the shops."], "Still out = gone.", "Has gone to the shops.", "gone-still-there"),
  q("been-vs-gone", 4, "A2", "mcq", "Which means the trip is finished and they are back?", "They have been to Italy.", ["They have gone to Italy.", "They have been to Italy.", "They has been to Italy."], "Been = experience / returned.", "Have been to Italy.", "been-back"),
  q("been-vs-gone", 5, "A2", "gap", "The manager ___ to lunch. She'll be back at 2.", "has gone", ["has been", "has gone", "have gone"], "Not here now.", "Has gone to lunch.", "gone-still-there"),
  q("been-vs-gone", 6, "A2", "mcq", "Choose the experience sentence.", "Have you ever been to Prague?", ["Have you ever gone and still there?", "Have you ever been to Prague?", "Has you ever been to Prague?"], "Ever + been for life experience.", "Have you ever been…?", "been-back"),
  q("been-vs-gone", 7, "A2", "fix", "I have gone to that café many times. I'm telling you now, at home.", "I have been to that café many times.", ["I have gone to that café many times.", "I have been to that café many times.", "I has been to that café many times."], "You returned.", "Have been many times.", "been-back"),
  q("been-vs-gone", 8, "A2", "gap", "Aisha isn't here. She ___ home.", "has gone", ["has been", "has gone", "have gone"], "She left and is still away.", "Has gone home.", "gone-still-there"),

  q("ed-vs-ing-adjectives", 1, "A2", "gap", "I am ___ because the meeting is long.", "bored", ["bored", "boring", "bore"], "How you feel.", "-ed = feeling: bored.", "ed-feeling"),
  q("ed-vs-ing-adjectives", 2, "A2", "gap", "The meeting is ___.", "boring", ["bored", "boring", "bored of"], "The thing causes the feeling.", "-ing = the cause: boring.", "ing-cause"),
  q("ed-vs-ing-adjectives", 3, "A2", "fix", "The news are very excited.", "The news is very exciting.", ["The news are very excited.", "The news is very exciting.", "I am very exciting about the news."], "News causes the feeling.", "Exciting news. I am excited.", "ing-cause"),
  q("ed-vs-ing-adjectives", 4, "A2", "mcq", "Which is correct?", "We were tired after the trip.", ["We were tiring after the trip.", "We were tired after the trip.", "The trip was tired."], "People feel -ed.", "We were tired. The trip was tiring.", "ed-feeling"),
  q("ed-vs-ing-adjectives", 5, "A2", "gap", "That was a ___ documentary.", "interesting", ["interested", "interesting", "interest"], "The documentary causes interest.", "Interesting documentary.", "ing-cause"),
  q("ed-vs-ing-adjectives", 6, "A2", "mcq", "Choose how the person feels.", "She is interested in design.", ["She is interesting in design.", "She is interested in design.", "Design is interested."], "Person + -ed.", "Interested in.", "ed-feeling"),
  q("ed-vs-ing-adjectives", 7, "A2", "fix", "I am boring at work today.", "I am bored at work today.", ["I am boring at work today.", "I am bored at work today.", "Work is bored today."], "Your feeling.", "I am bored. Work is boring.", "ed-feeling"),
  q("ed-vs-ing-adjectives", 8, "A2", "gap", "The instructions were ___ , so I got mixed up.", "confusing", ["confused", "confusing", "confuse"], "Instructions cause the feeling.", "Confusing instructions. I was confused.", "ing-cause"),
];
