import type { Question } from "../lib/types";
import { PHASE2_QUESTIONS } from "./questions-phase2";
import { PHASE3_QUESTIONS } from "./questions-phase3";
import { PHASE4_QUESTIONS } from "./questions-phase4";

const PHASE1_QUESTIONS: Question[] = [
  // --- a / an / the ---
  {
    id: "art-01",
    topicId: "a-an-the",
    level: "A1",
    type: "gap",
    prompt: "She bought ___ umbrella.",
    answer: "an",
    options: ["a", "an", "the"],
    hint: "Umbrella starts with a vowel sound.",
    explanation: "Use an before a vowel sound: an umbrella, an hour. A umbrella is wrong.",
    subRule: "an-before-vowel-sound",
  },
  {
    id: "art-02",
    topicId: "a-an-the",
    level: "A1",
    type: "gap",
    prompt: "He waited for ___ hour.",
    answer: "an",
    options: ["a", "an", "the"],
    hint: "Hour starts with a vowel sound, even though it begins with h.",
    explanation: "Hour sounds like it starts with a vowel, so an hour. Spellings can trick you; listen to the sound.",
    subRule: "an-before-vowel-sound",
  },
  {
    id: "art-03",
    topicId: "a-an-the",
    level: "A1",
    type: "gap",
    prompt: "I have ___ dog.",
    answer: "a",
    options: ["a", "an", "the"],
    hint: "Dog starts with a consonant sound, and this dog is not a specific one yet.",
    explanation: "First mention of one thing: a dog. Dog starts with a consonant sound, so a, not an.",
    subRule: "a-before-consonant",
  },
  {
    id: "art-04",
    topicId: "a-an-the",
    level: "A1",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "Can you close the window?",
    options: ["Can you close a window?", "Can you close the window?", "Can you close window?"],
    hint: "You both know which window you mean.",
    explanation: "Use the when both people know which thing: the window in this room. A window would mean any window.",
    subRule: "the-specific",
  },
  {
    id: "art-05",
    topicId: "a-an-the",
    level: "A1",
    type: "gap",
    prompt: "There is ___ orange on the table.",
    answer: "an",
    options: ["a", "an", "the"],
    hint: "Orange starts with a vowel sound. This is the first time we mention it.",
    explanation: "First mention + vowel sound → an orange. Later you could say the orange if you both mean that one.",
    subRule: "an-before-vowel-sound",
  },
  {
    id: "art-06",
    topicId: "a-an-the",
    level: "A1",
    type: "fix",
    prompt: "She is a engineer.",
    answer: "She is an engineer.",
    options: ["She is a engineer.", "She is an engineer.", "She is the engineer."],
    hint: "Engineer starts with a vowel sound.",
    explanation: "Jobs use a/an: a teacher, an engineer. Engineer starts with a vowel sound, so an.",
    subRule: "an-before-vowel-sound",
  },
  {
    id: "art-07",
    topicId: "a-an-the",
    level: "A1",
    type: "gap",
    prompt: "Please pass me ___ salt.",
    answer: "the",
    options: ["a", "an", "the"],
    hint: "You both can see which salt you mean.",
    explanation: "When there is one obvious thing, use the: the salt, the door, the sun.",
    subRule: "the-specific",
  },
  {
    id: "art-08",
    topicId: "a-an-the",
    level: "A1",
    type: "mcq",
    prompt: "Which word cannot take an?",
    answer: "university",
    options: ["apple", "hour", "university"],
    hint: "Listen to the first sound, not the first letter.",
    explanation: "University starts with a /j/ sound (like you), a consonant sound, so a university. An apple and an hour are correct.",
    subRule: "a-before-consonant",
  },
  {
    id: "art-09",
    topicId: "a-an-the",
    level: "A1",
    type: "gap",
    prompt: "I saw ___ movie last night. ___ movie was long.",
    answer: "a / the",
    options: ["a / the", "the / a", "a / a"],
    hint: "First you introduce it, then you both know which one.",
    explanation: "First mention: a movie. Second mention of the same movie: the movie.",
    subRule: "first-then-the",
  },
  {
    id: "art-10",
    topicId: "a-an-the",
    level: "A1",
    type: "fix",
    prompt: "I need a information.",
    answer: "I need information.",
    options: ["I need a information.", "I need an information.", "I need information."],
    hint: "Information is uncountable — it does not take a/an.",
    explanation: "Do not use a/an with uncountable nouns like information, advice, furniture. Just information, or some information.",
    subRule: "no-a-with-uncountable",
  },

  // --- am / is / are ---
  {
    id: "be-01",
    topicId: "am-is-are",
    level: "A1",
    type: "gap",
    prompt: "I ___ a student.",
    answer: "am",
    options: ["am", "is", "are"],
    hint: "The subject is I.",
    explanation: "Always I am. Never I is or I are.",
    subRule: "i-am",
  },
  {
    id: "be-02",
    topicId: "am-is-are",
    level: "A1",
    type: "gap",
    prompt: "She ___ at home.",
    answer: "is",
    options: ["am", "is", "are"],
    hint: "She is one person: he / she / it.",
    explanation: "He, she, and it take is: She is at home.",
    subRule: "he-she-it-is",
  },
  {
    id: "be-03",
    topicId: "am-is-are",
    level: "A1",
    type: "gap",
    prompt: "They ___ late.",
    answer: "are",
    options: ["am", "is", "are"],
    hint: "They is more than one.",
    explanation: "You, we, and they take are: They are late.",
    subRule: "you-we-they-are",
  },
  {
    id: "be-04",
    topicId: "am-is-are",
    level: "A1",
    type: "fix",
    prompt: "He are my brother.",
    answer: "He is my brother.",
    options: ["He are my brother.", "He is my brother.", "He am my brother."],
    hint: "He goes with is.",
    explanation: "He is one person, so He is my brother.",
    subRule: "he-she-it-is",
  },
  {
    id: "be-05",
    topicId: "am-is-are",
    level: "A1",
    type: "gap",
    prompt: "You ___ very kind.",
    answer: "are",
    options: ["am", "is", "are"],
    hint: "You always takes are, even for one person.",
    explanation: "You are — singular or plural. Never you is.",
    subRule: "you-we-they-are",
  },
  {
    id: "be-06",
    topicId: "am-is-are",
    level: "A1",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "We are ready.",
    options: ["We is ready.", "We am ready.", "We are ready."],
    hint: "We is like they.",
    explanation: "We are ready. We takes are.",
    subRule: "you-we-they-are",
  },
  {
    id: "be-07",
    topicId: "am-is-are",
    level: "A1",
    type: "gap",
    prompt: "It ___ cold today.",
    answer: "is",
    options: ["am", "is", "are"],
    hint: "It is like he and she.",
    explanation: "It is cold. Weather and time also use it is: It is 3 o’clock.",
    subRule: "he-she-it-is",
  },
  {
    id: "be-08",
    topicId: "am-is-are",
    level: "A1",
    type: "gap",
    prompt: "My friends ___ in the kitchen.",
    answer: "are",
    options: ["am", "is", "are"],
    hint: "Friends is plural.",
    explanation: "Plural nouns take are: My friends are in the kitchen.",
    subRule: "you-we-they-are",
  },
  {
    id: "be-09",
    topicId: "am-is-are",
    level: "A1",
    type: "fix",
    prompt: "I is tired.",
    answer: "I am tired.",
    options: ["I is tired.", "I am tired.", "I are tired."],
    hint: "I never takes is.",
    explanation: "I am tired. The pair is always I + am.",
    subRule: "i-am",
  },
  {
    id: "be-10",
    topicId: "am-is-are",
    level: "A1",
    type: "mcq",
    prompt: "Choose the correct pair.",
    answer: "The shop is closed.",
    options: ["The shop are closed.", "The shop is closed.", "The shop am closed."],
    hint: "The shop is one thing — like it.",
    explanation: "Singular nouns take is: The shop is closed.",
    subRule: "he-she-it-is",
  },

  // --- present simple vs continuous ---
  {
    id: "psc-01",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "gap",
    prompt: "She usually ___ coffee in the morning.",
    answer: "drinks",
    options: ["drinks", "is drinking", "drink"],
    hint: "Look at usually — that is a habit.",
    explanation: "Habits use present simple: She usually drinks coffee. Present continuous is for now, not for usually.",
    subRule: "habit-vs-now",
  },
  {
    id: "psc-02",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "gap",
    prompt: "Quiet, please. He ___ (work) right now.",
    answer: "is working",
    options: ["works", "is working", "work"],
    hint: "Right now means this moment.",
    explanation: "Actions happening now use am/is/are + -ing: He is working right now.",
    subRule: "habit-vs-now",
  },
  {
    id: "psc-03",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "mcq",
    prompt: "Which sentence describes a habit?",
    answer: "I take the bus every day.",
    options: ["I am taking the bus every day.", "I take the bus every day.", "I taking the bus every day."],
    hint: "Every day is a routine.",
    explanation: "Every day, always, usually → present simple. I am taking the bus every day mixes a now form with a habit.",
    subRule: "habit-vs-now",
  },
  {
    id: "psc-04",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "fix",
    prompt: "I am knowing her very well.",
    answer: "I know her very well.",
    options: ["I am knowing her very well.", "I know her very well.", "I knowing her very well."],
    hint: "Know is a state, not an action you do in this moment.",
    explanation: "Verbs like know, like, want, believe stay in present simple. Not I am knowing.",
    subRule: "stative-verbs",
  },
  {
    id: "psc-05",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "gap",
    prompt: "Look! The children ___ in the garden.",
    answer: "are playing",
    options: ["play", "are playing", "plays"],
    hint: "Look! points to something happening now.",
    explanation: "Look! and Listen! introduce now: The children are playing.",
    subRule: "habit-vs-now",
  },
  {
    id: "psc-06",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "gap",
    prompt: "Water ___ at 100 degrees.",
    answer: "boils",
    options: ["boils", "is boiling", "boil"],
    hint: "This is a scientific fact, not this kettle right now.",
    explanation: "Facts use present simple: Water boils at 100 degrees. Is boiling would mean this water, now.",
    subRule: "facts-simple",
  },
  {
    id: "psc-07",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "mcq",
    prompt: "Choose the correct sentence.",
    answer: "I am staying with a friend this week.",
    options: [
      "I stay with a friend this week.",
      "I am staying with a friend this week.",
      "I staying with a friend this week.",
    ],
    hint: "This week is a temporary situation around now.",
    explanation: "Temporary situations around now can use present continuous: I am staying with a friend this week.",
    subRule: "temporary-now",
  },
  {
    id: "psc-08",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "gap",
    prompt: "He ___ (not / like) spicy food.",
    answer: "doesn't like",
    options: ["doesn't like", "isn't liking", "don't like"],
    hint: "Like is a feeling, and he is the subject.",
    explanation: "Negatives of habits/states: doesn't like. Not isn't liking. He/she/it uses doesn't.",
    subRule: "stative-verbs",
  },
  {
    id: "psc-09",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "fix",
    prompt: "She live in Madrid.",
    answer: "She lives in Madrid.",
    options: ["She live in Madrid.", "She lives in Madrid.", "She is live in Madrid."],
    hint: "He/she/it needs -s in present simple.",
    explanation: "Present simple for he/she/it adds -s: She lives in Madrid. That is a fact, not a now action.",
    subRule: "he-she-it-s",
  },
  {
    id: "psc-10",
    topicId: "present-simple-vs-continuous",
    level: "A2",
    type: "gap",
    prompt: "What ___ you ___ (do) at the moment?",
    answer: "are / doing",
    options: ["are / doing", "do / do", "are / do"],
    hint: "At the moment = now.",
    explanation: "At the moment needs present continuous: What are you doing? What do you do? would ask about your job or habit.",
    subRule: "habit-vs-now",
  },

  // --- past simple ---
  {
    id: "ps-01",
    topicId: "past-simple",
    level: "A1",
    type: "gap",
    prompt: "Yesterday I ___ (watch) a film.",
    answer: "watched",
    options: ["watched", "watch", "watches"],
    hint: "Yesterday is finished time. Watch is regular.",
    explanation: "Finished time + regular verb → -ed: I watched a film yesterday.",
    subRule: "regular-ed",
  },
  {
    id: "ps-02",
    topicId: "past-simple",
    level: "A1",
    type: "gap",
    prompt: "She ___ (go) to work by bus.",
    answer: "went",
    options: ["goed", "went", "goes"],
    hint: "Go is irregular.",
    explanation: "Go → went. There is no goed.",
    subRule: "irregular",
  },
  {
    id: "ps-03",
    topicId: "past-simple",
    level: "A1",
    type: "fix",
    prompt: "Did you went home?",
    answer: "Did you go home?",
    options: ["Did you went home?", "Did you go home?", "Did you goed home?"],
    hint: "After did, use the base verb.",
    explanation: "Did already shows past. Use the base form: Did you go…? not Did you went…?",
    subRule: "did-plus-base",
  },
  {
    id: "ps-04",
    topicId: "past-simple",
    level: "A1",
    type: "gap",
    prompt: "I ___ (not / see) him last week.",
    answer: "didn't see",
    options: ["didn't see", "didn't saw", "don't see"],
    hint: "Last week is past. After didn't, use the base verb.",
    explanation: "Negatives: didn't + base verb: I didn't see him. Not didn't saw.",
    subRule: "did-plus-base",
  },
  {
    id: "ps-05",
    topicId: "past-simple",
    level: "A1",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "They left at 6.",
    options: ["They leaved at 6.", "They left at 6.", "They leaveed at 6."],
    hint: "Leave is irregular.",
    explanation: "Leave → left. Leaved is not a word.",
    subRule: "irregular",
  },
  {
    id: "ps-06",
    topicId: "past-simple",
    level: "A1",
    type: "gap",
    prompt: "We ___ (arrive) late.",
    answer: "arrived",
    options: ["arrived", "arrive", "arriving"],
    hint: "Regular verb, finished action.",
    explanation: "Arrive is regular: arrived. (Drop e, add -ed, or just add -d after e.)",
    subRule: "regular-ed",
  },
  {
    id: "ps-07",
    topicId: "past-simple",
    level: "A1",
    type: "gap",
    prompt: "Where ___ she ___ (live) in 2018?",
    answer: "did / live",
    options: ["did / live", "did / lived", "does / live"],
    hint: "2018 is finished. Questions need did.",
    explanation: "Past question: did + subject + base: Where did she live…? Not did she lived.",
    subRule: "did-plus-base",
  },
  {
    id: "ps-08",
    topicId: "past-simple",
    level: "A1",
    type: "mcq",
    prompt: "Choose the correct past form of buy.",
    answer: "bought",
    options: ["buyed", "bought", "boughted"],
    hint: "Buy is irregular.",
    explanation: "Buy → bought. Not buyed.",
    subRule: "irregular",
  },
  {
    id: "ps-09",
    topicId: "past-simple",
    level: "A1",
    type: "fix",
    prompt: "He didn't called me.",
    answer: "He didn't call me.",
    options: ["He didn't called me.", "He didn't call me.", "He didn't calls me."],
    hint: "Didn't already marks the past.",
    explanation: "After didn't, the verb stays in the base form: didn't call, not didn't called.",
    subRule: "did-plus-base",
  },
  {
    id: "ps-10",
    topicId: "past-simple",
    level: "A1",
    type: "gap",
    prompt: "Last night the shop ___ (close) at 8.",
    answer: "closed",
    options: ["closed", "closes", "close"],
    hint: "Last night is finished time.",
    explanation: "Finished time signal (last night) + regular verb: closed.",
    subRule: "regular-ed",
  },

  // --- subject vs object pronouns ---
  {
    id: "pro-01",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "gap",
    prompt: "___ called me yesterday. (Sarah)",
    answer: "She",
    options: ["She", "Her", "Hers"],
    hint: "This person does the calling.",
    explanation: "The subject does the action: She called me. Her called me is wrong.",
    subRule: "subject-form",
  },
  {
    id: "pro-02",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "gap",
    prompt: "Can you help ___?",
    answer: "me",
    options: ["I", "me", "my"],
    hint: "Help is a verb; the pronoun after it receives the action.",
    explanation: "After a verb, use the object form: help me, not help I.",
    subRule: "object-after-verb",
  },
  {
    id: "pro-03",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "fix",
    prompt: "Him is my colleague.",
    answer: "He is my colleague.",
    options: ["Him is my colleague.", "He is my colleague.", "His is my colleague."],
    hint: "This person is the subject of is.",
    explanation: "Subjects: I, he, she, we, they. He is my colleague, not Him is.",
    subRule: "subject-form",
  },
  {
    id: "pro-04",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "gap",
    prompt: "I saw ___ at the station. (Tom and Ana)",
    answer: "them",
    options: ["they", "them", "their"],
    hint: "Saw is a verb; Tom and Ana receive the action.",
    explanation: "They is the subject form. After saw, use them.",
    subRule: "object-after-verb",
  },
  {
    id: "pro-05",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "gap",
    prompt: "This gift is for ___.",
    answer: "her",
    options: ["she", "her", "hers"],
    hint: "For is a preposition.",
    explanation: "After a preposition (for, to, with, at), use the object: for her, not for she.",
    subRule: "object-after-preposition",
  },
  {
    id: "pro-06",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "We met them after work.",
    options: ["We met they after work.", "Us met them after work.", "We met them after work."],
    hint: "We does the meeting; them receives it.",
    explanation: "Subject + verb + object: We met them.",
    subRule: "object-after-verb",
  },
  {
    id: "pro-07",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "fix",
    prompt: "Please sit between he and I.",
    answer: "Please sit between him and me.",
    options: ["Please sit between he and I.", "Please sit between him and me.", "Please sit between him and I."],
    hint: "Between is a preposition; both pronouns are objects.",
    explanation: "After between, both pronouns are objects: him and me. Between he and I is a common mistake.",
    subRule: "object-after-preposition",
  },
  {
    id: "pro-08",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "gap",
    prompt: "___ live near the park.",
    answer: "They",
    options: ["Them", "They", "Their"],
    hint: "Someone lives — that is the subject.",
    explanation: "They live… Them live is wrong.",
    subRule: "subject-form",
  },
  {
    id: "pro-09",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "gap",
    prompt: "The manager asked you and me to wait. The manager asked ___ to wait.",
    answer: "us",
    options: ["we", "us", "our"],
    hint: "Asked whom? The object of asked.",
    explanation: "The manager asked us. We asked would make we the subject.",
    subRule: "object-after-verb",
  },
  {
    id: "pro-10",
    topicId: "subject-object-pronouns",
    level: "A1",
    type: "mcq",
    prompt: "Choose the object pronoun for I.",
    answer: "me",
    options: ["my", "me", "mine"],
    hint: "Object forms: me, you, him, her, it, us, them.",
    explanation: "I → me. My and mine show possession, not the object of a verb.",
    subRule: "object-after-verb",
  },

  // --- prepositions of place ---
  {
    id: "pl-01",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "The keys are ___ the table.",
    answer: "on",
    options: ["in", "on", "at"],
    hint: "The table is a surface.",
    explanation: "On = on a surface: on the table, on the wall, on the floor.",
    subRule: "on-surface",
  },
  {
    id: "pl-02",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "She is ___ the kitchen.",
    answer: "in",
    options: ["in", "on", "at"],
    hint: "The kitchen is a space you can be inside.",
    explanation: "In = inside a space: in the kitchen, in the room, in a box.",
    subRule: "in-space",
  },
  {
    id: "pl-03",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "I'll meet you ___ the station.",
    answer: "at",
    options: ["in", "on", "at"],
    hint: "Think of the station as a meeting point.",
    explanation: "At = a point: at the station, at the door, at the bus stop.",
    subRule: "at-point",
  },
  {
    id: "pl-04",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "He is at home.",
    options: ["He is in home.", "He is at home.", "He is on home."],
    hint: "Home with this meaning is a point, not a room you name.",
    explanation: "The fixed phrase is at home. In the house is also possible, but not in home.",
    subRule: "at-point",
  },
  {
    id: "pl-05",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "There is a picture ___ the wall.",
    answer: "on",
    options: ["in", "on", "at"],
    hint: "The picture is attached to the surface of the wall.",
    explanation: "On the wall, on the ceiling — attached to a surface.",
    subRule: "on-surface",
  },
  {
    id: "pl-06",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "fix",
    prompt: "The milk is on the fridge.",
    answer: "The milk is in the fridge.",
    options: ["The milk is on the fridge.", "The milk is in the fridge.", "The milk is at the fridge."],
    hint: "The fridge is a container / space.",
    explanation: "Inside a container: in the fridge, in the bag. On the fridge would mean on top of it.",
    subRule: "in-space",
  },
  {
    id: "pl-07",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "Someone is ___ the door.",
    answer: "at",
    options: ["in", "on", "at"],
    hint: "The door is a point, not a room.",
    explanation: "At the door = standing by that point. In the door is not used this way.",
    subRule: "at-point",
  },
  {
    id: "pl-08",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "They live ___ London.",
    answer: "in",
    options: ["in", "on", "at"],
    hint: "Cities and countries are spaces you live inside.",
    explanation: "In a city or country: in London, in Japan. At London is wrong for living there.",
    subRule: "in-space",
  },
  {
    id: "pl-09",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "mcq",
    prompt: "Choose the correct sentence.",
    answer: "The book is on the shelf.",
    options: ["The book is in the shelf.", "The book is on the shelf.", "The book is at the shelf."],
    hint: "A shelf is a surface.",
    explanation: "On the shelf. In the shelf would mean inside the wood.",
    subRule: "on-surface",
  },
  {
    id: "pl-10",
    topicId: "prepositions-of-place",
    level: "A1",
    type: "gap",
    prompt: "She works ___ the hospital.",
    answer: "at",
    options: ["in", "on", "at"],
    hint: "Workplaces as points often take at: at the hospital, at school.",
    explanation: "At the hospital / at school = that workplace as a point. In the hospital can mean as a patient inside the building.",
    subRule: "at-point",
  },

  // --- prepositions of time ---
  {
    id: "tm-01",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "The class starts ___ Monday.",
    answer: "on",
    options: ["in", "on", "at"],
    hint: "Monday is a day.",
    explanation: "On + day or date: on Monday, on 5 May.",
    subRule: "on-day",
  },
  {
    id: "tm-02",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "I was born ___ 1998.",
    answer: "in",
    options: ["in", "on", "at"],
    hint: "1998 is a year.",
    explanation: "In + month, year, or century: in 1998, in June, in the 1990s.",
    subRule: "in-month-year",
  },
  {
    id: "tm-03",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "Let's meet ___ 7 o'clock.",
    answer: "at",
    options: ["in", "on", "at"],
    hint: "7 o'clock is a clock time.",
    explanation: "At + clock time: at 7, at midnight. Also at night, at the weekend (British).",
    subRule: "at-clock",
  },
  {
    id: "tm-04",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "She runs in the morning.",
    options: ["She runs on the morning.", "She runs in the morning.", "She runs at the morning."],
    hint: "Parts of the day usually take in, except night.",
    explanation: "In the morning / afternoon / evening. But at night.",
    subRule: "in-month-year",
  },
  {
    id: "tm-05",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "The shop is closed ___ Sundays.",
    answer: "on",
    options: ["in", "on", "at"],
    hint: "Sundays are days.",
    explanation: "On Sundays, on weekdays — still a day.",
    subRule: "on-day",
  },
  {
    id: "tm-06",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "fix",
    prompt: "The meeting is in Friday.",
    answer: "The meeting is on Friday.",
    options: ["The meeting is in Friday.", "The meeting is on Friday.", "The meeting is at Friday."],
    hint: "Friday is a day, not a month.",
    explanation: "Days take on, not in: on Friday.",
    subRule: "on-day",
  },
  {
    id: "tm-07",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "He often reads ___ night.",
    answer: "at",
    options: ["in", "on", "at"],
    hint: "Night is the special case among parts of the day.",
    explanation: "At night, not in night. Contrast: in the evening.",
    subRule: "at-clock",
  },
  {
    id: "tm-08",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "We got married ___ July.",
    answer: "in",
    options: ["in", "on", "at"],
    hint: "July is a month.",
    explanation: "In July. If you add a date: on 12 July.",
    subRule: "in-month-year",
  },
  {
    id: "tm-09",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "mcq",
    prompt: "Choose the correct option.",
    answer: "The train leaves at 9:15.",
    options: ["The train leaves on 9:15.", "The train leaves in 9:15.", "The train leaves at 9:15."],
    hint: "Clock times take at.",
    explanation: "At 9:15. On is for days; in is for months and years.",
    subRule: "at-clock",
  },
  {
    id: "tm-10",
    topicId: "prepositions-of-time",
    level: "A1",
    type: "gap",
    prompt: "Her birthday is ___ 3 March.",
    answer: "on",
    options: ["in", "on", "at"],
    hint: "3 March is a date.",
    explanation: "On + date: on 3 March, on the 3rd of March.",
    subRule: "on-day",
  },

  // --- there is / there are ---
  {
    id: "th-01",
    topicId: "there-is-there-are",
    level: "A1",
    type: "gap",
    prompt: "___ a cat in the garden.",
    answer: "There is",
    options: ["There is", "There are", "There"],
    hint: "A cat is one thing.",
    explanation: "There is + singular: There is a cat.",
    subRule: "singular-is",
  },
  {
    id: "th-02",
    topicId: "there-is-there-are",
    level: "A1",
    type: "gap",
    prompt: "___ two chairs in the kitchen.",
    answer: "There are",
    options: ["There is", "There are", "They are"],
    hint: "Two chairs is plural.",
    explanation: "There are + plural: There are two chairs. They are two chairs would describe the chairs, not introduce them.",
    subRule: "plural-are",
  },
  {
    id: "th-03",
    topicId: "there-is-there-are",
    level: "A1",
    type: "fix",
    prompt: "There is many people here.",
    answer: "There are many people here.",
    options: ["There is many people here.", "There are many people here.", "There many people here."],
    hint: "People is plural.",
    explanation: "People is plural, so there are many people.",
    subRule: "plural-are",
  },
  {
    id: "th-04",
    topicId: "there-is-there-are",
    level: "A1",
    type: "mcq",
    prompt: "Which question is correct?",
    answer: "Is there a bank near here?",
    options: ["Is there a bank near here?", "Are there a bank near here?", "There is a bank near here?"],
    hint: "A bank is singular; invert is there.",
    explanation: "Singular question: Is there…? Plural: Are there any shops…?",
    subRule: "singular-is",
  },
  {
    id: "th-05",
    topicId: "there-is-there-are",
    level: "A1",
    type: "gap",
    prompt: "___ any milk in the fridge?",
    answer: "Is there",
    options: ["Is there", "Are there", "There is"],
    hint: "Milk is uncountable — treat it like singular.",
    explanation: "Uncountable nouns take is there / there is: Is there any milk?",
    subRule: "singular-is",
  },
  {
    id: "th-06",
    topicId: "there-is-there-are",
    level: "A1",
    type: "gap",
    prompt: "___ some books on the desk.",
    answer: "There are",
    options: ["There is", "There are", "There have"],
    hint: "Books is plural.",
    explanation: "There are some books. English does not use there have for this meaning.",
    subRule: "plural-are",
  },
  {
    id: "th-07",
    topicId: "there-is-there-are",
    level: "A1",
    type: "fix",
    prompt: "There are a problem.",
    answer: "There is a problem.",
    options: ["There are a problem.", "There is a problem.", "There have a problem."],
    hint: "A problem is one thing.",
    explanation: "A + singular noun → there is: There is a problem.",
    subRule: "singular-is",
  },
  {
    id: "th-08",
    topicId: "there-is-there-are",
    level: "A1",
    type: "mcq",
    prompt: "Choose the correct negative.",
    answer: "There isn't any sugar.",
    options: ["There isn't any sugar.", "There aren't any sugar.", "There no sugar."],
    hint: "Sugar is uncountable.",
    explanation: "Uncountable: there isn't any sugar. Aren't needs a plural count noun: there aren't any eggs.",
    subRule: "singular-is",
  },
  {
    id: "th-09",
    topicId: "there-is-there-are",
    level: "A1",
    type: "gap",
    prompt: "___ three windows in this room.",
    answer: "There are",
    options: ["There is", "There are", "It is"],
    hint: "Three windows is more than one.",
    explanation: "There are three windows. It is three windows is not used to introduce them.",
    subRule: "plural-are",
  },
  {
    id: "th-10",
    topicId: "there-is-there-are",
    level: "A1",
    type: "gap",
    prompt: "___ an airport in the city?",
    answer: "Is there",
    options: ["Is there", "Are there", "There is"],
    hint: "An airport is singular.",
    explanation: "Is there an airport…? Use are there only with plurals.",
    subRule: "singular-is",
  },

  // --- comparatives and superlatives ---
  {
    id: "cs-01",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "gap",
    prompt: "This bag is ___ (cheap) than that one.",
    answer: "cheaper",
    options: ["cheaper", "more cheap", "cheapest"],
    hint: "Cheap is a short adjective. You are comparing two things.",
    explanation: "Short adjectives add -er: cheaper than. Use than, not that.",
    subRule: "short-er",
  },
  {
    id: "cs-02",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "gap",
    prompt: "This hotel is ___ (expensive) than the last one.",
    answer: "more expensive",
    options: ["expensiver", "more expensive", "most expensive"],
    hint: "Expensive is a long adjective.",
    explanation: "Long adjectives use more + adjective: more expensive than. Not expensiver.",
    subRule: "more-long",
  },
  {
    id: "cs-03",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "fix",
    prompt: "My car is faster that yours.",
    answer: "My car is faster than yours.",
    options: ["My car is faster that yours.", "My car is faster than yours.", "My car is more fast than yours."],
    hint: "The word after a comparative is than.",
    explanation: "Always than after a comparative: faster than, not faster that.",
    subRule: "than-not-that",
  },
  {
    id: "cs-04",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "gap",
    prompt: "This is ___ (good) coffee in the café.",
    answer: "the best",
    options: ["the better", "the best", "better"],
    hint: "You mean number one in the group. Good is irregular.",
    explanation: "Good → better → the best. Superlatives need the: the best coffee.",
    subRule: "superlative-the",
  },
  {
    id: "cs-05",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "mcq",
    prompt: "Which sentence is correct?",
    answer: "She is the tallest in her family.",
    options: [
      "She is the most tall in her family.",
      "She is the tallest in her family.",
      "She is taller of her family.",
    ],
    hint: "Tall is short; you mean number one in the group.",
    explanation: "Short adjective superlative: the tallest. Most tall is wrong. Taller is only for two-way comparison.",
    subRule: "superlative-the",
  },
  {
    id: "cs-06",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "gap",
    prompt: "Today is ___ (hot) than yesterday.",
    answer: "hotter",
    options: ["hotter", "more hot", "hottest"],
    hint: "Hot is short; double the last letter before -er.",
    explanation: "Hot → hotter (double t). Comparing two days, not the hottest day of the year.",
    subRule: "short-er",
  },
  {
    id: "cs-07",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "gap",
    prompt: "That was ___ (interesting) film of the year.",
    answer: "the most interesting",
    options: ["more interesting", "the most interesting", "interestinger"],
    hint: "Long adjective + the whole year (a group).",
    explanation: "Long superlative: the most interesting. Superlatives take the.",
    subRule: "superlative-the",
  },
  {
    id: "cs-08",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "mcq",
    prompt: "Choose the correct comparative of bad.",
    answer: "worse",
    options: ["badder", "worse", "more bad"],
    hint: "Bad is irregular, like good.",
    explanation: "Bad → worse → the worst. Not badder.",
    subRule: "short-er",
  },
  {
    id: "cs-09",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "fix",
    prompt: "This exam is more easy than the last one.",
    answer: "This exam is easier than the last one.",
    options: [
      "This exam is more easy than the last one.",
      "This exam is easier than the last one.",
      "This exam is easyer than the last one.",
    ],
    hint: "Easy is a short adjective ending in -y.",
    explanation: "Y → i + er: easier than. More easy is not the usual form.",
    subRule: "short-er",
  },
  {
    id: "cs-10",
    topicId: "comparatives-superlatives",
    level: "A2",
    type: "gap",
    prompt: "Of the three routes, this is ___ (quick).",
    answer: "the quickest",
    options: ["quicker", "the quickest", "more quick"],
    hint: "Three routes = a group, so superlative.",
    explanation: "With three or more, use the superlative: the quickest. Quicker is for two.",
    subRule: "superlative-the",
  },

  // --- present perfect vs past simple ---
  {
    id: "pp-01",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "gap",
    prompt: "I ___ Paris in 2019.",
    answer: "visited",
    options: ["visited", "have visited", "visit"],
    hint: "In 2019 is a finished time.",
    explanation: "A finished time (in 2019, yesterday, last year) needs past simple: I visited Paris in 2019. Not have visited in 2019.",
    subRule: "finished-time-past-simple",
  },
  {
    id: "pp-02",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "gap",
    prompt: "I ___ Paris three times.",
    answer: "have visited",
    options: ["visited", "have visited", "was visiting"],
    hint: "Life experience up to now, no finished date.",
    explanation: "Experience without a finished time: I have visited Paris three times. The time is still “my life until now.”",
    subRule: "experience-present-perfect",
  },
  {
    id: "pp-03",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "fix",
    prompt: "I have seen him yesterday.",
    answer: "I saw him yesterday.",
    options: ["I have seen him yesterday.", "I saw him yesterday.", "I have saw him yesterday."],
    hint: "Yesterday is finished.",
    explanation: "Yesterday, last week, ago → past simple. Present perfect does not sit with those time words.",
    subRule: "finished-time-past-simple",
  },
  {
    id: "pp-04",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "mcq",
    prompt: "The door still will not open. Which sentence fits?",
    answer: "She has lost her keys.",
    options: [
      "She lost her keys in 2019.",
      "She has lost her keys.",
      "She has lost her keys yesterday.",
    ],
    hint: "The result is still true now: the door still will not open.",
    explanation: "A past action with a result now often uses present perfect: She has lost her keys (so she still cannot get in). Do not mix present perfect with yesterday.",
    subRule: "result-now",
  },
  {
    id: "pp-05",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "gap",
    prompt: "___ you ever ___ sushi?",
    answer: "Have / eaten",
    options: ["Have / eaten", "Did / eat", "Have / ate"],
    hint: "Ever asks about life experience.",
    explanation: "Ever / never → present perfect: Have you ever eaten sushi? After have, use the past participle eaten, not ate.",
    subRule: "experience-present-perfect",
  },
  {
    id: "pp-06",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "gap",
    prompt: "When ___ you ___ your first job?",
    answer: "did / start",
    options: ["have / started", "did / start", "have / start"],
    hint: "When asks for a finished time.",
    explanation: "When + a finished time answer → past simple: When did you start…? Present perfect avoids when-dates.",
    subRule: "finished-time-past-simple",
  },
  {
    id: "pp-07",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "mcq",
    prompt: "Choose the correct sentence.",
    answer: "He hasn't finished yet.",
    options: ["He didn't finish yet.", "He hasn't finished yet.", "He hasn't finished yesterday."],
    hint: "Yet belongs with present perfect in this meaning.",
    explanation: "Yet (until now) goes with present perfect: He hasn't finished yet. Yesterday cannot combine with hasn't finished.",
    subRule: "result-now",
  },
  {
    id: "pp-08",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "fix",
    prompt: "They have gone to Spain last summer.",
    answer: "They went to Spain last summer.",
    options: [
      "They have gone to Spain last summer.",
      "They went to Spain last summer.",
      "They have went to Spain last summer.",
    ],
    hint: "Last summer is a finished time.",
    explanation: "Last summer pins the action in the past: they went. Present perfect + last summer is the classic clash.",
    subRule: "finished-time-past-simple",
  },
  {
    id: "pp-09",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "gap",
    prompt: "She ___ (live) here since 2020.",
    answer: "has lived",
    options: ["lived", "has lived", "lives"],
    hint: "Since 2020 means from then until now.",
    explanation: "Since / for with a time that continues until now → present perfect: She has lived here since 2020.",
    subRule: "until-now",
  },
  {
    id: "pp-10",
    topicId: "present-perfect-vs-past-simple",
    level: "A2",
    type: "gap",
    prompt: "I ___ (lose) my phone last night, but I found it this morning.",
    answer: "lost",
    options: ["lost", "have lost", "was losing"],
    hint: "Last night is finished, and the story is over (you found it).",
    explanation: "A finished episode with a past time: I lost my phone last night. Have lost would suggest you still don't have it.",
    subRule: "finished-time-past-simple",
  },
];

export const QUESTIONS: Question[] = [
  ...PHASE1_QUESTIONS,
  ...PHASE2_QUESTIONS,
  ...PHASE3_QUESTIONS,
  ...PHASE4_QUESTIONS,
];

export function questionsForTopic(topicId: string): Question[] {
  return QUESTIONS.filter((question) => question.topicId === topicId);
}

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((question) => question.id === id);
}
