import type { Level, Question, QuestionType } from "../lib/types";

function q(
  topicId: string,
  n: number,
  level: Level,
  type: QuestionType,
  prompt: string,
  answer: string,
  options: string[],
  hint: string,
  explanation: string,
  subRule: string,
): Question {
  return {
    id: `${topicId}-${String(n).padStart(2, "0")}`,
    topicId,
    level,
    type,
    prompt,
    answer,
    options,
    hint,
    explanation,
    subRule,
  };
}

export const PHASE4_QUESTIONS: Question[] = [
  q("gerunds-after-verbs", 1, "B1", "gap", "Please keep ___ until I get back.", "waiting", ["waiting", "to wait", "wait"], "Keep takes -ing.", "Keep + -ing: keep waiting.", "keep-ing"),
  q("gerunds-after-verbs", 2, "B1", "gap", "Would you mind ___ the window?", "closing", ["to close", "closing", "close"], "Mind takes -ing.", "Mind + -ing: mind closing.", "mind-ing"),
  q("gerunds-after-verbs", 3, "B1", "fix", "She keeps to interrupt in meetings.", "She keeps interrupting in meetings.", ["She keeps to interrupt in meetings.", "She keeps interrupting in meetings.", "She keeps interrupt in meetings."], "Keep takes -ing.", "Keeps interrupting, not to interrupt.", "keep-ing"),
  q("gerunds-after-verbs", 4, "B1", "mcq", "Which is correct?", "They considered packing at 9.", ["They considered to pack at 9.", "They considered packing at 9.", "They considered pack at 9."], "Consider takes -ing.", "Considered packing.", "mind-ing"),
  q("gerunds-after-verbs", 5, "B1", "gap", "He suggested ___ a taxi.", "taking", ["to take", "taking", "take"], "Suggest takes -ing.", "Suggested taking.", "mind-ing"),
  q("gerunds-after-verbs", 6, "B1", "mcq", "Choose the verb that takes -ing here.", "keep", ["want", "decide", "keep"], "Keep going, not keep to go.", "Keep + -ing.", "keep-ing"),
  q("gerunds-after-verbs", 7, "B1", "fix", "I miss to see my colleagues.", "I miss seeing my colleagues.", ["I miss to see my colleagues.", "I miss seeing my colleagues.", "I miss see my colleagues."], "Miss + -ing.", "Miss seeing.", "mind-ing"),
  q("gerunds-after-verbs", 8, "B1", "gap", "We're considering ___ flats.", "changing", ["to change", "changing", "change"], "Consider takes -ing.", "Considering changing.", "mind-ing"),

  q("infinitives-after-verbs", 1, "B1", "gap", "She decided ___ late.", "to stay", ["staying", "to stay", "stay"], "Decide takes to.", "Decided to stay.", "decide-to"),
  q("infinitives-after-verbs", 2, "B1", "gap", "I want ___ earlier tomorrow.", "to leave", ["leaving", "to leave", "leave"], "Want takes to.", "Want to leave.", "want-to"),
  q("infinitives-after-verbs", 3, "B1", "fix", "They hope finding a flat soon.", "They hope to find a flat soon.", ["They hope finding a flat soon.", "They hope to find a flat soon.", "They hope find a flat soon."], "Hope + to.", "Hope to find.", "decide-to"),
  q("infinitives-after-verbs", 4, "B1", "mcq", "Which is correct?", "We plan to move in June.", ["We plan moving in June.", "We plan to move in June.", "We plan move in June."], "Plan takes to.", "Plan to move.", "want-to"),
  q("infinitives-after-verbs", 5, "B1", "gap", "He refused ___ the form.", "to sign", ["signing", "to sign", "sign"], "Refuse takes to.", "Refused to sign.", "decide-to"),
  q("infinitives-after-verbs", 6, "B1", "mcq", "Choose the verb that takes to here.", "promise", ["enjoy", "avoid", "promise"], "Promise to help, not promising as the locked pair.", "Promise + to.", "want-to"),
  q("infinitives-after-verbs", 7, "B1", "fix", "She offered helping with the boxes.", "She offered to help with the boxes.", ["She offered helping with the boxes.", "She offered to help with the boxes.", "She offered help with the boxes."], "Offer + to.", "Offered to help.", "decide-to"),
  q("infinitives-after-verbs", 8, "B1", "gap", "I'm learning ___ Portuguese.", "to speak", ["speaking", "to speak", "speak"], "Learn takes to.", "Learning to speak.", "want-to"),

  q("linking-words", 1, "A2", "gap", "I stayed home ___ I had a fever.", "because", ["although", "because", "however"], "Gives a reason.", "Because + clause = reason.", "because-reason"),
  q("linking-words", 2, "A2", "gap", "___ it was late, she finished the report.", "Although", ["Because", "Although", "However"], "A fact, then the main point anyway.", "Although concedes; the report still got done.", "although-concede"),
  q("linking-words", 3, "A2", "fix", "I was tired. Although, I went to the gym.", "I was tired. However, I went to the gym.", ["I was tired. Although, I went to the gym.", "I was tired. However, I went to the gym.", "I was tired. Because, I went to the gym."], "Contrast after a full stop.", "However starts the contrast sentence.", "however-contrast"),
  q("linking-words", 4, "A2", "mcq", "Which gives a reason?", "We left because the office closed.", ["We left although the office closed.", "We left because the office closed.", "We left. However the office closed as a reason."], "Because = why.", "Because the office closed.", "because-reason"),
  q("linking-words", 5, "A2", "gap", "The train was delayed. ___, we still arrived before lunch.", "However", ["Although", "Because", "However"], "New sentence, contrast.", "However after a full stop.", "however-contrast"),
  q("linking-words", 6, "A2", "mcq", "Choose the concession.", "Although the cafe was busy, we found a table.", ["Because the cafe was busy, we found a table.", "Although the cafe was busy, we found a table.", "However the cafe was busy we found a table."], "Busy, but still a table.", "Although + clause.", "although-concede"),
  q("linking-words", 7, "A2", "fix", "She called me although she needed help. (reason)", "She called me because she needed help.", ["She called me although she needed help.", "She called me because she needed help.", "She called me. However she needed help."], "Needed help is why she called.", "Because, not although.", "because-reason"),
  q("linking-words", 8, "A2", "gap", "___ the instructions were clear, I still made a mistake.", "Although", ["Because", "Although", "However"], "Clear instructions, mistake anyway.", "Although + clause.", "although-concede"),

  q("despite-in-spite-of", 1, "B1", "gap", "___ the rain, we walked.", "Despite", ["Although", "Despite", "However"], "Rain is a noun.", "Despite + noun.", "despite-noun"),
  q("despite-in-spite-of", 2, "B1", "gap", "In spite of ___ tired, she presented.", "feeling", ["she felt", "feeling", "felt"], "In spite of + -ing or a noun.", "In spite of feeling tired.", "despite-noun"),
  q("despite-in-spite-of", 3, "B1", "fix", "Despite it was noisy, I slept.", "Despite the noise, I slept.", ["Despite it was noisy, I slept.", "Despite the noise, I slept.", "Despite noisy, I slept."], "No full clause after despite.", "Despite + noun: the noise.", "not-clause"),
  q("despite-in-spite-of", 4, "B1", "mcq", "Which is correct?", "In spite of the delay, we caught the train.", ["In spite of it delayed, we caught the train.", "In spite of the delay, we caught the train.", "In spite of delayed, we caught the train."], "In spite of + noun.", "The delay is a noun.", "despite-noun"),
  q("despite-in-spite-of", 5, "B1", "gap", "We booked the hall ___ the cost.", "despite", ["although", "despite", "because"], "Cost is a noun.", "Despite the cost.", "despite-noun"),
  q("despite-in-spite-of", 6, "B1", "mcq", "For a full clause, switch to ___.", "although", ["despite", "in spite of", "although"], "Although + clause.", "Although it was raining — not despite it was.", "not-clause"),
  q("despite-in-spite-of", 7, "B1", "fix", "In spite of she was ill, she came.", "In spite of being ill, she came.", ["In spite of she was ill, she came.", "In spite of being ill, she came.", "In spite of ill, she came."], "No clause after in spite of.", "Being ill / her illness.", "not-clause"),
  q("despite-in-spite-of", 8, "B1", "gap", "___ of the traffic, they were on time.", "In spite", ["Despite", "In spite", "Although"], "The two-word form.", "In spite of + noun.", "despite-noun"),

  q("so-vs-such", 1, "A2", "gap", "The room was ___ cold.", "so", ["so", "such", "such a"], "Cold is an adjective alone.", "So + adjective.", "so-adj"),
  q("so-vs-such", 2, "A2", "gap", "It was ___ a long meeting.", "such", ["so", "such", "too"], "A + adjective + noun.", "Such a long meeting.", "such-noun"),
  q("so-vs-such", 3, "A2", "fix", "She speaks so a quietly voice.", "She speaks so quietly.", ["She speaks so a quietly voice.", "She speaks so quietly.", "She speaks such quietly."], "Quietly is an adverb.", "So + adverb.", "so-adj"),
  q("so-vs-such", 4, "A2", "mcq", "Which is correct?", "They are such friendly neighbours.", ["They are so friendly neighbours.", "They are such friendly neighbours.", "They are such a friendly neighbours."], "Plural noun: such, no a.", "Such + adjective + plural noun.", "such-noun"),
  q("so-vs-such", 5, "A2", "gap", "Why are you walking ___ slowly?", "so", ["so", "such", "such a"], "Slowly is an adverb.", "So slowly.", "so-adj"),
  q("so-vs-such", 6, "A2", "mcq", "Choose the pattern for a noun.", "such a busy day", ["so a busy day", "such a busy day", "so busy a"], "Such a + adjective + noun.", "Such a busy day.", "such-noun"),
  q("so-vs-such", 7, "A2", "fix", "It was so nice weather.", "It was such nice weather.", ["It was so nice weather.", "It was such nice weather.", "It was such a nice weather."], "Weather is uncountable; such + adjective + noun.", "Such nice weather, not so nice weather.", "such-noun"),
  q("so-vs-such", 8, "A2", "gap", "The instructions were ___ clear.", "so", ["so", "such", "such a"], "Clear stands alone.", "So clear.", "so-adj"),

  q("so-neither", 1, "A2", "gap", "I like tea. ___ do I.", "So", ["Neither", "So", "Too"], "Agree with a positive.", "So do I.", "so-agree"),
  q("so-neither", 2, "A2", "gap", "I don't eat meat. ___ do I.", "Neither", ["So", "Neither", "Too"], "Agree with a negative.", "Neither do I.", "neither-agree"),
  q("so-neither", 3, "A2", "fix", "She can swim. Neither can I.", "She can swim. So can I.", ["She can swim. Neither can I.", "She can swim. So can I.", "She can swim. So I can."], "Positive statement.", "So + auxiliary + subject.", "so-agree"),
  q("so-neither", 4, "A2", "mcq", "Which agrees with a negative?", "I haven't finished. Neither have I.", ["I haven't finished. So have I.", "I haven't finished. Neither have I.", "I haven't finished. Neither I have."], "Haven't is negative.", "Neither have I.", "neither-agree"),
  q("so-neither", 5, "A2", "gap", "They're staying late. So ___ we.", "are", ["do", "are", "have"], "They're = they are.", "Match the auxiliary: so are we.", "so-agree"),
  q("so-neither", 6, "A2", "mcq", "Choose the word order.", "So does Ana.", ["So Ana does.", "So does Ana.", "So Ana do."], "Auxiliary before the subject.", "So does Ana.", "so-agree"),
  q("so-neither", 7, "A2", "fix", "We didn't book. So did they.", "We didn't book. Neither did they.", ["We didn't book. So did they.", "We didn't book. Neither did they.", "We didn't book. Neither they did."], "Didn't is negative.", "Neither did they.", "neither-agree"),
  q("so-neither", 8, "A2", "gap", "He won't join. Neither ___ I.", "will", ["do", "will", "won't"], "Won't = will not; keep will.", "Neither will I.", "neither-agree"),

  q("wish-if-only", 1, "B1", "gap", "I wish I ___ more time this week.", "had", ["have", "had", "would have"], "Unreal present.", "Wish + past: I wish I had.", "wish-past-present"),
  q("wish-if-only", 2, "B1", "gap", "I wish I ___ left earlier yesterday.", "had", ["have", "had", "would"], "Unreal past: past perfect.", "Wish + had + participle: had left.", "wish-past-perfect"),
  q("wish-if-only", 3, "B1", "fix", "I wish I would have a balcony now.", "I wish I had a balcony now.", ["I wish I would have a balcony now.", "I wish I had a balcony now.", "I wish I have a balcony now."], "Present you cannot change.", "Wish + past, not would have, for now.", "wish-past-present"),
  q("wish-if-only", 4, "B1", "mcq", "Which is a regret about the past?", "If only I had saved that file.", ["If only I had more files now.", "If only I had saved that file.", "If only I save that file."], "Saved = finished past.", "If only + past perfect.", "wish-past-perfect"),
  q("wish-if-only", 5, "B1", "gap", "If only this street ___ quieter.", "were", ["is", "were", "would be"], "Unreal present; were is the careful form.", "If only it were quieter.", "wish-past-present"),
  q("wish-if-only", 6, "B1", "mcq", "Choose the present-unreal pattern.", "I wish I knew her number.", ["I wish I know her number.", "I wish I knew her number.", "I wish I would knew her number."], "Now, but you don't know.", "Wish + past.", "wish-past-present"),
  q("wish-if-only", 7, "B1", "fix", "She wishes she went to the interview last Monday.", "She wishes she had gone to the interview last Monday.", ["She wishes she went to the interview last Monday.", "She wishes she had gone to the interview last Monday.", "She wishes she would go to the interview last Monday."], "Last Monday is finished.", "Wish + past perfect for a past regret.", "wish-past-perfect"),
  q("wish-if-only", 8, "B1", "gap", "I wish we ___ the earlier train. We missed the meeting.", "had caught", ["caught", "had caught", "would catch"], "The missed meeting is in the past.", "Had caught.", "wish-past-perfect"),

  q("causative", 1, "B1", "gap", "I had my car ___ last week.", "serviced", ["service", "serviced", "servicing"], "Someone else did it.", "Have + object + past participle.", "have-done"),
  q("causative", 2, "B1", "gap", "She got her hair ___ before the wedding.", "cut", ["cut", "cutting", "to cut"], "A hairdresser did it.", "Get + object + past participle.", "get-done"),
  q("causative", 3, "B1", "fix", "We had repaired the roof. (a company did it for us)", "We had the roof repaired.", ["We had repaired the roof.", "We had the roof repaired.", "We had the roof to repair."], "Object before the participle.", "Had the roof repaired.", "have-done"),
  q("causative", 4, "B1", "mcq", "Which means you arranged it?", "They had the locks changed.", ["They had changed the locks themselves.", "They had the locks changed.", "The locks changed them."], "Someone else changed the locks.", "Had the locks changed.", "have-done"),
  q("causative", 5, "B1", "gap", "I'm going to get this suit ___.", "cleaned", ["clean", "cleaned", "cleaning"], "A cleaner will do it.", "Get it cleaned.", "get-done"),
  q("causative", 6, "B1", "mcq", "Choose the causative order.", "have + object + past participle", ["have + past participle + object", "have + object + past participle", "have + to + object"], "Had my passport renewed.", "Object then participle.", "have-done"),
  q("causative", 7, "B1", "fix", "He got fix his laptop.", "He got his laptop fixed.", ["He got fix his laptop.", "He got his laptop fixed.", "He got his laptop to fixed."], "Get + object + participle.", "Got his laptop fixed.", "get-done"),
  q("causative", 8, "B1", "gap", "Did you have those photos ___?", "printed", ["print", "printed", "printing"], "A shop printed them.", "Have them printed.", "have-done"),

  q("subject-verb-agreement", 1, "A2", "gap", "Everyone ___ ready.", "is", ["are", "is", "be"], "Everyone is singular.", "Everyone is.", "everyone-singular"),
  q("subject-verb-agreement", 2, "A2", "gap", "The news ___ on at 6.", "is", ["are", "is", "be"], "News is singular here.", "The news is.", "news-singular"),
  q("subject-verb-agreement", 3, "A2", "fix", "Each of the rooms have a desk.", "Each of the rooms has a desk.", ["Each of the rooms have a desk.", "Each of the rooms has a desk.", "Each of the rooms having a desk."], "Each is singular.", "Each … has.", "everyone-singular"),
  q("subject-verb-agreement", 4, "A2", "mcq", "Which is correct?", "The chairs are in the corridor.", ["The chairs is in the corridor.", "The chairs are in the corridor.", "The chairs be in the corridor."], "Chairs is plural.", "Plural subject + are.", "plural-plural"),
  q("subject-verb-agreement", 5, "A2", "gap", "My colleagues ___ on the same floor.", "work", ["works", "work", "working"], "Colleagues is plural.", "They work.", "plural-plural"),
  q("subject-verb-agreement", 6, "A2", "mcq", "Choose the singular subject.", "The furniture looks new.", ["The furniture look new.", "The furniture looks new.", "The furnitures look new."], "Furniture is uncountable/singular.", "Looks.", "news-singular"),
  q("subject-verb-agreement", 7, "A2", "fix", "There is two printers in the office.", "There are two printers in the office.", ["There is two printers in the office.", "There are two printers in the office.", "There be two printers in the office."], "Two printers = plural.", "There are + plural.", "plural-plural"),
  q("subject-verb-agreement", 8, "A2", "gap", "Nobody ___ the spare key.", "has", ["have", "has", "having"], "Nobody is singular.", "Nobody has.", "everyone-singular"),

  q("tricky-uncountables", 1, "A2", "gap", "She gave me some ___.", "advice", ["advices", "advice", "an advice"], "No plural here.", "Some advice.", "no-plural"),
  q("tricky-uncountables", 2, "A2", "gap", "I need a piece of ___.", "information", ["informations", "information", "an information"], "Use piece of.", "A piece of information.", "piece-of"),
  q("tricky-uncountables", 3, "A2", "fix", "We bought two furnitures.", "We bought two pieces of furniture.", ["We bought two furnitures.", "We bought two pieces of furniture.", "We bought two furniture."], "Furniture has no plural.", "Pieces of furniture.", "piece-of"),
  q("tricky-uncountables", 4, "A2", "mcq", "Which is correct?", "Is there any news?", ["Are there any news?", "Is there any news?", "Is there a news?"], "News is uncountable.", "Any news; is, not are.", "no-plural"),
  q("tricky-uncountables", 5, "A2", "gap", "Leave your ___ at the desk.", "luggage", ["luggages", "luggage", "a luggage"], "No plural.", "Luggage, not luggages.", "no-plural"),
  q("tricky-uncountables", 6, "A2", "mcq", "Choose the natural phrase.", "some useful advice", ["an useful advice", "some useful advice", "some useful advices"], "Some + uncountable.", "Some advice.", "no-plural"),
  q("tricky-uncountables", 7, "A2", "fix", "Can you give me an information?", "Can you give me some information?", ["Can you give me an information?", "Can you give me some information?", "Can you give me informations?"], "No a/an.", "Some information.", "piece-of"),
  q("tricky-uncountables", 8, "A2", "gap", "Two ___ of luggage are missing.", "pieces", ["piece", "pieces", "furnitures"], "Count with pieces.", "Two pieces of luggage.", "piece-of"),

  q("by-vs-until", 1, "B1", "gap", "Please send the invoice ___ Friday.", "by", ["until", "by", "during"], "A deadline: not later than.", "By Friday.", "by-deadline"),
  q("by-vs-until", 2, "B1", "gap", "The shop is open ___ 8.", "until", ["by", "until", "at"], "It continues up to that time.", "Open until 8.", "until-continue"),
  q("by-vs-until", 3, "B1", "fix", "Stay here by I call you.", "Stay here until I call you.", ["Stay here by I call you.", "Stay here until I call you.", "Stay here by I will call you."], "Continuing, then a stop.", "Until I call you.", "until-continue"),
  q("by-vs-until", 4, "B1", "mcq", "Which is a deadline?", "Have it ready by noon.", ["Have it ready until noon.", "Have it ready by noon.", "Have it ready during noon."], "Not later than noon.", "By noon.", "by-deadline"),
  q("by-vs-until", 5, "B1", "gap", "I'll wait ___ the printer finishes.", "until", ["by", "until", "to"], "Waiting continues.", "Until it finishes.", "until-continue"),
  q("by-vs-until", 6, "B1", "mcq", "Applications close ___ 15 March.", "by", ["until", "by", "while"], "Last moment to submit.", "By 15 March.", "by-deadline"),
  q("by-vs-until", 7, "B1", "fix", "The museum stays open by 6 every day. (it continues)", "The museum stays open until 6 every day.", ["The museum stays open by 6 every day.", "The museum stays open until 6 every day.", "The museum stays open by 6 o'clock deadline."], "How long it continues.", "Until 6.", "until-continue"),
  q("by-vs-until", 8, "B1", "gap", "Finish the slides ___ the meeting starts.", "by", ["until", "by", "during"], "Before that moment.", "By the time it starts.", "by-deadline"),

  q("in-time-vs-on-time", 1, "B1", "gap", "The flight left ___ time. 14:00, as scheduled.", "on", ["in", "on", "at"], "At the scheduled moment.", "On time.", "on-time-schedule"),
  q("in-time-vs-on-time", 2, "B1", "gap", "We arrived ___ time to board.", "in", ["on", "in", "at"], "Not too late; minutes to spare.", "In time to + verb.", "in-time-spare"),
  q("in-time-vs-on-time", 3, "B1", "fix", "She got to the pharmacy on time to pick up the prescription before it closed. (spare minutes)", "She got to the pharmacy in time to pick up the prescription before it closed.", ["She got to the pharmacy on time to pick up the prescription before it closed.", "She got to the pharmacy in time to pick up the prescription before it closed.", "She got to the pharmacy at time to pick up the prescription."], "Purpose: not too late.", "In time to pick up.", "in-time-spare"),
  q("in-time-vs-on-time", 4, "B1", "mcq", "Which matches a timetable?", "The 7:15 train is usually on time.", ["The 7:15 train is usually in time.", "The 7:15 train is usually on time.", "The 7:15 train is usually at time."], "Scheduled moment.", "On time.", "on-time-schedule"),
  q("in-time-vs-on-time", 5, "B1", "gap", "Will you be ___ time for the start?", "in", ["on", "in", "by"], "Not too late for the beginning.", "In time for + noun.", "in-time-spare"),
  q("in-time-vs-on-time", 6, "B1", "mcq", "The meeting started at 10:00 exactly. Everyone arrived ___.", "on time", ["in time", "on time", "in the time"], "Exactly as scheduled.", "On time.", "on-time-schedule"),
  q("in-time-vs-on-time", 7, "B1", "fix", "Call me on time if the parcel arrives before I leave.", "Call me in time if the parcel arrives before I leave.", ["Call me on time if the parcel arrives before I leave.", "Call me in time if the parcel arrives before I leave.", "Call me at time if the parcel arrives."], "Soon enough, not a timetable.", "In time.", "in-time-spare"),
  q("in-time-vs-on-time", 8, "B1", "gap", "The 9:02 departed at 9:02, as scheduled. It left ___.", "on time", ["in time", "on time", "in the time"], "At the scheduled moment.", "Left on time.", "on-time-schedule"),

  q("at-the-end-vs-in-the-end", 1, "B1", "gap", "There's a bakery ___ the end of this street.", "at", ["in", "at", "on"], "Position: end of + noun.", "At the end of the street.", "at-end-of"),
  q("at-the-end-vs-in-the-end", 2, "B1", "gap", "___ the end we took a taxi.", "In", ["At", "In", "On"], "Finally, after a process.", "In the end = finally.", "in-the-end-finally"),
  q("at-the-end-vs-in-the-end", 3, "B1", "fix", "At the end, after three wrong turns, we found the office.", "In the end, after three wrong turns, we found the office.", ["At the end, after three wrong turns, we found the office.", "In the end, after three wrong turns, we found the office.", "In the end of, after three wrong turns, we found the office."], "Finally.", "In the end.", "in-the-end-finally"),
  q("at-the-end-vs-in-the-end", 4, "B1", "mcq", "Which is a place in the film?", "The credits are at the end of the film.", ["The credits are in the end of the film.", "The credits are at the end of the film.", "The credits are in the end the film."], "At the end of + noun.", "At the end of the film.", "at-end-of"),
  q("at-the-end-vs-in-the-end", 5, "B1", "gap", "Sit ___ the end of the row.", "at", ["in", "at", "on"], "A position.", "At the end of the row.", "at-end-of"),
  q("at-the-end-vs-in-the-end", 6, "B1", "mcq", "They argued for an hour. ___ they agreed.", "In the end", ["At the end", "In the end", "At the end of"], "After a process.", "In the end they agreed.", "in-the-end-finally"),
  q("at-the-end-vs-in-the-end", 7, "B1", "fix", "In the end of the corridor, turn left.", "At the end of the corridor, turn left.", ["In the end of the corridor, turn left.", "At the end of the corridor, turn left.", "In the end the corridor, turn left."], "Place + of + noun.", "At the end of.", "at-end-of"),
  q("at-the-end-vs-in-the-end", 8, "B1", "gap", "We almost cancelled. ___ the end the client signed.", "In", ["At", "In", "By"], "Finally.", "In the end.", "in-the-end-finally"),

  q("during-vs-while", 1, "A2", "gap", "Please don't call ___ the meeting.", "during", ["while", "during", "until"], "Meeting is a noun.", "During + noun.", "during-noun"),
  q("during-vs-while", 2, "A2", "gap", "___ we were talking, the printer jammed.", "While", ["During", "While", "By"], "We were talking is a clause.", "While + clause.", "while-clause"),
  q("during-vs-while", 3, "A2", "fix", "I took notes during she presented.", "I took notes while she presented.", ["I took notes during she presented.", "I took notes while she presented.", "I took notes during presented."], "She presented is a clause.", "While she presented.", "while-clause"),
  q("during-vs-while", 4, "A2", "mcq", "Which is correct?", "No phones during the flight.", ["No phones while the flight.", "No phones during the flight.", "No phones during we fly."], "Flight is a noun.", "During the flight.", "during-noun"),
  q("during-vs-while", 5, "A2", "gap", "He fell asleep ___ the film.", "during", ["while", "during", "until"], "Film is a noun.", "During the film.", "during-noun"),
  q("during-vs-while", 6, "A2", "mcq", "Choose the clause pattern.", "While I was cooking, the doorbell rang.", ["During I was cooking, the doorbell rang.", "While I was cooking, the doorbell rang.", "During cooking I, the doorbell rang."], "I was cooking = clause.", "While + clause.", "while-clause"),
  q("during-vs-while", 7, "A2", "fix", "Don't interrupt while the announcement.", "Don't interrupt during the announcement.", ["Don't interrupt while the announcement.", "Don't interrupt during the announcement.", "Don't interrupt while announcement."], "Announcement is a noun.", "During the announcement.", "during-noun"),
  q("during-vs-while", 8, "A2", "gap", "___ you're on hold, I'll find the file.", "While", ["During", "While", "Until"], "You're on hold is a clause.", "While you're on hold.", "while-clause"),

  q("who-vs-whom", 1, "B1", "gap", "___ called the office?", "Who", ["Whom", "Who", "Which"], "Subject of called.", "Who called?", "who-subject"),
  q("who-vs-whom", 2, "B1", "gap", "___ did you invite?", "Whom", ["Who", "Whom", "Which"], "Object of invite.", "Whom did you invite?", "whom-object"),
  q("who-vs-whom", 3, "B1", "fix", "Whom left this bag?", "Who left this bag?", ["Whom left this bag?", "Who left this bag?", "Whom did left this bag?"], "Left needs a subject.", "Who left.", "who-subject"),
  q("who-vs-whom", 4, "B1", "mcq", "Which is the careful object form?", "To whom should I send this?", ["To who should I send this?", "To whom should I send this?", "Whom should send this?"], "After a preposition.", "To whom.", "whom-object"),
  q("who-vs-whom", 5, "B1", "gap", "___ is waiting at reception?", "Who", ["Whom", "Who", "Whose"], "Subject of is waiting.", "Who is waiting?", "who-subject"),
  q("who-vs-whom", 6, "B1", "mcq", "Choose the object question.", "Whom did they hire?", ["Whom hired they?", "Whom did they hire?", "Who did hire they?"], "They hired someone.", "Whom did they hire?", "whom-object"),
  q("who-vs-whom", 7, "B1", "fix", "Who did you give the keys? (careful form, missing to)", "To whom did you give the keys?", ["Who did you give the keys?", "To whom did you give the keys?", "Whom did give you the keys?"], "Object of to.", "To whom.", "whom-object"),
  q("who-vs-whom", 8, "B1", "gap", "___ should we thank for the booking?", "Whom", ["Who", "Whom", "Which"], "Object of thank.", "Whom should we thank?", "whom-object"),

  q("like-vs-as", 1, "B1", "gap", "She sings ___ her mother.", "like", ["as", "like", "as if a"], "Similar to a person; + noun.", "Like + noun.", "like-similar"),
  q("like-vs-as", 2, "B1", "gap", "She works ___ a nurse.", "as", ["like", "as", "as like"], "That's her job / role.", "As a nurse.", "as-role"),
  q("like-vs-as", 3, "B1", "fix", "Do it like I showed you.", "Do it as I showed you.", ["Do it like I showed you.", "Do it as I showed you.", "Do it as like I showed you."], "As + clause.", "As I showed you.", "as-role"),
  q("like-vs-as", 4, "B1", "mcq", "Which means similar to?", "This tea tastes like the one in Porto.", ["This tea tastes as the one in Porto.", "This tea tastes like the one in Porto.", "This tea tastes as a the one in Porto."], "Like + noun phrase.", "Tastes like.", "like-similar"),
  q("like-vs-as", 5, "B1", "gap", "___ a manager, she signs the invoices.", "As", ["Like", "As", "Alike"], "In that role.", "As a manager.", "as-role"),
  q("like-vs-as", 6, "B1", "mcq", "Choose similarity, not the job.", "He cooks like a chef, but he works in IT.", ["He cooks as a chef, but he works in IT.", "He cooks like a chef, but he works in IT.", "He cooks as like a chef."], "Similar style, not his job.", "Like a chef.", "like-similar"),
  q("like-vs-as", 7, "B1", "fix", "She was hired like a translator.", "She was hired as a translator.", ["She was hired like a translator.", "She was hired as a translator.", "She was hired as like a translator."], "That's the role.", "Hired as.", "as-role"),
  q("like-vs-as", 8, "B1", "gap", "Your bag looks ___ mine.", "like", ["as", "like", "as a"], "Similar to.", "Looks like mine.", "like-similar"),

  q("bring-vs-take", 1, "A2", "gap", "I'm here. Please ___ the files to my desk.", "bring", ["take", "bring", "borrow"], "Towards the speaker.", "Bring here.", "bring-here"),
  q("bring-vs-take", 2, "A2", "gap", "It's raining. ___ an umbrella with you.", "Take", ["Bring", "Take", "Carry to me"], "Away from here, with you.", "Take with you.", "take-away"),
  q("bring-vs-take", 3, "A2", "fix", "I'll bring this parcel to the post office on my way home. (I'm leaving this room)", "I'll take this parcel to the post office on my way home.", ["I'll bring this parcel to the post office on my way home.", "I'll take this parcel to the post office on my way home.", "I'll borrow this parcel to the post office."], "Away from here.", "Take it there.", "take-away"),
  q("bring-vs-take", 4, "A2", "mcq", "A guest is coming to your flat. You say:", "Bring a cake if you can.", ["Take a cake if you can.", "Bring a cake if you can.", "Lend a cake if you can."], "Towards your place.", "Bring.", "bring-here"),
  q("bring-vs-take", 5, "A2", "gap", "Don't forget to ___ your badge when you leave.", "take", ["bring", "take", "lend"], "Leaving this place.", "Take it with you.", "take-away"),
  q("bring-vs-take", 6, "A2", "mcq", "You're on a video call from home. A colleague should come to the office with the contract. You say:", "Please take the contract to the office.", ["Please bring the contract to the office.", "Please take the contract to the office.", "Please borrow the contract to the office."], "The office is not where you are.", "Take it to the office.", "take-away"),
  q("bring-vs-take", 7, "A2", "fix", "When you come to dinner, take a bottle. (towards the host)", "When you come to dinner, bring a bottle.", ["When you come to dinner, take a bottle.", "When you come to dinner, bring a bottle.", "When you come to dinner, lend a bottle."], "Towards the dinner.", "Bring a bottle.", "bring-here"),
  q("bring-vs-take", 8, "A2", "gap", "Can you ___ me that stapler? It's on your table; I'm at mine.", "bring", ["take", "bring", "lend"], "Towards me.", "Bring me that stapler.", "bring-here"),

  q("borrow-vs-lend", 1, "A2", "gap", "Can I ___ your charger?", "borrow", ["lend", "borrow", "take to"], "You receive it.", "Borrow from someone.", "borrow-from"),
  q("borrow-vs-lend", 2, "A2", "gap", "Ana ___ me a charger.", "lent", ["borrowed", "lent", "brought"], "She gave it.", "Lend to someone; past lent.", "lend-to"),
  q("borrow-vs-lend", 3, "A2", "fix", "Can you borrow me a pen?", "Can you lend me a pen?", ["Can you borrow me a pen?", "Can you lend me a pen?", "Can you borrow a pen me?"], "You want them to give.", "Lend me.", "lend-to"),
  q("borrow-vs-lend", 4, "A2", "mcq", "Which is correct?", "I borrowed a bike from Jo.", ["I lent a bike from Jo.", "I borrowed a bike from Jo.", "I borrowed Jo a bike."], "You received it from Jo.", "Borrow from.", "borrow-from"),
  q("borrow-vs-lend", 5, "A2", "gap", "Banks ___ money to small firms.", "lend", ["borrow", "lend", "bring"], "Banks give money.", "Lend to.", "lend-to"),
  q("borrow-vs-lend", 6, "A2", "mcq", "The owner of the umbrella ___.", "lends it", ["borrows it", "lends it", "borrows you it"], "Owner gives.", "Lends.", "lend-to"),
  q("borrow-vs-lend", 7, "A2", "fix", "I lent a jacket from the cloakroom.", "I borrowed a jacket from the cloakroom.", ["I lent a jacket from the cloakroom.", "I borrowed a jacket from the cloakroom.", "I lent the cloakroom a jacket from."], "You received it.", "Borrowed from.", "borrow-from"),
  q("borrow-vs-lend", 8, "A2", "gap", "She won't ___ her laptop to anyone.", "lend", ["borrow", "lend", "take"], "She won't give it.", "Won't lend to anyone.", "lend-to"),

  q("see-watch-look", 1, "A2", "gap", "___ at this chart for a second.", "Look", ["See", "Watch", "Look"], "Direct your eyes, short.", "Look at.", "look-at"),
  q("see-watch-look", 2, "A2", "gap", "We ___ a series last night — all eight episodes.", "watched", ["saw", "watched", "looked"], "Look for a period at something that changes.", "Watch a series.", "watch-period"),
  q("see-watch-look", 3, "A2", "fix", "I looked a bird in the car park.", "I saw a bird in the car park.", ["I looked a bird in the car park.", "I saw a bird in the car park.", "I looked at a bird in the car park without noticing it."], "Notice, without trying.", "Saw a bird.", "see-notice"),
  q("see-watch-look", 4, "A2", "mcq", "Which needs at?", "Look at the screen.", ["See at the screen.", "Look at the screen.", "Watch at the screen."], "Look + at.", "Look at.", "look-at"),
  q("see-watch-look", 5, "A2", "gap", "Did you ___ my keys on the counter?", "see", ["watch", "see", "look"], "Notice, not a long activity.", "See my keys.", "see-notice"),
  q("see-watch-look", 6, "A2", "mcq", "Choose the long activity.", "They watched the match in a cafe.", ["They saw the match in a cafe for ninety minutes as a glance.", "They watched the match in a cafe.", "They looked the match in a cafe."], "A match unfolds over time.", "Watched the match.", "watch-period"),
  q("see-watch-look", 7, "A2", "fix", "Watch that sign. You need the street name now.", "Look at that sign.", ["Watch that sign.", "Look at that sign.", "See at that sign."], "Direct your eyes now, not a show.", "Look at the sign.", "look-at"),
  q("see-watch-look", 8, "A2", "gap", "I can ___ the river from this window.", "see", ["watch", "see", "look"], "It's just there; you notice it.", "Can see the river.", "see-notice"),

  q("hear-vs-listen", 1, "A2", "gap", "I ___ a bang in the street.", "heard", ["listened", "heard", "listened to"], "The sound reached you.", "Heard a bang.", "hear-sound"),
  q("hear-vs-listen", 2, "A2", "gap", "___ to this podcast on the train.", "Listen", ["Hear", "Listen", "Hear at"], "Pay attention.", "Listen to.", "listen-to"),
  q("hear-vs-listen", 3, "A2", "fix", "Please hear to the announcement.", "Please listen to the announcement.", ["Please hear to the announcement.", "Please listen to the announcement.", "Please listen the announcement."], "Pay attention + to.", "Listen to.", "listen-to"),
  q("hear-vs-listen", 4, "A2", "mcq", "Which is effortless sound?", "Did you hear the doorbell?", ["Did you listen the doorbell?", "Did you hear the doorbell?", "Did you listen to hear the doorbell as a bang?"], "It reached you.", "Hear the doorbell.", "hear-sound"),
  q("hear-vs-listen", 5, "A2", "gap", "Sorry, I wasn't ___. Can you repeat that?", "listening", ["hearing", "listening", "listen"], "Not paying attention.", "Wasn't listening.", "listen-to"),
  q("hear-vs-listen", 6, "A2", "mcq", "Choose the locked pair.", "listen to music", ["hear to music", "listen to music", "listen music"], "Listen + to.", "Listen to music.", "listen-to"),
  q("hear-vs-listen", 7, "A2", "fix", "I listened a motorbike and then I saw it.", "I heard a motorbike and then I saw it.", ["I listened a motorbike and then I saw it.", "I heard a motorbike and then I saw it.", "I listened to a motorbike and then I saw it."], "Sound reached you first.", "Heard a motorbike.", "hear-sound"),
  q("hear-vs-listen", 8, "A2", "gap", "Can you ___ me from the kitchen?", "hear", ["listen", "hear", "listen to"], "Does the sound reach you?", "Can you hear me?", "hear-sound"),

  q("phrasal-verbs", 1, "A2", "gap", "I usually ___ up at 6:30.", "get", ["take", "get", "put"], "Leave bed.", "Get up = leave bed.", "particle-meaning"),
  q("phrasal-verbs", 2, "A2", "gap", "Can you look ___ my plants while I'm away?", "after", ["for", "after", "up"], "Care for them.", "Look after = take care of.", "particle-meaning"),
  q("phrasal-verbs", 3, "A2", "fix", "She gave up to sugar last year.", "She gave up sugar last year.", ["She gave up to sugar last year.", "She gave up sugar last year.", "She gave up of sugar last year."], "Stop a habit.", "Give up + noun.", "particle-meaning"),
  q("phrasal-verbs", 4, "A2", "mcq", "Find the meaning of find out.", "learn information", ["learn information", "stand after a search", "stop a machine"], "Find out = learn information.", "Find out.", "particle-meaning"),
  q("phrasal-verbs", 5, "A2", "gap", "Don't put ___ the dentist appointment again.", "off", ["on", "off", "up"], "Delay it.", "Put off = postpone.", "particle-meaning"),
  q("phrasal-verbs", 6, "A2", "mcq", "The plane is leaving the ground. It is ___.", "taking off", ["getting off", "taking off", "taking out"], "Take off (plane).", "Taking off.", "particle-meaning"),
  q("phrasal-verbs", 7, "A2", "fix", "Please turn on the printer off when you leave. (stop it)", "Please turn off the printer when you leave.", ["Please turn on the printer off when you leave.", "Please turn off the printer when you leave.", "Please turn the printer on off when you leave."], "Stop the machine.", "Turn off.", "particle-meaning"),
  q("phrasal-verbs", 8, "A2", "gap", "If you don't know the word, look it ___.", "up", ["after", "for", "up"], "Check in a dictionary.", "Look up a word.", "particle-meaning"),

  q("so-that-in-order-to", 1, "B1", "gap", "She left early in order ___ catch the train.", "to", ["that", "to", "for"], "In order to + base.", "In order to catch.", "in-order-to"),
  q("so-that-in-order-to", 2, "B1", "gap", "She left early so that she ___ catch the train.", "could", ["to", "could", "catch"], "So that + clause.", "So that she could catch.", "so-that-clause"),
  q("so-that-in-order-to", 3, "B1", "fix", "I wrote it down in order that remember.", "I wrote it down in order to remember.", ["I wrote it down in order that remember.", "I wrote it down in order to remember.", "I wrote it down so that remember."], "In order to + base.", "In order to remember.", "in-order-to"),
  q("so-that-in-order-to", 4, "B1", "mcq", "Which is a clause of purpose?", "Speak slowly so that everyone can follow.", ["Speak slowly in order that everyone follow.", "Speak slowly so that everyone can follow.", "Speak slowly in order everyone can follow."], "So that + subject + verb.", "So that everyone can follow.", "so-that-clause"),
  q("so-that-in-order-to", 5, "B1", "gap", "He whispered ___ that the baby wouldn't wake.", "so", ["in order", "so", "because"], "So that + clause.", "So that the baby wouldn't wake.", "so-that-clause"),
  q("so-that-in-order-to", 6, "B1", "mcq", "Choose the to-pattern.", "I saved the file in order to send it later.", ["I saved the file so that send it later.", "I saved the file in order to send it later.", "I saved the file in order sending it later."], "In order to + base.", "In order to send.", "in-order-to"),
  q("so-that-in-order-to", 7, "B1", "fix", "We booked a taxi so that arrive on time.", "We booked a taxi so that we would arrive on time.", ["We booked a taxi so that arrive on time.", "We booked a taxi so that we would arrive on time.", "We booked a taxi in order that arrive on time."], "So that needs a subject.", "So that we would arrive.", "so-that-clause"),
  q("so-that-in-order-to", 8, "B1", "gap", "Wear a badge in order ___ be recognised.", "to", ["that", "to", "for"], "In order to + base.", "In order to be recognised.", "in-order-to"),

  q("would-rather-had-better", 1, "B1", "gap", "I'd rather ___ than drive.", "walk", ["to walk", "walk", "walking"], "Rather + base.", "I'd rather walk.", "rather-prefer"),
  q("would-rather-had-better", 2, "B1", "gap", "You'd better ___ now or you'll miss it.", "leave", ["to leave", "leave", "leaving"], "Warning + base.", "Had better leave.", "had-better-warn"),
  q("would-rather-had-better", 3, "B1", "fix", "I'd rather to sit by the window.", "I'd rather sit by the window.", ["I'd rather to sit by the window.", "I'd rather sit by the window.", "I'd rather sitting by the window."], "No to after rather.", "Rather sit.", "rather-prefer"),
  q("would-rather-had-better", 4, "B1", "mcq", "Which is a warning?", "You'd better save that file.", ["I'd rather save that file.", "You'd better save that file.", "You should to save that file."], "Risk if you don't.", "Had better.", "had-better-warn"),
  q("would-rather-had-better", 5, "B1", "gap", "I'd rather walk ___ drive.", "than", ["than", "then", "to"], "Preference between two actions.", "Rather A than B.", "rather-prefer"),
  q("would-rather-had-better", 6, "B1", "mcq", "Choose preference, not a warning.", "I'd rather work from home on Fridays.", ["You'd better work from home on Fridays.", "I'd rather work from home on Fridays.", "I'd rather to work from home on Fridays."], "Want, not must.", "Would rather.", "rather-prefer"),
  q("would-rather-had-better", 7, "B1", "fix", "You had better to charge your phone.", "You had better charge your phone.", ["You had better to charge your phone.", "You had better charge your phone.", "You had better charging your phone."], "Base after had better.", "Had better charge.", "had-better-warn"),
  q("would-rather-had-better", 8, "B1", "gap", "We'd better not ___ the last train.", "miss", ["to miss", "miss", "missing"], "Negative warning: had better not + base.", "Had better not miss.", "had-better-warn"),

  q("stop-remember-gerund-infinitive", 1, "B1", "gap", "He stopped ___ last year. No more cigarettes.", "smoking", ["to smoke", "smoking", "smoke"], "Quit the habit.", "Stop + -ing = quit.", "stop-ing-quit"),
  q("stop-remember-gerund-infinitive", 2, "B1", "gap", "Remember ___ the door when you leave.", "to lock", ["locking", "to lock", "lock"], "Don't forget later.", "Remember to + future task.", "remember-to"),
  q("stop-remember-gerund-infinitive", 3, "B1", "fix", "I stopped smoking a cigarette outside, then I went back in. (paused in order to)", "I stopped to smoke a cigarette outside, then I went back in.", ["I stopped smoking a cigarette outside, then I went back in.", "I stopped to smoke a cigarette outside, then I went back in.", "I stopped smoke a cigarette outside, then I went back in."], "Paused another action.", "Stop to + purpose.", "stop-to-purpose"),
  q("stop-remember-gerund-infinitive", 4, "B1", "mcq", "Which is a memory of the past?", "I remember meeting her in Lisbon.", ["I remember to meet her in Lisbon.", "I remember meeting her in Lisbon.", "I remember meet her in Lisbon."], "It already happened.", "Remember + -ing.", "remember-ing"),
  q("stop-remember-gerund-infinitive", 5, "B1", "gap", "Did you remember ___ the attachment?", "to add", ["adding", "to add", "add"], "A task you must not forget.", "Remember to add.", "remember-to"),
  q("stop-remember-gerund-infinitive", 6, "B1", "mcq", "Choose quit, not pause.", "She stopped checking her phone at dinner.", ["She stopped to check her phone at dinner.", "She stopped checking her phone at dinner.", "She stopped check her phone at dinner."], "The habit ended (at dinner).", "Stop checking.", "stop-ing-quit"),
  q("stop-remember-gerund-infinitive", 7, "B1", "fix", "Remember locking the office if you mean don't forget tonight.", "Remember to lock the office.", ["Remember locking the office.", "Remember to lock the office.", "Remember lock the office."], "Future task.", "Remember to lock.", "remember-to"),
  q("stop-remember-gerund-infinitive", 8, "B1", "gap", "I remember ___ the window before we left. I'm sure I did it.", "closing", ["to close", "closing", "close"], "A memory.", "Remember closing.", "remember-ing"),

  q("who-which-that", 1, "A2", "gap", "This is the neighbour ___ waters our plants.", "who", ["which", "who", "where"], "A person.", "Who for people.", "who-people"),
  q("who-which-that", 2, "A2", "gap", "The files ___ I sent are in your inbox.", "that", ["who", "that", "where"], "Things; identifying.", "That/which for things.", "which-things"),
  q("who-which-that", 3, "A2", "fix", "The printer who is jammed is on floor 2.", "The printer which is jammed is on floor 2.", ["The printer who is jammed is on floor 2.", "The printer which is jammed is on floor 2.", "The printer who jammed is on floor 2."], "Printer is a thing.", "Which/that, not who.", "which-things"),
  q("who-which-that", 4, "A2", "mcq", "After a comma, extra information about a thing:", "The office, which faces the park, is cold.", ["The office, that faces the park, is cold.", "The office, which faces the park, is cold.", "The office, who faces the park, is cold."], "Which, not that, after a comma.", "Which after a comma.", "which-things"),
  q("who-which-that", 5, "A2", "gap", "Is this the app ___ you mentioned?", "that", ["who", "that", "where"], "App is a thing; identifying.", "That you mentioned.", "that-identifying"),
  q("who-which-that", 6, "A2", "mcq", "That can identify people or things. Choose a thing clause.", "The bag that is by the door is mine.", ["The bag who is by the door is mine.", "The bag that is by the door is mine.", "The bag where is by the door is mine."], "Bag = thing.", "That is by the door.", "that-identifying"),
  q("who-which-that", 7, "A2", "fix", "She's the engineer which designed it.", "She's the engineer who designed it.", ["She's the engineer which designed it.", "She's the engineer who designed it.", "She's the engineer who design it."], "Engineer is a person.", "Who, not which.", "who-people"),
  q("who-which-that", 8, "A2", "gap", "This is the form ___ you need to sign.", "that", ["who", "that", "where"], "Form is a thing.", "That you need to sign.", "that-identifying"),

  q("first-vs-second-conditional", 1, "B1", "gap", "If it rains tomorrow, we ___ stay in. Real plan.", "will", ["would", "will", "would have"], "Possible future.", "First: if + present, will.", "first-real"),
  q("first-vs-second-conditional", 2, "B1", "gap", "If I ___ the lottery, I would travel. Unreal.", "won", ["win", "won", "would win"], "Not a real ticket plan.", "Second: if + past, would.", "second-unreal"),
  q("first-vs-second-conditional", 3, "B1", "fix", "If I win the lottery, I would buy a flat.", "If I won the lottery, I would buy a flat.", ["If I win the lottery, I would buy a flat.", "If I won the lottery, I would buy a flat.", "If I will win the lottery, I would buy a flat."], "Unreal money.", "If + past, would.", "second-unreal"),
  q("first-vs-second-conditional", 4, "B1", "mcq", "The forecast is 80% rain. Choose the real future.", "If it rains, I'll take a taxi.", ["If it rained, I would take a taxi.", "If it rains, I'll take a taxi.", "If it will rain, I take a taxi."], "Likely.", "First conditional.", "first-real"),
  q("first-vs-second-conditional", 5, "B1", "gap", "If she ___ more hours, she would finish tonight. She doesn't have them.", "had", ["has", "had", "will have"], "Unreal now.", "If she had, she would.", "second-unreal"),
  q("first-vs-second-conditional", 6, "B1", "mcq", "You might see Ana this afternoon. Choose the real one.", "If I see Ana, I'll give her the keys.", ["If I saw Ana, I would give her the keys.", "If I see Ana, I'll give her the keys.", "If I would see Ana, I give her the keys."], "Possible this afternoon.", "If I see, I'll give.", "first-real"),
  q("first-vs-second-conditional", 7, "B1", "fix", "If I have a spare room, I would put you up. (I don't have one)", "If I had a spare room, I would put you up.", ["If I have a spare room, I would put you up.", "If I had a spare room, I would put you up.", "If I will have a spare room, I would put you up."], "Unreal now.", "If I had, I would.", "second-unreal"),
  q("first-vs-second-conditional", 8, "B1", "gap", "If the client ___ the brief today, we'll start on Monday. Possible.", "sends", ["sent", "sends", "would send"], "Real possible future.", "If + present, will.", "first-real"),

  q("present-perfect-vs-present-perfect-continuous", 1, "B1", "gap", "I have ___ three emails. Here's the last one.", "written", ["been writing", "written", "wrote"], "A finished count / result.", "Have written = result.", "pp-result"),
  q("present-perfect-vs-present-perfect-continuous", 2, "B1", "gap", "I have been ___ all morning.", "writing", ["written", "writing", "write"], "The activity over time.", "Have been writing.", "ppc-activity"),
  q("present-perfect-vs-present-perfect-continuous", 3, "B1", "fix", "She has written all morning. (you mean the activity, not a count)", "She has been writing all morning.", ["She has written all morning.", "She has been writing all morning.", "She has been written all morning."], "Duration of the activity.", "Has been writing.", "ppc-activity"),
  q("present-perfect-vs-present-perfect-continuous", 4, "B1", "mcq", "Which stresses a result you can see?", "He has painted the door. It's dry now.", ["He has been painting the door all morning.", "He has painted the door. It's dry now.", "He has been painted the door."], "Finished result.", "Has painted.", "pp-result"),
  q("present-perfect-vs-present-perfect-continuous", 5, "B1", "gap", "They have been ___ in that cafe since 8.", "sitting", ["sat", "sitting", "sit"], "Activity continuing.", "Have been sitting.", "ppc-activity"),
  q("present-perfect-vs-present-perfect-continuous", 6, "B1", "mcq", "Choose the finished number.", "We have booked two rooms.", ["We have been booking two rooms all morning as a number.", "We have booked two rooms.", "We have been booked two rooms."], "Two rooms = result.", "Have booked.", "pp-result"),
  q("present-perfect-vs-present-perfect-continuous", 7, "B1", "fix", "I have been broken three cups this week. (count/result)", "I have broken three cups this week.", ["I have been broken three cups this week.", "I have broken three cups this week.", "I have been breaking three cups as a finished total."], "A countable result.", "Have broken.", "pp-result"),
  q("present-perfect-vs-present-perfect-continuous", 8, "B1", "gap", "You're red. Have you been ___?", "running", ["run", "running", "ran"], "Activity that explains now.", "Have you been running?", "ppc-activity"),

  q("reported-questions", 1, "B1", "gap", "She asked ___ I was ready.", "if", ["do", "if", "did"], "Yes/no report.", "Asked if + statement order.", "if-whether"),
  q("reported-questions", 2, "B1", "gap", "She asked where I ___.", "lived", ["did live", "lived", "live I"], "Wh- + statement order; tense back.", "Asked where I lived.", "statement-order"),
  q("reported-questions", 3, "B1", "fix", "He asked where did I park.", "He asked where I parked.", ["He asked where did I park.", "He asked where I parked.", "He asked where did I parked."], "No did in the report.", "Where I parked.", "statement-order"),
  q("reported-questions", 4, "B1", "mcq", "Which reports a yes/no question?", "They asked whether the shop was open.", ["They asked was the shop open.", "They asked whether the shop was open.", "They asked whether was the shop open."], "If/whether + statement.", "Whether the shop was open.", "if-whether"),
  q("reported-questions", 5, "B1", "gap", "I asked what time the train ___.", "left", ["did leave", "left", "does leave"], "Statement order; past in the report.", "What time the train left.", "statement-order"),
  q("reported-questions", 6, "B1", "mcq", "Choose statement order.", "She asked how I had got there.", ["She asked how had I got there.", "She asked how I had got there.", "She asked how did I got there."], "No inversion.", "How I had got there.", "statement-order"),
  q("reported-questions", 7, "B1", "fix", "Ana asked if was I free on Friday.", "Ana asked if I was free on Friday.", ["Ana asked if was I free on Friday.", "Ana asked if I was free on Friday.", "Ana asked if did I was free on Friday."], "If + subject + verb.", "If I was free.", "if-whether"),
  q("reported-questions", 8, "B1", "gap", "They asked whether we ___ bring ID.", "should", ["did should", "should", "do"], "Keep the modal; statement order.", "Whether we should bring ID.", "if-whether"),

  q("lay-vs-lie", 1, "B1", "gap", "___ the keys on the desk.", "Lay", ["Lie", "Lay", "Lain"], "Put something down; needs an object.", "Lay the keys.", "lay-object"),
  q("lay-vs-lie", 2, "B1", "gap", "I'm going to ___ on the sofa for ten minutes.", "lie", ["lay", "lie", "laid"], "Recline; no object.", "Lie on the sofa.", "lie-recline"),
  q("lay-vs-lie", 3, "B1", "fix", "Lie the folders by the printer.", "Lay the folders by the printer.", ["Lie the folders by the printer.", "Lay the folders by the printer.", "Lain the folders by the printer."], "Folders = object.", "Lay + object.", "lay-object"),
  q("lay-vs-lie", 4, "B1", "mcq", "Which needs no object?", "Don't lie in the sun too long.", ["Don't lay in the sun too long.", "Don't lie in the sun too long.", "Don't laid in the sun too long."], "Recline.", "Lie in the sun.", "lie-recline"),
  q("lay-vs-lie", 5, "B1", "gap", "Yesterday she ___ the samples on the tray.", "laid", ["lay", "laid", "lied"], "Past of lay (put).", "Laid + object.", "lay-object"),
  q("lay-vs-lie", 6, "B1", "mcq", "Past of recline (lie) is ___.", "lay", ["laid", "lay", "lied"], "Lie → lay → lain.", "Yesterday I lay on the sofa.", "lie-recline"),
  q("lay-vs-lie", 7, "B1", "fix", "He laid down after lunch. (no object; recline)", "He lay down after lunch.", ["He laid down after lunch.", "He lay down after lunch.", "He lied down after lunch."], "Past of lie = lay.", "Lay down.", "lie-recline"),
  q("lay-vs-lie", 8, "B1", "gap", "Please ___ your coat on that chair.", "lay", ["lie", "lay", "lain"], "Coat is the object.", "Lay your coat.", "lay-object"),

  q("future-perfect", 1, "B2", "gap", "By 6 I will have ___.", "left", ["leave", "left", "leaving"], "Finished before a future point.", "Will have + past participle.", "will-have-pp"),
  q("future-perfect", 2, "B2", "gap", "___ Friday we will have sent the invoice.", "By", ["Until", "By", "During"], "Deadline in the future.", "By + future point.", "by-future-point"),
  q("future-perfect", 3, "B2", "fix", "By noon she will have finish the draft.", "By noon she will have finished the draft.", ["By noon she will have finish the draft.", "By noon she will have finished the draft.", "By noon she will finished the draft."], "Have + participle.", "Will have finished.", "will-have-pp"),
  q("future-perfect", 4, "B2", "mcq", "Which is finished before a future time?", "They will have boarded by 9.", ["They will board at 9 as a simple future.", "They will have boarded by 9.", "They will be boarding by 9 as the only completed reading."], "Completed before 9.", "Will have boarded.", "will-have-pp"),
  q("future-perfect", 5, "B2", "gap", "This time next month I will have ___ here for a year.", "worked", ["work", "worked", "working"], "Duration completed by then.", "Will have worked.", "will-have-pp"),
  q("future-perfect", 6, "B2", "mcq", "Choose future perfect, not future continuous.", "At 8 I will have left. The lights will be off.", ["At 8 I will be leaving still.", "At 8 I will have left. The lights will be off.", "At 8 I will left."], "Already gone before 8.", "Will have left.", "by-future-point"),
  q("future-perfect", 7, "B2", "fix", "By the time you arrive, we will eat already.", "By the time you arrive, we will have eaten.", ["By the time you arrive, we will eat already.", "By the time you arrive, we will have eaten.", "By the time you arrive, we will be eaten."], "Finished before you arrive.", "Will have eaten.", "by-future-point"),
  q("future-perfect", 8, "B2", "gap", "Don't call at 7. I will have ___ by then.", "gone", ["go", "gone", "going"], "Already not there.", "Will have gone.", "will-have-pp"),
];
