import type { Topic } from "../lib/types";

export const PHRASAL_VERBS_SET = [
  "get up",
  "get on",
  "get off",
  "take off",
  "take out",
  "look after",
  "look for",
  "look up",
  "put on",
  "put off",
  "go on",
  "go out",
  "come back",
  "turn on",
  "turn off",
  "give up",
  "pick up",
  "break down",
  "find out",
  "grow up",
] as const;

const draft = (
  partial: Omit<Topic, "status" | "ruleReviewed" | "rule" | "exampleGood" | "exampleBad"> & {
    rule?: string;
    exampleGood?: string;
    exampleBad?: string;
  },
): Topic => ({
  status: "draft",
  ruleReviewed: false,
  rule: partial.rule ?? "",
  exampleGood: partial.exampleGood ?? "",
  exampleBad: partial.exampleBad ?? "",
  ...partial,
});

const live = (
  topic: Omit<Topic, "status" | "ruleReviewed">,
): Topic => ({
  ...topic,
  status: "live",
  ruleReviewed: true,
});

export const TOPICS: Topic[] = [
  {
    id: "a-an-the",
    title: "A, an, the",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "a an the exercises",
    rule: "Use a/an for one thing that is not specific. Use an before a vowel sound (an apple, an hour). Use the when both of you know which one.",
    exampleGood: "She bought an umbrella.",
    exampleBad: "She bought a umbrella.",
    sisters: ["zero-article", "some-any"],
    related: ["zero-article", "some-any", "there-is-there-are"],
  },
  {
    id: "am-is-are",
    title: "Am, is, are",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "am is are exercises",
    rule: "I am. He, she, and it is. You, we, and they are. That pairing does not change.",
    exampleGood: "She is a teacher.",
    exampleBad: "She are a teacher.",
    sisters: ["was-were", "have-has"],
    related: ["was-were", "there-is-there-are", "present-simple"],
  },
  {
    id: "present-simple-vs-continuous",
    title: "Present simple vs present continuous",
    level: "A2",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "present simple vs present continuous",
    rule: "Use present simple for habits and facts (usually, every day). Use present continuous (am/is/are + -ing) for something happening now.",
    exampleGood: "She usually drinks coffee. Right now she is drinking tea.",
    exampleBad: "She usually is drinking coffee.",
    sisters: ["present-simple", "present-continuous"],
    related: ["present-simple", "present-continuous", "adverbs-of-frequency"],
  },
  {
    id: "past-simple",
    title: "Past simple",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "past simple exercises",
    rule: "Use past simple for a finished action. Regular verbs add -ed. Irregular verbs change (go → went). In a normal sentence you use that past form: I went, she watched.",
    exampleGood: "Did you go to work yesterday?",
    exampleBad: "Did you went to work yesterday?",
    sisters: ["past-continuous", "past-simple-vs-past-continuous", "present-perfect-vs-past-simple"],
    related: ["present-perfect-vs-past-simple", "past-continuous", "question-formation"],
  },
  {
    id: "subject-object-pronouns",
    title: "Subject vs object pronouns",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "subject object pronouns",
    rule: "The subject does the action (I, she, they). The object receives it (me, her, them). After a verb or preposition, use the object form.",
    exampleGood: "She called me.",
    exampleBad: "She called I.",
    sisters: ["possessive-adjectives-pronouns", "reflexive-pronouns"],
    related: ["possessive-adjectives-pronouns", "am-is-are"],
  },
  {
    id: "prepositions-of-place",
    title: "Prepositions of place",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "prepositions of place in on at",
    rule: "In is a space (in the room). On is a surface (on the table). At is a point (at the door, at home, at the station).",
    exampleGood: "The keys are on the table.",
    exampleBad: "The keys are in the table.",
    sisters: ["prepositions-of-time", "prepositions-of-movement"],
    related: ["prepositions-of-time", "there-is-there-are"],
  },
  {
    id: "prepositions-of-time",
    title: "Prepositions of time",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "prepositions of time in on at",
    rule: "In is for months, years, and parts of the day (in June, in 2020, in the morning). On is for days and dates. At is for clock times and at night.",
    exampleGood: "The meeting is on Monday at 9.",
    exampleBad: "The meeting is in Monday at 9.",
    sisters: ["prepositions-of-place", "for-since"],
    related: ["prepositions-of-place", "for-since", "already-yet-still"],
  },
  {
    id: "there-is-there-are",
    title: "There is / there are",
    level: "A1",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "there is there are exercises",
    rule: "There is introduces one thing. There are introduces more than one. The verb agrees with the noun that follows, not with there.",
    exampleGood: "There are two chairs in the kitchen.",
    exampleBad: "There is two chairs in the kitchen.",
    sisters: ["am-is-are", "countable-uncountable"],
    related: ["a-an-the", "countable-uncountable"],
  },
  {
    id: "comparatives-superlatives",
    title: "Comparatives and superlatives",
    level: "A2",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "comparatives and superlatives",
    rule: "Short adjectives: bigger / the biggest. Long adjectives: more expensive / the most expensive. After a comparative, use than, not that. Superlatives need the.",
    exampleGood: "This bag is cheaper than that one.",
    exampleBad: "This bag is cheaper that that one.",
    sisters: ["as-as", "too-enough"],
    related: ["as-as", "too-enough", "adjective-vs-adverb"],
  },
  {
    id: "present-perfect-vs-past-simple",
    title: "Present perfect vs past simple",
    level: "A2",
    phase: 1,
    status: "live",
    ruleReviewed: true,
    keyword: "present perfect vs past simple",
    rule: "Past simple is for a finished time (yesterday, last year, in 2019). Present perfect (have/has + past participle) links the past to now: experience, or a result you can still see.",
    exampleGood: "I visited Paris in 2019. I have visited Paris three times.",
    exampleBad: "I have visited Paris in 2019.",
    sisters: ["past-simple", "present-perfect", "for-since"],
    related: ["past-simple", "present-perfect", "already-yet-still"],
  },

  live({
    id: "present-simple",
    title: "Present simple",
    level: "A1",
    phase: 2,
    keyword: "present simple exercises",
    rule: "He, she, and it take -s: she lives. I, you, we, and they take the base: they live. Negatives in statements use don't or doesn't plus the base: she doesn't live here.",
    exampleGood: "Does she work on Mondays?",
    exampleBad: "Does she works on Mondays?",
    sisters: ["present-simple-vs-continuous", "present-continuous"],
    related: ["present-simple-vs-continuous", "question-formation"],
  }),
  live({
    id: "present-continuous",
    title: "Present continuous",
    level: "A1",
    phase: 2,
    keyword: "present continuous exercises",
    rule: "Build it with am, is, or are plus a verb ending in -ing: I am waiting. Never drop am/is/are, and do not use the base verb alone for an action in progress.",
    exampleGood: "They are waiting outside.",
    exampleBad: "They waiting outside.",
    sisters: ["present-simple-vs-continuous", "present-simple"],
    related: ["present-simple-vs-continuous"],
  }),
  live({
    id: "past-continuous",
    title: "Past continuous",
    level: "A2",
    phase: 2,
    keyword: "past continuous exercises",
    rule: "Was or were plus -ing: I was cooking at 7. Use it for an action that was already in progress at a past moment, not for a short finished event.",
    exampleGood: "At 7 I was cooking.",
    exampleBad: "At 7 I cooked dinner still.",
    sisters: ["past-simple", "past-simple-vs-past-continuous"],
    related: ["past-simple-vs-past-continuous"],
  }),
  live({
    id: "past-simple-vs-past-continuous",
    title: "Past simple vs past continuous",
    level: "A2",
    phase: 2,
    keyword: "past simple vs past continuous",
    rule: "A short finished event often cuts into a longer past action: I was cooking when the phone rang. The background uses past continuous; the interruption uses past simple.",
    exampleGood: "I was cooking when the phone rang.",
    exampleBad: "I cooked when the phone was ringing.",
    sisters: ["past-simple", "past-continuous"],
    related: ["past-simple", "past-continuous"],
  }),
  live({
    id: "present-perfect",
    title: "Present perfect",
    level: "A2",
    phase: 2,
    keyword: "present perfect exercises",
    rule: "Have or has plus the past participle: she has eaten, they have gone. Use it when you are not naming a finished date — the situation still connects to now.",
    exampleGood: "She has already eaten.",
    exampleBad: "She have already eaten.",
    sisters: ["present-perfect-vs-past-simple", "for-since"],
    related: ["present-perfect-vs-past-simple", "for-since"],
  }),
  live({
    id: "will-vs-going-to",
    title: "Will vs going to",
    level: "A2",
    phase: 2,
    keyword: "will vs going to",
    rule: "Will is a decision or prediction at the moment of speaking. Going to is a plan you already have, or a future you can see coming from evidence now.",
    exampleGood: "Look at those clouds — it is going to rain.",
    exampleBad: "Look at those clouds — it will raining.",
    sisters: ["going-to", "future-simple"],
    related: ["going-to"],
  }),
  live({
    id: "going-to",
    title: "Going to",
    level: "A1",
    phase: 2,
    keyword: "be going to exercises",
    rule: "The shape is always am/is/are + going to + the base verb: I am going to call her. Do not drop am/is/are, and do not add a second to (not going to to call).",
    exampleGood: "I am going to call her tonight.",
    exampleBad: "I going to call her tonight.",
    sisters: ["will-vs-going-to", "future-simple"],
    related: ["will-vs-going-to"],
  }),
  live({
    id: "zero-article",
    title: "Zero article",
    level: "A2",
    phase: 2,
    keyword: "zero article no article",
    rule: "Use no article with plural or uncountable nouns when you mean things in general: Dogs need water. I like music. Add the only when you mean specific ones you both know.",
    exampleGood: "I like music.",
    exampleBad: "I like the music. (if you mean music in general)",
    sisters: ["a-an-the", "some-any"],
    related: ["a-an-the"],
  }),
  live({
    id: "some-any",
    title: "Some / any",
    level: "A1",
    phase: 2,
    keyword: "some any exercises",
    rule: "Some is typical in positive sentences: I have some tea. Any is typical in questions and negatives: Do you have any tea? I don't have any tea.",
    exampleGood: "I don't have any sugar.",
    exampleBad: "I don't have some sugar.",
    sisters: ["a-an-the", "much-many-a-lot-of"],
    related: ["a-an-the", "countable-uncountable"],
  }),
  live({
    id: "much-many-a-lot-of",
    title: "Much / many / a lot of",
    level: "A1",
    phase: 2,
    keyword: "much many a lot of",
    rule: "Many with things you can count (many emails). Much with uncountable nouns, mainly in questions and negatives (much time). A lot of works with both in positive sentences.",
    exampleGood: "We don't have much time.",
    exampleBad: "We don't have many time.",
    sisters: ["some-any", "countable-uncountable", "a-few-vs-a-little"],
    related: ["countable-uncountable"],
  }),
  live({
    id: "this-that-these-those",
    title: "This / that / these / those",
    level: "A1",
    phase: 2,
    keyword: "this that these those",
    rule: "This and these are near you. That and those are farther away. This/that with one thing; these/those with more than one.",
    exampleGood: "These keys are mine.",
    exampleBad: "This keys are mine.",
    sisters: ["a-an-the"],
    related: ["a-an-the"],
  }),
  live({
    id: "possessive-adjectives-pronouns",
    title: "Possessive adjectives vs pronouns",
    level: "A1",
    phase: 2,
    keyword: "possessive adjectives vs pronouns",
    rule: "My, your, her go before a noun: her bag. Mine, yours, hers stand alone: the bag is hers. Do not put a noun after mine/yours/hers.",
    exampleGood: "The bag is hers.",
    exampleBad: "The bag is her.",
    sisters: ["subject-object-pronouns", "possessive-s"],
    related: ["possessive-s", "subject-object-pronouns"],
  }),
  live({
    id: "possessive-s",
    title: "Possessive 's",
    level: "A1",
    phase: 2,
    keyword: "possessive s exercises",
    rule: "Add 's to a person or animal to show belonging: Tom's phone. If a plural already ends in s, add only the apostrophe: the students' room.",
    exampleGood: "Tom's phone is on the desk.",
    exampleBad: "Toms phone is on the desk.",
    sisters: ["possessive-adjectives-pronouns", "its-vs-its"],
    related: ["its-vs-its"],
  }),
  live({
    id: "question-formation",
    title: "Question formation (do / does / did)",
    level: "A1",
    phase: 2,
    keyword: "question formation do does did",
    rule: "Turn a sentence into a question by putting do, does, or did first, then the subject, then the base verb: Do you work here? Where does she live? The main verb never keeps -s or -ed after do/does/did.",
    exampleGood: "Did they wait long?",
    exampleBad: "Did they waited long?",
    sisters: ["present-simple", "past-simple", "indirect-questions"],
    related: ["present-simple", "past-simple"],
  }),
  live({
    id: "countable-uncountable",
    title: "Countable vs uncountable nouns",
    level: "A1",
    phase: 2,
    keyword: "countable uncountable nouns",
    rule: "If you can number it (one chair, two chairs), it is countable and can take a/an. If you cannot (water, advice), do not say a water or two advices — use some, or no article.",
    exampleGood: "I need some advice.",
    exampleBad: "I need an advice.",
    sisters: ["tricky-uncountables", "much-many-a-lot-of"],
    related: ["some-any", "much-many-a-lot-of"],
  }),
  live({
    id: "can-could",
    title: "Can / could",
    level: "A1",
    phase: 2,
    keyword: "can could exercises",
    rule: "Can shows ability or permission in the present: I can swim. Could is the past of can, or a more polite request: Could you open the window? After can/could the verb stays in the base form.",
    exampleGood: "Could you open the window?",
    exampleBad: "Could you opening the window?",
    sisters: ["must-have-to", "may-might"],
    related: ["must-have-to", "should"],
  }),
  live({
    id: "must-have-to",
    title: "Must / have to",
    level: "A2",
    phase: 2,
    keyword: "must vs have to",
    rule: "Both show obligation. Have to often comes from a rule or situation. Must often comes from the speaker. Mustn't means it is not allowed — that is not the same as don't have to (no obligation).",
    exampleGood: "You don't have to come if you are busy.",
    exampleBad: "You mustn't come if you are busy. (if you only mean it is optional)",
    sisters: ["should", "can-could"],
    related: ["should"],
  }),
  live({
    id: "should",
    title: "Should",
    level: "A2",
    phase: 2,
    keyword: "should exercises",
    rule: "Should gives advice or a sensible idea, not a hard rule: You should see a doctor. After should, use the base verb. It is weaker than must.",
    exampleGood: "You should see a doctor.",
    exampleBad: "You should to see a doctor.",
    sisters: ["must-have-to", "would-rather-had-better"],
    related: ["must-have-to"],
  }),
  live({
    id: "used-to",
    title: "Used to",
    level: "A2",
    phase: 2,
    keyword: "used to exercises",
    rule: "Used to + base verb is a past habit or state that is not true now: I used to smoke. In questions and negatives, use did + use to (not used): Did you use to live here?",
    exampleGood: "Did you use to live here?",
    exampleBad: "Did you used to live here?",
    sisters: ["used-to-vs-would", "used-to-vs-be-used-to"],
    related: ["past-simple"],
  }),
  live({
    id: "for-since",
    title: "For / since",
    level: "A2",
    phase: 2,
    keyword: "for vs since",
    rule: "For is a length of time: for three years, for a week. Since is the starting point: since 2021, since Monday. Do not mix them (not for 2021, not since three years).",
    exampleGood: "I have lived here since 2021.",
    exampleBad: "I have lived here for 2021.",
    sisters: ["prepositions-of-time", "present-perfect", "already-yet-still"],
    related: ["present-perfect", "prepositions-of-time"],
  }),
  live({
    id: "its-vs-its",
    title: "Its vs it's",
    level: "A2",
    phase: 2,
    keyword: "its vs it's",
    rule: "It's is a short form of it is or it has. Its shows belonging, with no apostrophe: the dog wagged its tail.",
    exampleGood: "The dog wagged its tail.",
    exampleBad: "The dog wagged it's tail.",
    sisters: ["possessive-s"],
    related: ["possessive-s"],
  }),
  live({
    id: "affect-vs-effect",
    title: "Affect vs effect",
    level: "B1",
    phase: 2,
    keyword: "affect vs effect",
    rule: "Affect is usually the verb: the news affected her. Effect is usually the noun: the effect of the news. If you can put the in front of it, you probably want effect.",
    exampleGood: "The news affected her.",
    exampleBad: "The news effected her.",
    sisters: [],
    related: ["make-vs-do"],
  }),
  live({
    id: "fewer-vs-less",
    title: "Fewer vs less",
    level: "B1",
    phase: 2,
    keyword: "fewer vs less",
    rule: "Fewer with plural things you can count: fewer emails. Less with uncountable amounts: less time, less sugar. Do not say less emails.",
    exampleGood: "I get fewer emails now.",
    exampleBad: "I get less emails now.",
    sisters: ["countable-uncountable"],
    related: ["countable-uncountable"],
  }),
  live({
    id: "make-vs-do",
    title: "Make vs do",
    level: "A2",
    phase: 2,
    keyword: "make vs do",
    rule: "Do for tasks and activities: do homework, do the shopping. Make for creating or producing a result: make a cake, make a decision, make a mistake.",
    exampleGood: "I need to make a decision.",
    exampleBad: "I need to do a decision.",
    sisters: ["say-vs-tell"],
    related: ["say-vs-tell"],
  }),
  live({
    id: "say-vs-tell",
    title: "Say vs tell",
    level: "A2",
    phase: 2,
    keyword: "say vs tell",
    rule: "Say something. Tell someone something. Tell needs a person: she told me the news. After say, the person needs to if you mention them: she said to me.",
    exampleGood: "She told me the news.",
    exampleBad: "She said me the news.",
    sisters: ["make-vs-do", "reported-statements"],
    related: ["make-vs-do"],
  }),
  live({
    id: "good-vs-well",
    title: "Good vs well",
    level: "A2",
    phase: 2,
    keyword: "good vs well",
    rule: "Good describes a noun: a good singer. Well describes how someone does an action: she sings well. Well can also mean healthy: I don't feel well.",
    exampleGood: "She sings well.",
    exampleBad: "She sings good.",
    sisters: ["adjective-vs-adverb"],
    related: ["ed-vs-ing-adjectives"],
  }),
  live({
    id: "every-vs-each",
    title: "Every vs each",
    level: "A2",
    phase: 2,
    keyword: "every vs each",
    rule: "Every looks at the group as a whole: every student passed. Each looks at members one by one: each student has a locker. Both take a singular noun.",
    exampleGood: "Each student has a locker.",
    exampleBad: "Each students have a locker.",
    sisters: ["other-another-others"],
    related: ["other-another-others"],
  }),
  live({
    id: "other-another-others",
    title: "Other / another / others",
    level: "A2",
    phase: 2,
    keyword: "other another others",
    rule: "Another + one thing: another cup. Other + a noun: other people. Others stands alone, with no noun after it. The other means the last remaining one(s).",
    exampleGood: "Would you like another cup?",
    exampleBad: "Would you like other cup?",
    sisters: ["every-vs-each"],
    related: ["every-vs-each"],
  }),
  live({
    id: "been-vs-gone",
    title: "Been vs gone",
    level: "A2",
    phase: 2,
    keyword: "been vs gone",
    rule: "Has gone means they went and they are still there. Has been means they went and they came back — or you mean the experience of visiting.",
    exampleGood: "She has gone to the bank. She isn't here.",
    exampleBad: "She has been to the bank. She isn't here. (if she is still at the bank)",
    sisters: ["present-perfect"],
    related: ["present-perfect"],
  }),
  live({
    id: "ed-vs-ing-adjectives",
    title: "Bored vs boring (-ed / -ing)",
    level: "A2",
    phase: 2,
    keyword: "bored vs boring adjectives",
    rule: "-ed describes how a person feels: I am bored. -ing describes the thing that causes the feeling: the film is boring. People feel -ed; things are often -ing.",
    exampleGood: "The film is boring.",
    exampleBad: "The film is bored.",
    sisters: ["adjective-vs-adverb"],
    related: ["good-vs-well"],
  }),

  live({
    id: "already-yet-still",
    title: "Already / yet / still",
    level: "A2",
    phase: 3,
    keyword: "already yet still",
    rule: "Already means sooner than expected, in positives: she has already left. Yet means until now, in questions and negatives: has she left yet? Still means it continues: she is still here / she still hasn't called.",
    exampleGood: "Has the parcel arrived yet?",
    exampleBad: "Has the parcel arrived already? (if you only mean 'up to now')",
    sisters: ["present-perfect", "for-since"],
    related: ["present-perfect"],
  }),
  live({
    id: "reflexive-pronouns",
    title: "Reflexive pronouns",
    level: "A2",
    phase: 3,
    keyword: "reflexive pronouns myself",
    rule: "Use myself, yourself, himself when the same person is subject and object: she taught herself. Do not use a reflexive just because the verb has an object (she taught me, not she taught myself).",
    exampleGood: "She taught herself Spanish.",
    exampleBad: "She taught herself me Spanish.",
    sisters: ["subject-object-pronouns"],
    related: ["subject-object-pronouns"],
  }),
  live({
    id: "relative-pronouns",
    title: "Relative pronouns",
    level: "A2",
    phase: 3,
    keyword: "relative pronouns who which that",
    rule: "A relative clause adds information after a noun. Who for people, which for things, that for both: the woman who called; the file which / that I sent.",
    exampleGood: "The woman who called is my manager.",
    exampleBad: "The woman which called is my manager.",
    sisters: ["who-which-that"],
    related: ["subject-object-pronouns"],
  }),
  live({
    id: "prepositions-of-movement",
    title: "Prepositions of movement",
    level: "A2",
    phase: 3,
    keyword: "prepositions of movement",
    rule: "These show direction, not location. To a destination, into a space, onto a surface, out of / off when you leave. In/on/at for where something is belongs on the place page.",
    exampleGood: "She walked into the room.",
    exampleBad: "She walked in the room. (if you mean she entered)",
    sisters: ["prepositions-of-place"],
    related: ["prepositions-of-place"],
  }),
  live({
    id: "dependent-prepositions",
    title: "Dependent prepositions",
    level: "B1",
    phase: 3,
    keyword: "adjective preposition interested in",
    rule: "Some adjectives and verbs lock a preposition: interested in, good at, afraid of, depend on, listen to. Learn the pair. Do not reuse in/on/at from place or time.",
    exampleGood: "She is interested in design.",
    exampleBad: "She is interested on design.",
    sisters: ["prepositions-of-place"],
    related: ["prepositions-of-place"],
  }),
  live({
    id: "may-might",
    title: "May / might",
    level: "A2",
    phase: 3,
    keyword: "may vs might",
    rule: "May and might show possibility, not ability (that is can). Might often sounds a little less sure. After both, use the base verb: it may rain.",
    exampleGood: "It might rain later.",
    exampleBad: "It might raining later.",
    sisters: ["can-could"],
    related: ["can-could"],
  }),
  live({
    id: "too-enough",
    title: "Too / enough",
    level: "A2",
    phase: 3,
    keyword: "too vs enough",
    rule: "Too means more than is OK: too heavy to lift. Enough means as much as you need: old enough to drive. Too comes before the adjective; enough comes after it.",
    exampleGood: "This bag is too heavy.",
    exampleBad: "This bag is enough heavy.",
    sisters: ["comparatives-superlatives", "so-vs-such"],
    related: ["comparatives-superlatives"],
  }),
  live({
    id: "as-as",
    title: "As … as",
    level: "A2",
    phase: 3,
    keyword: "as as comparisons",
    rule: "As … as shows the same degree: as tall as her brother. Negatives use not as … as. This is not the -er / more comparative on the other page.",
    exampleGood: "She is as tall as her brother.",
    exampleBad: "She is as taller as her brother.",
    sisters: ["comparatives-superlatives"],
    related: ["comparatives-superlatives"],
  }),
  live({
    id: "adverbs-of-frequency",
    title: "Adverbs of frequency",
    level: "A1",
    phase: 3,
    keyword: "adverbs of frequency",
    rule: "Always, usually, often, sometimes, never. They usually go before the main verb (she always arrives) but after am, is, or are (she is always late).",
    exampleGood: "She is always late.",
    exampleBad: "She always is late.",
    sisters: ["present-simple"],
    related: ["present-simple"],
  }),
  live({
    id: "gerunds-vs-infinitives",
    title: "Gerunds vs infinitives",
    level: "B1",
    phase: 3,
    keyword: "gerund vs infinitive",
    rule: "After some verbs use -ing: enjoy swimming. After others use to + verb: want to go. Enjoy, avoid, finish take -ing. Want, decide, hope take to. This page is that choice, not a dictionary of every verb.",
    exampleGood: "I enjoy swimming.",
    exampleBad: "I enjoy to swim.",
    sisters: ["gerunds-after-verbs", "infinitives-after-verbs", "stop-remember-gerund-infinitive"],
    related: ["present-simple"],
  }),
  live({
    id: "zero-conditional",
    title: "Zero conditional",
    level: "A2",
    phase: 3,
    keyword: "zero conditional",
    rule: "If + present, present. Use it for facts and routines that are always true: If you heat ice, it melts. Not for a possible future (that is the first conditional).",
    exampleGood: "If you heat ice, it melts.",
    exampleBad: "If you heat ice, it will melts.",
    sisters: ["first-conditional"],
    related: ["first-conditional"],
  }),
  live({
    id: "first-conditional",
    title: "First conditional",
    level: "A2",
    phase: 3,
    keyword: "first conditional",
    rule: "If + present, will + base. Use it for a real possible future: If it rains, we will stay in. Do not put will in the if-clause.",
    exampleGood: "If it rains, we will stay in.",
    exampleBad: "If it will rain, we will stay in.",
    sisters: ["zero-conditional", "second-conditional", "first-vs-second-conditional"],
    related: ["second-conditional"],
  }),
  live({
    id: "second-conditional",
    title: "Second conditional",
    level: "B1",
    phase: 3,
    keyword: "second conditional",
    rule: "If + past, would + base. Use it for an unreal present or future: If I had time, I would help. If I were you is the usual form for advice.",
    exampleGood: "If I had time, I would help.",
    exampleBad: "If I would have time, I would help.",
    sisters: ["first-conditional", "first-vs-second-conditional"],
    related: ["first-conditional"],
  }),
  live({
    id: "passive-present",
    title: "Passive voice (present)",
    level: "B1",
    phase: 3,
    keyword: "present passive",
    rule: "Am, is, or are plus a past participle. The thing that receives the action becomes the subject: they make the parts → the parts are made. Use by only if you need the doer.",
    exampleGood: "The parts are made in Osaka.",
    exampleBad: "The parts are make in Osaka.",
    sisters: ["passive-past"],
    related: ["passive-past"],
  }),
  live({
    id: "passive-past",
    title: "Passive voice (past)",
    level: "B1",
    phase: 3,
    keyword: "past passive",
    rule: "Was or were plus a past participle: the email was sent yesterday. Same idea as present passive, but the helping verb is past.",
    exampleGood: "The email was sent yesterday.",
    exampleBad: "The email was send yesterday.",
    sisters: ["passive-present"],
    related: ["passive-present"],
  }),
  live({
    id: "future-simple",
    title: "Future simple (will)",
    level: "A2",
    phase: 3,
    keyword: "future simple will",
    rule: "Will plus the base verb: I will call, she won't wait. Won't is will not. This page is the form. Choosing will versus going to is a different page.",
    exampleGood: "I will call you tonight.",
    exampleBad: "I will calling you tonight.",
    sisters: ["will-vs-going-to", "going-to"],
    related: ["will-vs-going-to"],
  }),
  live({
    id: "future-continuous",
    title: "Future continuous",
    level: "B1",
    phase: 3,
    keyword: "future continuous",
    rule: "Will be plus -ing for an action in progress at a future time: at 8 I will be travelling. Not a simple decision (that is will + base).",
    exampleGood: "At 8 I will be travelling.",
    exampleBad: "At 8 I will travelling.",
    sisters: ["future-simple", "future-perfect"],
    related: ["future-simple"],
  }),
  live({
    id: "past-perfect",
    title: "Past perfect",
    level: "B1",
    phase: 3,
    keyword: "past perfect",
    rule: "Had plus a past participle for the earlier of two past events: the film had started when we arrived. The later event stays in past simple.",
    exampleGood: "The film had started when we arrived.",
    exampleBad: "The film has started when we arrived.",
    sisters: ["past-simple"],
    related: ["past-simple"],
  }),
  live({
    id: "present-perfect-continuous",
    title: "Present perfect continuous",
    level: "B1",
    phase: 3,
    keyword: "present perfect continuous",
    rule: "Have or has been plus -ing for an activity that started before now and is still going, often with for or since: I have been waiting for an hour. This is the activity shape, not have/has + participle alone.",
    exampleGood: "I have been waiting for an hour.",
    exampleBad: "I have waiting for an hour.",
    sisters: ["present-perfect", "present-perfect-vs-present-perfect-continuous"],
    related: ["present-perfect"],
  }),
  live({
    id: "reported-statements",
    title: "Reported speech (statements)",
    level: "B1",
    phase: 3,
    keyword: "reported speech statements",
    rule: "When you report later, tenses usually move back: “I work here” → she said she worked there. Pronouns and time words change too. Say versus tell (who you tell) is a different page.",
    exampleGood: "She said she worked there.",
    exampleBad: "She said she work there.",
    sisters: ["reported-questions", "say-vs-tell"],
    related: ["say-vs-tell"],
  }),
  live({
    id: "third-conditional",
    title: "Third conditional",
    level: "B1",
    phase: 3,
    keyword: "third conditional",
    rule: "If + past perfect, would have + past participle. Use it for an unreal past — it did not happen: If I had left earlier, I would have caught the train.",
    exampleGood: "If I had left earlier, I would have caught the train.",
    exampleBad: "If I would have left earlier, I would have caught the train.",
    sisters: ["second-conditional", "mixed-conditionals"],
    related: ["second-conditional"],
  }),
  live({
    id: "mixed-conditionals",
    title: "Mixed conditionals",
    level: "B2",
    phase: 3,
    keyword: "mixed conditionals",
    rule: "The if-clause and the result are in different times. A common mix: unreal past condition, present result: If I had studied medicine, I would be a doctor now. That is not a pure third conditional.",
    exampleGood: "If I had studied medicine, I would be a doctor now.",
    exampleBad: "If I had studied medicine, I would have been a doctor now. (if you mean the job now)",
    sisters: ["third-conditional", "second-conditional"],
    related: ["third-conditional"],
  }),
  live({
    id: "was-were",
    title: "Was / were",
    level: "A1",
    phase: 3,
    keyword: "was were exercises",
    rule: "Was and were are the past of am, is, and are. I, he, she, and it take was. You, we, and they take were.",
    exampleGood: "They were at home.",
    exampleBad: "They was at home.",
    sisters: ["am-is-are"],
    related: ["am-is-are", "past-simple"],
  }),
  live({
    id: "have-has",
    title: "Have / has",
    level: "A1",
    phase: 3,
    keyword: "have has exercises",
    rule: "I, you, we, and they have. He, she, and it has. Use it for possession in the present: she has a car. This is only have/has, not every present-simple verb.",
    exampleGood: "She has a car.",
    exampleBad: "She have a car.",
    sisters: ["am-is-are"],
    related: ["present-simple"],
  }),
  live({
    id: "question-tags",
    title: "Question tags",
    level: "A2",
    phase: 3,
    keyword: "question tags",
    rule: "A short question after a statement: You're late, aren't you? A positive statement takes a negative tag, and a negative statement takes a positive tag. Use the same auxiliary as the statement.",
    exampleGood: "You're late, aren't you?",
    exampleBad: "You're late, are you? (as a normal checking tag)",
    sisters: ["question-formation"],
    related: ["question-formation"],
  }),
  live({
    id: "indirect-questions",
    title: "Indirect questions",
    level: "B1",
    phase: 3,
    keyword: "indirect questions",
    rule: "After I wonder, could you tell me, or do you know, keep statement word order: I wonder where she lives. Do not use do/does/did after the question word in that clause.",
    exampleGood: "I wonder where she lives.",
    exampleBad: "I wonder where does she live.",
    sisters: ["question-formation", "reported-questions"],
    related: ["question-formation"],
  }),
  live({
    id: "used-to-vs-would",
    title: "Used to vs would",
    level: "B1",
    phase: 3,
    keyword: "used to vs would",
    rule: "Both can describe repeated past actions. Used to also works for past states: I used to have a motorbike. Would does not work for states: not I would have a motorbike for ownership.",
    exampleGood: "I used to have a motorbike.",
    exampleBad: "I would have a motorbike when I was 20. (for ownership)",
    sisters: ["used-to", "used-to-vs-be-used-to"],
    related: ["used-to"],
  }),
  live({
    id: "used-to-vs-be-used-to",
    title: "Used to vs be used to",
    level: "B1",
    phase: 3,
    keyword: "used to vs be used to",
    rule: "Used to + verb is a past habit that has stopped. Be used to + noun or -ing means accustomed: I am used to the noise / I am used to working nights. The be is required in the second.",
    exampleGood: "I am used to working nights.",
    exampleBad: "I used to working nights. (if you mean accustomed now)",
    sisters: ["used-to", "used-to-vs-would"],
    related: ["used-to"],
  }),
  live({
    id: "adjective-vs-adverb",
    title: "Adjective vs adverb",
    level: "A2",
    phase: 3,
    keyword: "adjective vs adverb",
    rule: "Adjectives describe a noun or follow be: a quiet room, she is quiet. Adverbs (often -ly) describe how someone does an action: she speaks quietly. Good versus well is a special pair on its own page.",
    exampleGood: "She speaks quietly.",
    exampleBad: "She speaks quiet.",
    sisters: ["good-vs-well", "ed-vs-ing-adjectives"],
    related: ["good-vs-well"],
  }),
  live({
    id: "a-few-vs-a-little",
    title: "A few vs a little",
    level: "A2",
    phase: 3,
    keyword: "a few vs a little",
    rule: "A few with countable plurals: a few emails. A little with uncountable nouns: a little time. Without a, few and little sound more negative (almost none).",
    exampleGood: "I have a little time.",
    exampleBad: "I have a few time.",
    sisters: ["much-many-a-lot-of", "countable-uncountable"],
    related: ["countable-uncountable"],
  }),

  live({
    id: "gerunds-after-verbs",
    title: "Gerunds after certain verbs",
    level: "B1",
    phase: 4,
    keyword: "verbs followed by gerund",
    rule: "After enjoy, avoid, finish, mind, suggest, keep, miss, and consider, use -ing: I enjoy swimming. This page is that verb list. Choosing -ing versus to in general is the other gerunds page.",
    exampleGood: "Would you mind waiting?",
    exampleBad: "Would you mind to wait?",
    sisters: ["gerunds-vs-infinitives", "infinitives-after-verbs"],
    related: ["gerunds-vs-infinitives"],
  }),
  live({
    id: "infinitives-after-verbs",
    title: "Infinitives after certain verbs",
    level: "B1",
    phase: 4,
    keyword: "verbs followed by infinitive",
    rule: "After want, decide, hope, plan, refuse, promise, offer, and learn, use to + verb: she decided to wait. Not -ing after these verbs.",
    exampleGood: "She decided to wait.",
    exampleBad: "She decided waiting.",
    sisters: ["gerunds-vs-infinitives", "gerunds-after-verbs"],
    related: ["gerunds-vs-infinitives"],
  }),
  live({
    id: "linking-words",
    title: "Linking words",
    level: "A2",
    phase: 4,
    keyword: "because although however",
    rule: "Because gives a reason (a clause). Although concedes a fact, then the main point. However starts a contrast, usually after a full stop or semicolon. Despite belongs on its own page.",
    exampleGood: "I stayed in because it was raining.",
    exampleBad: "I stayed in despite it was raining.",
    sisters: ["despite-in-spite-of"],
    related: ["despite-in-spite-of"],
  }),
  live({
    id: "despite-in-spite-of",
    title: "Despite / in spite of",
    level: "B1",
    phase: 4,
    keyword: "despite vs in spite of",
    rule: "Despite and in spite of mean the same. Both take a noun or -ing, not a full clause: despite the rain / in spite of feeling tired. For a clause, use although.",
    exampleGood: "Despite the rain, we walked.",
    exampleBad: "Despite it was raining, we walked.",
    sisters: ["linking-words"],
    related: ["linking-words"],
  }),
  live({
    id: "so-vs-such",
    title: "So vs such",
    level: "A2",
    phase: 4,
    keyword: "so vs such",
    rule: "So + adjective or adverb: so cold, so quickly. Such + (a/an) + adjective + noun: such a cold day. Too/enough is a different idea (too much / not enough).",
    exampleGood: "It was such a cold day.",
    exampleBad: "It was so a cold day.",
    sisters: ["too-enough"],
    related: ["too-enough"],
  }),
  live({
    id: "so-neither",
    title: "So / neither",
    level: "A2",
    phase: 4,
    keyword: "so neither agreement",
    rule: "To agree with a positive, use so + auxiliary + subject: I like tea. So do I. To agree with a negative, use neither: I don't. Neither do I. This is agreement, not too/enough.",
    exampleGood: "I don't eat meat. Neither do I.",
    exampleBad: "I don't eat meat. So do I.",
    sisters: ["too-enough"],
    related: ["too-enough"],
  }),
  live({
    id: "wish-if-only",
    title: "Wish / if only",
    level: "B1",
    phase: 4,
    keyword: "wish if only",
    rule: "Wish + past for a present you cannot change: I wish I had more time. Wish + past perfect for a past you cannot change: I wish I had left earlier. If only is stronger. Second conditional uses if + would, not wish.",
    exampleGood: "I wish I had more time.",
    exampleBad: "I wish I would have more time now.",
    sisters: ["second-conditional"],
    related: ["second-conditional"],
  }),
  live({
    id: "causative",
    title: "Causative (have/get something done)",
    level: "B1",
    phase: 4,
    keyword: "have something done",
    rule: "Have or get + object + past participle means someone else does it for you: I had my car serviced. Passive is the thing is done, without that ‘arrange it’ meaning.",
    exampleGood: "I had my car serviced.",
    exampleBad: "I had serviced my car. (if you mean a garage did it)",
    sisters: ["passive-present"],
    related: ["passive-present"],
  }),
  live({
    id: "subject-verb-agreement",
    title: "Subject–verb agreement",
    level: "A2",
    phase: 4,
    keyword: "subject verb agreement",
    rule: "A singular subject takes a singular verb; a plural subject takes a plural verb. Everyone, each, and news are singular: everyone is ready; the news is on. This is more than am/is/are pairings.",
    exampleGood: "The news is on at 6.",
    exampleBad: "The news are on at 6.",
    sisters: ["am-is-are"],
    related: ["am-is-are"],
  }),
  live({
    id: "tricky-uncountables",
    title: "Tricky uncountables",
    level: "A2",
    phase: 4,
    keyword: "advice information uncountable",
    rule: "Advice, information, furniture, luggage, and news have no plural in this use. Say some advice, two pieces of furniture — not an advice or informations. The countable page is the general idea; this page is these nouns.",
    exampleGood: "She gave me some advice.",
    exampleBad: "She gave me an advice.",
    sisters: ["countable-uncountable"],
    related: ["countable-uncountable"],
  }),
  live({
    id: "by-vs-until",
    title: "By vs until",
    level: "B1",
    phase: 4,
    keyword: "by vs until",
    rule: "By is a deadline — not later than: send it by Friday. Until is how long something continues: the shop is open until 8. In/on/at for dates and clock times is the other time page.",
    exampleGood: "Please send it by Friday.",
    exampleBad: "Please send it until Friday. (if you mean a deadline)",
    sisters: ["prepositions-of-time"],
    related: ["prepositions-of-time"],
  }),
  live({
    id: "in-time-vs-on-time",
    title: "In time vs on time",
    level: "B1",
    phase: 4,
    keyword: "in time vs on time",
    rule: "On time means at the scheduled moment: the train left on time. In time means not too late, with enough time to spare: we arrived in time to board.",
    exampleGood: "We arrived in time to board.",
    exampleBad: "We arrived on time to board. (if you only mean ‘with minutes to spare’)",
    sisters: ["prepositions-of-time"],
    related: ["prepositions-of-time"],
  }),
  live({
    id: "at-the-end-vs-in-the-end",
    title: "At the end vs in the end",
    level: "B1",
    phase: 4,
    keyword: "at the end vs in the end",
    rule: "At the end of + a noun is a position: at the end of the street / the film. In the end means finally, after a process: in the end we took a taxi.",
    exampleGood: "In the end we took a taxi.",
    exampleBad: "At the end we took a taxi. (if you mean ‘finally’)",
    sisters: ["prepositions-of-time"],
    related: ["prepositions-of-time"],
  }),
  live({
    id: "during-vs-while",
    title: "During vs while",
    level: "A2",
    phase: 4,
    keyword: "during vs while",
    rule: "During + a noun: during the meeting. While + a clause: while we were talking. Do not say during we were talking.",
    exampleGood: "Please don't call during the meeting.",
    exampleBad: "Please don't call during we were meeting.",
    sisters: ["prepositions-of-time"],
    related: ["prepositions-of-time"],
  }),
  live({
    id: "who-vs-whom",
    title: "Who vs whom",
    level: "B1",
    phase: 4,
    keyword: "who vs whom",
    rule: "Who is the subject: who called? Whom is the object: whom did you call? After a preposition, whom is the careful form: to whom. Everyday English often uses who for both.",
    exampleGood: "Whom did you call?",
    exampleBad: "Whom called you?",
    sisters: ["subject-object-pronouns", "relative-pronouns"],
    related: ["relative-pronouns"],
  }),
  live({
    id: "like-vs-as",
    title: "Like vs as",
    level: "B1",
    phase: 4,
    keyword: "like vs as",
    rule: "Like + a noun means similar to: she sings like her mother. As + a clause or a role: as I said; she works as a nurse. As … as (as tall as) is degree comparison on another page.",
    exampleGood: "She works as a nurse.",
    exampleBad: "She works like a nurse. (if you mean her job)",
    sisters: ["as-as"],
    related: ["as-as"],
  }),
  live({
    id: "bring-vs-take",
    title: "Bring vs take",
    level: "A2",
    phase: 4,
    keyword: "bring vs take",
    rule: "Bring is towards the speaker or the place we are talking about: bring the files here. Take is away from here: take an umbrella with you.",
    exampleGood: "Please bring the files to my desk.",
    exampleBad: "Please take the files to my desk. (if I am at that desk now)",
    sisters: ["borrow-vs-lend"],
    related: ["borrow-vs-lend"],
  }),
  live({
    id: "borrow-vs-lend",
    title: "Borrow vs lend",
    level: "A2",
    phase: 4,
    keyword: "borrow vs lend",
    rule: "Borrow is receive: I borrowed a charger from Ana. Lend is give: Ana lent me a charger. The person who owns it lends; the other person borrows.",
    exampleGood: "Can I borrow your charger?",
    exampleBad: "Can I lend your charger?",
    sisters: ["bring-vs-take"],
    related: ["bring-vs-take"],
  }),
  live({
    id: "see-watch-look",
    title: "See / watch / look",
    level: "A2",
    phase: 4,
    keyword: "see vs watch vs look",
    rule: "See is notice with your eyes, often without trying. Look (at) is direct your eyes. Watch is look for a period, especially something that changes: watch a film.",
    exampleGood: "We watched a film last night.",
    exampleBad: "We looked a film last night.",
    sisters: ["hear-vs-listen"],
    related: ["hear-vs-listen"],
  }),
  live({
    id: "hear-vs-listen",
    title: "Hear vs listen",
    level: "A2",
    phase: 4,
    keyword: "hear vs listen",
    rule: "Hear is the sound reaching you, without effort: I heard a bang. Listen (to) is pay attention: listen to the podcast. See/watch/look is the eyes version.",
    exampleGood: "Listen to this podcast.",
    exampleBad: "Hear to this podcast.",
    sisters: ["see-watch-look"],
    related: ["see-watch-look"],
  }),
  live({
    id: "phrasal-verbs",
    title: "High-frequency phrasal verbs",
    level: "A2",
    phase: 4,
    keyword: "phrasal verbs exercises",
    rule: `One set of 20, one page — not a catalogue: ${PHRASAL_VERBS_SET.join(", ")}. A verb + particle changes the meaning: give up = stop trying.`,
    exampleGood: "She gave up sugar last year.",
    exampleBad: "She gave up to sugar last year.",
    sisters: [],
    related: ["make-vs-do"],
  }),
  live({
    id: "so-that-in-order-to",
    title: "So that / in order to",
    level: "B1",
    phase: 4,
    keyword: "so that in order to",
    rule: "Both show purpose. In order to + base verb: she left early in order to catch the train. So that + a clause, often with can/could: she left early so that she could catch the train. Because is a reason, not this purpose pair.",
    exampleGood: "She left early in order to catch the train.",
    exampleBad: "She left early in order that catch the train.",
    sisters: ["linking-words"],
    related: ["linking-words"],
  }),
  live({
    id: "would-rather-had-better",
    title: "Would rather / had better",
    level: "B1",
    phase: 4,
    keyword: "would rather had better",
    rule: "Would rather = preference: I'd rather walk. Had better = a warning or strong advice now: you'd better leave or you'll miss it. Should is softer general advice.",
    exampleGood: "You'd better leave now.",
    exampleBad: "You'd better to leave now.",
    sisters: ["should"],
    related: ["should"],
  }),
  live({
    id: "stop-remember-gerund-infinitive",
    title: "Stop / remember + gerund vs infinitive",
    level: "B1",
    phase: 4,
    keyword: "stop remember gerund infinitive",
    rule: "Stop smoking = quit the habit. Stop to smoke = pause another action in order to smoke. Remember doing = a memory of the past. Remember to do = don't forget a future task. Enjoy vs want is the other gerunds page.",
    exampleGood: "Remember to lock the door.",
    exampleBad: "Remember locking the door. (if you mean ‘don't forget later’)",
    sisters: ["gerunds-vs-infinitives"],
    related: ["gerunds-vs-infinitives"],
  }),
  live({
    id: "who-which-that",
    title: "Who / which / that",
    level: "A2",
    phase: 4,
    keyword: "who which that",
    rule: "Who for people, which for things, that for both in identifying clauses: the files that I sent. Which, not that, after a comma for extra information. The relatives page is how to add the clause; this page is which word.",
    exampleGood: "The files that I sent are in your inbox.",
    exampleBad: "The files who I sent are in your inbox.",
    sisters: ["relative-pronouns"],
    related: ["relative-pronouns"],
  }),
  live({
    id: "first-vs-second-conditional",
    title: "First vs second conditional",
    level: "B1",
    phase: 4,
    keyword: "first vs second conditional",
    rule: "First (if + present, will) is a real possible future. Second (if + past, would) is unreal now or a remote future. The other pages teach each form; this page is which to choose.",
    exampleGood: "If I won the lottery, I would travel. (unreal)",
    exampleBad: "If I win the lottery, I would travel.",
    sisters: ["first-conditional", "second-conditional"],
    related: ["first-conditional"],
  }),
  live({
    id: "present-perfect-vs-present-perfect-continuous",
    title: "Present perfect vs present perfect continuous",
    level: "B1",
    phase: 4,
    keyword: "present perfect vs present perfect continuous",
    rule: "Have + participle often stresses a result you can see: I have written three emails. Have been + -ing stresses the activity over time: I have been writing all morning. The other pages are the two forms; this page is the choice.",
    exampleGood: "I have been writing all morning.",
    exampleBad: "I have written all morning. (if you mean the activity, not a finished count)",
    sisters: ["present-perfect", "present-perfect-continuous"],
    related: ["present-perfect-continuous"],
  }),
  live({
    id: "reported-questions",
    title: "Reported questions",
    level: "B1",
    phase: 4,
    keyword: "reported questions",
    rule: "Yes/no questions use if or whether: she asked if I was ready. Wh- questions keep the question word and statement order: she asked where I lived. Tense usually moves back. Indirect questions are polite questions now, not reports of what someone asked.",
    exampleGood: "She asked where I lived.",
    exampleBad: "She asked where did I live.",
    sisters: ["reported-statements", "indirect-questions"],
    related: ["reported-statements"],
  }),
  live({
    id: "lay-vs-lie",
    title: "Lay vs lie",
    level: "B1",
    phase: 4,
    keyword: "lay vs lie",
    rule: "Lay needs an object (put something down): lay the keys on the desk; past laid. Lie has no object (recline): lie on the sofa; past lay. The present of lie is not the past of lay.",
    exampleGood: "Lay the keys on the desk.",
    exampleBad: "Lie the keys on the desk.",
    sisters: [],
    related: ["make-vs-do"],
  }),
  live({
    id: "future-perfect",
    title: "Future perfect",
    level: "B2",
    phase: 4,
    keyword: "future perfect",
    rule: "Will have + past participle for an action finished before a future point: by 6 I will have left. Will + base is a simple future. Will be + -ing is an action in progress at a future time.",
    exampleGood: "By 6 I will have left.",
    exampleBad: "By 6 I will have leave.",
    sisters: ["future-continuous", "future-simple"],
    related: ["future-simple"],
  }),
];

export function getTopic(id: string): Topic | undefined {
  return TOPICS.find((topic) => topic.id === id);
}

export function liveTopics(): Topic[] {
  return TOPICS.filter((topic) => topic.status === "live");
}

export function getRelatedLive(topic: Topic): Topic[] {
  return topic.related
    .map((id) => getTopic(id))
    .filter((item): item is Topic => item !== undefined && item.status === "live");
}
